### ISSUE TITLE
Report filtering issue - Data does not change when you increase the date range from the default 30 days displayed.

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#1034]
**Describe the bug**
When we change the filter to show 90 days(or any other times)  from the default.  It still shows the original 30 days data and doesn't parse the changed filters for different dates.

**What version are you running?**
4.3.4
**Did this happen on prior versions to the one you are running?**

**To Reproduce**
1. Go to 'Reports'
2. Click on 'service bodies' and select the service body you want to report on.
3. Take not of initial report details
4. change date range to a different longer time period.
5. Report data does not change from the original 

**Expected behavior**
We expect to see a longer date range shown when a longer period is selected.

**Screenshots**
30 days
![image](https://github.com/bmlt-enabled/yap/assets/29008815/7e6300e9-b6e2-455e-bfc5-a48772c624fc)

90 days
![image](https://github.com/bmlt-enabled/yap/assets/29008815/5c3e46ef-79fa-4309-9b08-eca8e30b111b)

**Additional context**
Problem exists on both 4.3.3 and 4.3.4

**Comment by dgershman** [comment]
Did you try to use a specific date range also, rather than a preset date range?

Can you share the URL in the developer tools what was is logged in the network tab when you switch between 30 and 90 days also?

**Comment by brustar64** [comment]
Testing Jan 1 to Feb 29
![image](https://github.com/bmlt-enabled/yap/assets/29008815/860256dd-ba39-4930-b58a-2f8c43bc8392)

Testing Jan 1 to April 30
![image](https://github.com/bmlt-enabled/yap/assets/29008815/e6d6ea69-ebba-4400-a936-013004b45593)

**Comment by brustar64** [comment]
> Can you share the URL in the developer tools what was is logged in the network tab when you switch between 30 and 90 days also?

Which developer tools extension should I be using?

**Comment by brustar64** [comment]
I'm not sure if this is what you mean.



Request URL:
https://c.tile.openstreetmap.org/6/57/38.png
Request Method:
GET
Status Code:
200 OK (from disk cache)
Remote Address:
151.101.97.91:443
Referrer Policy:
strict-origin-when-cross-origin
Accept-Ranges:
bytes
Access-Control-Allow-Origin:
*
Age:
9572
Alt-Svc:
h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control:
max-age=13309, stale-while-revalidate=604800, stale-if-error=604800
Content-Length:
15422
Content-Type:
image/png
Date:
Mon, 06 May 2024 09:07:13 GMT
Etag:
"aa3a38216c7e2edb1ffa9bed5f04b90f"
Expires:
Mon, 06 May 2024 10:09:30 GMT
Server:
Apache/2.4.54 (Ubuntu)
Via:
1.1 varnish
X-Cache:
HIT
X-Cache-Hits:
6

X-Served-By:
cache-bne12526-BNE
X-Tilerender:
bowser.openstreetmap.org
X-Timer:
S1714986433.307835,VS0,VE1

**Comment by brustar64** [comment]
[na.org.au.har.txt](https://github.com/bmlt-enabled/yap/files/15218898/na.org.au.har.txt)
Attached the HAR file

**Comment by dgershman** [comment]
The HAR file doesn't seem to contain queries that relate to loading up a report.  Please send one that is capturing those requests.

**Comment by brustar64** [comment]
[na.org.au 30 then 90.har.txt](https://github.com/bmlt-enabled/yap/files/15245487/na.org.au.30.then.90.har.txt)

**Comment by brustar64** [comment]
This range shows 90 days. 
![image](https://github.com/bmlt-enabled/yap/assets/29008815/a31d53d3-897e-4619-8553-bd7ebe6686f5)
but the output data is only until April 29
![image](https://github.com/bmlt-enabled/yap/assets/29008815/e0ead1f4-8d89-447c-bd4a-c5bd47ae7d56)

**Comment by dgershman** [comment]
nevermind, i figured out the issue, something with the display

**Comment by dgershman** [comment]
The component that we use to display call details + events has had a number of issues.  I've opted to rework this as call events being in a modal.  This should resolve the issue.  It also fixes #610.

![Screenshot 2024-05-09 at 8 55 20 AM](https://github.com/bmlt-enabled/yap/assets/1850811/5b12cbf1-a7b0-4e04-8e3b-9076b50630ab)

This will be in `4.3.5`.

**Comment by dgershman** [comment]
@brustar64 can you try this?  https://github.com/bmlt-enabled/yap/releases/download/4.3.5-beta1/yap-4.3.5-beta1.zip

**Comment by brustar64** [comment]
sent as a DM in Slack
Thanks very much.
________________________________

**Comment by dgershman** [comment]
Fixed in 4.3.5
