### ISSUE TITLE
service volunteer call records and vm 

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#105]
Unless you are the twilio admin you can’t see the call records and voicemail links.

**Comment by radius314** [comment]
this is a PITA so far.  Twilio does not do a great job at keeping track of historical participants that are in conferences.

**Comment by pjaudiomv** [comment]
No they don't, i bet it is a PITA. its kind of annoying for testing purposes to not be able to tell who the helpline tried to call.

**Comment by radius314** [comment]
Let me clarify. The twilio console does show all this detail, it's just not retrievable from the API.

**Comment by radius314** [comment]
<img width="1603" alt="twilio_console_-_voice_calls_logs_and_inbox__35_821_messages__1_089_unread_" src="https://user-images.githubusercontent.com/1850811/43009934-0c7f538e-8c0d-11e8-9f78-034c0a72516a.png">

**Comment by radius314** [comment]
<img width="1596" alt="twilio_console_-_voice_conferences_logs" src="https://user-images.githubusercontent.com/1850811/43009992-353c2e1e-8c0d-11e8-8964-df8b46ce326f.png">

**Comment by radius314** [comment]
The API does not let you get a list of participants but the UI displays it.  What I've read is that Twilio does not expose this from the API.  What they recommend is to keep your own running list, which is code for use your own database.

**Comment by radius314** [comment]
https://stackoverflow.com/questions/42481929/how-to-get-twilio-conference-participants-after-it-is-over
https://stackoverflow.com/questions/32445991/twilio-participants-on-a-completed-conference?rq=1

**Comment by pjaudiomv** [comment]
gotcha, mine hardly ever shows the outgoing api, does this only show if the call is actually picked up i guess (meaning someone joined the conference?)

**Comment by radius314** [comment]
No it should show the outgoing API regardless if the call is picked up.

**Comment by radius314** [comment]
Will be released in v3, in master now.

**Comment by pjaudiomv** [comment]
cool I just tested this too, working great.
