### ISSUE TITLE
Laravel Illuminate Errors

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#1078]
Getting this error in the Laravel log, [2024-06-17 16:37:25] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get(NULL)
#2 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(681): Illuminate\\Log\\LogManager->driver()
#3 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(317): Illuminate\\Log\\LogManager->error('Undefined const...', Array)
#4 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(278): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(497): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 /home/alsaskrsc/phoneline/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Error))
#7 /home/alsaskrsc/phoneline/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 

Ver 4.3.5

PHP 8.2

No, I was running good then this just started happening

**To Reproduce**
1.Go to https://phoneline.alsaskrsc-na.org/admin

**Expected behavior**
Show admin

**Comment by dgershman** [comment]
the config.php file had an incorrect copy and paste which contains odd single quote backticks instead of double quotes.
