### ISSUE TITLE
Using volunteer routing with Tomato

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#108]
**Is your feature request related to a problem? Please describe.**
Tomato has no knowledge if a service body has volunteer routing, configuration and volunteers.  For security reasons and BMLT sanity, all data is unpublished data and can only be reached by an authenticated user.

**Describe the solution you'd like**
When yap does it's service body lookup, it first gets the closest meeting.  From there you can pull the `root_server_uri`.  That would be mapped to a `yap_uri` and an api key (would have to be added, and received from the trusted other yap provider).   From there the yap instance could check the configuration `/service-body-config.php?service_body_id=` and then allow that yap server to handle the call (using redirects).  Once challenge would be to map the Tomato service body id to the original service body id.  Tomato has no record of this currently.

**Comment by jbraswell** [comment]
You can get the original service body id from tomato by using its REST API.

Here's a service body: https://tomato.na-bmlt.org/rest/v1/servicebodies/450/
```
{
    "url": "https://tomato.na-bmlt.org/rest/v1/servicebodies/450/",
    "root_server": "https://tomato.na-bmlt.org/rest/v1/rootservers/24/",
    "parent": null,
    "source_id": 1,
    "name": "Florida Region",
    "type": "RS",
    "description": "Florida Region Service Body",
    "service_body_url": "",
    "world_id": "RG219"
}
```

The `source_id` is the service body's id in its root server.

This `source_id` field exists on the meetings and formats resources in tomato's REST API, too.

**Comment by radius314** [comment]
In the short term added a simple way to use tomato for simple helpline dialing.  leverages being able to do extension dialing another yap instance.  `tomato_helpline_routing=true` in a webhook.

**Comment by radius314** [comment]
doing volunteer routing is going to a little more in depth.  not really a huge issue just yet.

**Comment by pjaudiomv** [comment]
So if you wanted to use this with a helpline you could set your helpline field to same number and append with |wwww1 ?

**Comment by radius314** [comment]
The way that NC region is using it, is that they are setting up a statewide number.  Tomato pulls the helpline field on its regular sync, and thusly it's able to use that for routing.  Since we are using override_service_body_id on some of the ASC numbers, we can pause and press 1 to skip meeting finding.  If someone directly calls that number, they get meeting finding.

**Comment by pjaudiomv** [comment]
Actually that didn't make sense

**Comment by pjaudiomv** [comment]
Cool that does make sense thanks

**Comment by radius314** [comment]
Ok, let me re-explain.  Let's say 888-111-2222 was a statewide number webhook pointed to `http://example.com/yap/?tomato_helpline_routing=true`.  Let's say you search for an ASC that is using Yap volunteer routing, but it's in a different root server.  Tomato cannot read any of those values because they are hidden behind authentication (containing PII = Personally Identifiable Information).  However Tomato can see the ASC phone number (888-111-3333).  So the caller is routed to that ASC number and the helpline field has 8881113333|wwww1.  This means it will call the number, pause for 4 seconds and then press 1.

The 8881113333 webhook is set up on that other yap instance as http://example2.com/yap/?override_service_body_id=x.  

If I call 8881113333 directly I get the full menu.

**Comment by pjaudiomv** [comment]
Got it thanks.

**Comment by radius314** [comment]
This doesn't make sense to do right now.
