### ISSUE TITLE
Volunteer List shows blank Groups, when using Groups

### ISSUE THREAD

**Issue by fsrnadmin** [bmlt-enabled/yap#1092]
**Describe the bug**
While Upgrading to 4.3.5, and we go to the volunteers menu, the Group names, created in Groups menu, do not show up in list of groups that are included

**What version are you running?**
4.3.5

**What PHP version are you running?**
8.0.30

**Did this happen on prior versions to the one you are running (if so what version)?**

**To Reproduce**
1. Go to Volunteers
2. Click on freestate region
3. Group names do not show up , just blank panels.
4. Actual Behavior
![actual](https://github.com/bmlt-enabled/yap/assets/91708532/6ad531ea-6200-48d4-9078-9e98c0dd46a0)

5. See error

**Expected behavior**
![expected](https://github.com/bmlt-enabled/yap/assets/91708532/d590dbd7-93ab-41ab-9296-f91a2743dbbb)

**Screenshots**

**Additional context**

**Comment by dgershman** [comment]
The names never showed up there, you need to go to the Groups tab and see who is in them.
