### ISSUE TITLE
Report page has all Zeros on ALL (Recursive)

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#1114]
Reporting Page has Zeros on all the indicies.  

v4.3.5

PHP 8.2

**Did this happen on prior versions to the one you are running (if so what version)?**  Not sure when it broke.

**To Reproduce**
1. Go to 'Reports'
2. See zeros in stats, but clearly shows items in graph above.
3. 
**Expected behavior**
Expected counts of Meeting searches, Volunteer calls, percent answered.

![image](https://github.com/user-attachments/assets/e201188c-2e56-45c1-a540-62c3fdbc6590)

**Comment by dgershman** [comment]
It doesn't look like Recurse is on.

**Comment by gutterwall** [comment]
Recusion was checked...

**Comment by dgershman** [comment]
Can you email me your database?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
Fix will be in Yap 4.4.0
