### ISSUE TITLE
Move Skipping Helpline Call Routing instructions to a different section in documentation

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/yap#1119]
I was looking for the instructions to configure Twilio to only do meeting searches and it took me a few minutes to find the instructions under Skipping Helpline Call Routing (https://yap.bmlt.app/helpline/skipping-helpline-call-routing). I was thinking maybe this documentation would be better in a different section because it's really not about Helpline/Volunteer Routing. Maybe it's better under the General section, or the Meeting Search section, or the Miscellaneous section. LOL. Just a thought. 

Maybe it could be a 7.a. under Setup in General? Or just a quick note in step 7 in Setup that links to wherever else in the documentation it lives.

**Comment by dgershman** [comment]
It was moved to general, and I added a note under 7 on the setup page.
