### ISSUE TITLE
Volunteer's not scheduled if timezone missing

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/yap#1121]
If a volunteer shift does not have a timezone set it causes all volunteer shifts to fail. This can be visually seen in the schedule and calling results in no transfer to any volunteer

**What version are you running?**
v4.3.5

**What PHP version are you running?**
8.2.22

**Did this happen on prior versions to the one you are running (if so what version)?**
Initial install

**To Reproduce**
1. Go to Volunteers
2. Create a test volunteer, properly fill out all info except timezone
3. Enable volunteer and click save volunteers
4. Schedule will be empty and incoming calls won't be transfered to volunteers

**Expected behavior**
Should not allow saving if timezone not set

**Comment by dgershman** [comment]
How did you make it so that there is no time zone set?

**Comment by klgrimley** [comment]
It's not a required field so if you leave it blank it will save without a timezone chosen

**Comment by dgershman** [comment]
Yeah I could even figure out how you were able to set it as a blank value.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by klgrimley** [comment]
At least for us the placeholder/default option is blank. Guessing that passes null or empty when saved. 
![Screenshot 2024-08-26 at 8 48 20 AM](https://github.com/user-attachments/assets/47d7cadd-9c31-4c91-99cf-b7beb59b1417)

**Comment by dgershman** [comment]
Weird.  Does it happen just for you?  Or for other people?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by klgrimley** [comment]
Looking at the rendered markup that's actually kind of interesting I would expect `<option value="Africa/Abidjan">Africa/Abidjan</option>` to be the default option

**Comment by klgrimley** [comment]
Both myself and one of our Area PR chairs have this happen. It was actually one of the shifts that she entered that brought it to my attention

**Comment by dgershman** [comment]
Any browser and/or OS in particular?  The same result regardless or browser?  Its supposed to use your computer time to determine the time zone you are in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by klgrimley** [comment]
I'm mac. Happens on both my intel pro and M2 air. Both using chrome. I've asked the Area person what she was using and will let you know.

When using firefox it does populate with my timezone

**Comment by klgrimley** [comment]
Brave and Safari also do not populate. I saw Africa/Abidjan for a second in each of them before it turning blank. Assuming that's what I saw. It was so quick I couldn't really read it

https://github.com/user-attachments/assets/7c7967c9-d9e6-469d-b273-711a23acbce1

**Comment by klgrimley** [comment]
The Area PR chair is using an Android phone. She said her browser is Google so guessing that means Chrome. Could this be a browser engine issue?

**Comment by dgershman** [comment]
Ok cool this is helpful.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by klgrimley** [comment]
Let me know if there's any other info I can provide

**Comment by dgershman** [comment]
Fix will be in Yap 4.4.0

**Comment by dgershman** [comment]
Can you give this a try?  https://github.com/bmlt-enabled/yap/releases/download/4.4.0-beta1/yap-4.4.0-beta1.zip
