### ISSUE TITLE
add consent phrase to reports to mollify Twilio

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#1144]
Earlier versions of yap included a note that the caller had consented to receive SMS texts in the reports.  This was needed to make Twilio happy when attempting to register yap numbers (or at least it helped).  This has disappeared in the current version.  It would be good to restore it.  Specifically, in the event description of a request for meetings by SMS, add the phrase “Caller Consented to Receive SMS”.  So the revised description would be

`Caller Consented to Receive SMS; Meeting Search Location Gathered`

This reflects the fact that the system tells the caller that they will get an SMS text before they press 1 or 2 to search for meetings by city or by zip code.  See the blog post https://bmlt.app/registration-requirements-for-yap-helpline-numbers/ and the sample application for more details.

**Comment by dgershman** [comment]
Ok will look into this.  Not sure how this regressed.

**Comment by dgershman** [comment]
ref: https://github.com/bmlt-enabled/yap/pull/713

**Comment by dgershman** [comment]
The language that was submitted in this feature was "Meeting search results will also be sent to you by SMS text message”.  It has always been present.

**Comment by dgershman** [comment]
<img width="1202" alt="Screenshot 2024-09-09 at 9 34 27 PM" src="https://github.com/user-attachments/assets/36516533-109e-4867-97d8-f1c9f539179c">

Fix will be in Yap 4.4.0
