### ISSUE TITLE
Volunteer schedule by months or by 5 weekly schedules (EG First Monday fo the month ETC)

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#115]
**Feature Request**

One of our largest Regional Phone line services is Sydney Metro which provides services for all 4 Sydney Areas - East, West, North and South.

They currently organise their roster for a each volunteer rostered on for a single 24hour period each month.  During that time frame the helpline number is diverted to the volunteer's number.

After explaining how YAP works and how it organises volunteers they felt that it would not work for them as their current approach with having volunteers commit to a full 24 hour period of service each month works well for them.

**Describe the solution you'd like**
It would be really great to have a volunteer roster that could be organised around a monthly schedule. 

**Describe alternatives you've considered**
I suggested that they could start to organise differently and that there was now an option to organise around volunteers who were situated actually in the 4 different geographical areas who would be better positioned to do 12 step calls or picking someone up to take them to a meeting etc.
They are going to consider this approach but there is some resistance from the Coordinator who felt that the way its currently organised is working well and if its not broken there's no need to fix it.

**Additional context**
An option to choose First XXXday of the month, Second XXXday or the month ETC. could possibly work well.  Then they could look ahead and see the gaps for 5 week months and schedule someone in on those days.

**Comment by radius314** [comment]
What if this were a feature where you set the schedule one way, and then it bumped automatically by 1 for each day of the week or the week of the year?

**Comment by brustar64** [comment]
Hi Danny,

This could work, particularly if they are used to working on their particular date in the month.

To be honest though, I'm ok if we drop this feature request.

The way I plan to set up the Sydney volunteers (who are the ones who organise their volunteers this way), is to just enable each set of 7 volunteers for and disable the previous set once each week.

With the system they've been using the coordinator has to change the diversion every single day.

I thought about having groups where each week is comprised from 7 volunteers but the challenge with doing it this way is if someone can't do it for one particular week, they'll have to edit the group.  I think its probably easier to just disable the volunteer who is unable to do the shift an enable another volunteer (potentially the coordinator who usually fills in for someone who can't do their shift) who would be set up on 24/7 but usually disabled. The next day the coordinator just disables himself/herself.

Thanks again for all your work on YAP.  We are almost there with the whole of Australia on YAP.  Just Sydney to go now....

Yours in service
Bruce
________________________________

**Comment by radius314** [comment]
The could be an opportunity for the future to have someone be able to enable or disable themselves, but it's a ways off.

**Comment by dgershman** [comment]
Not going to implement this.
