### ISSUE TITLE
Session time out while entering volunteers

### ISSUE THREAD

**Issue by jbutler58** [bmlt-enabled/yap#1155]
**Describe the bug**
I was in the process of adding volunteers when my session timed out.  I hadn't saved since I was still adding volunteers and I had the expectation that if I was actively using the application that it wouldn't timeout.  I lost all the work I had done. 

**What version are you running?**
4.4.0

**What PHP version are you running?**
not sure

**Comment by dgershman** [comment]
How long were you on the page for?  The timeout doesn't get reset until you reload the page.  It's not based off activity on the page.

**Comment by dgershman** [comment]
The entire session structure has been refactored.  This will be fixed in Yap 4.5.0
