### ISSUE TITLE
Group volunteers gone after 4.4.0 update

### ISSUE THREAD

**Issue by timbdesigns** [bmlt-enabled/yap#1194]
**Describe the bug** When I update to 4.4.0 all the volunteers in a group disappear.

**What version are you running?** 4.3.5

**What PHP version are you running?** 8.3.12

**Did this happen on prior versions to the one you are running (if so what version)?**

**To Reproduce**
<img width="1355" alt="Screenshot 2024-10-15 at 3 26 02 PM" src="https://github.com/user-attachments/assets/45c134c0-b423-4056-8fd3-5885b65b337f">

**Expected behavior**
<img width="1920" alt="Screenshot 2024-10-15 at 3 21 36 PM 2" src="https://github.com/user-attachments/assets/841d8e2b-3d84-4e63-bcde-5f60d70aa64a">

**Screenshots**

**Additional context**

**Comment by dgershman** [comment]
Able to reproduce.  Working on a fix.

**Comment by dgershman** [comment]
Can you try this fix?  https://github.com/bmlt-enabled/yap/releases/download/4.4.1-beta1/yap-4.4.1-beta1.zip

**Comment by timbdesigns** [comment]
That works Thanks! One other issue I noticed back in 4.4.0 as well as 4.4.1 beta is in reports the meeting lookup data isn't showing.
<img width="1181" alt="Screenshot 2024-10-30 at 6 31 24 PM" src="https://github.com/user-attachments/assets/d39cec05-11e2-4eb9-b82c-794dab047f0d">

**Comment by dgershman** [comment]
can you open a separate issue for this?

**Comment by dgershman** [comment]
@timbdesigns can you open a ticket and provide full information about this?
