### ISSUE TITLE
SMS All Helpline Volunteers

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#121]
**Describe the solution you'd like**
It would be really great if we could send an SMS messages using the YAP Admin interface to:
1. all helpline volunteers for a service body
2. all helpline volunteers for an entire region
3. single helpline volunteer

**Describe alternatives you've considered**
Haven't really considered any other options - I'm sure there could be something configured in Twilio but I'd like to leverage the YAP admin interface as a communication tool for helpline volunteers as it's already got all the information.

**Comment by radius314** [comment]
Are you thinking of this an internal notification tool?

**Comment by brustar64** [comment]
Yes :-)

Regards
Bruce

________________________________

**Comment by radius314** [comment]
After much thought, this feature will not be implemented.  It's not core to phonelines and would like to keep the bloat down.

**Comment by brustar64** [comment]
I understand and respect your decision.  Thanks Danny.
I'll try to be more discerning in relation to future feature requests that they are features that go directly to fulfilling our primary purpose.
