### ISSUE TITLE
When English/Spanish enabled, title is no longer read

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#1228]
**Describe the bug**
When English/Spanish enabled, the title is no longer read.  Similarly, if there is a custom greeting, it is no longer played if English/Spanish is enabled.

**What version are you running?**
4.1.1

**What PHP version are you running?**
PHP version 8.1.29

**Did this happen on prior versions to the one you are running (if so what version)?**
Don't know.

**To Reproduce**
1. In the Configuration for an area, add a title and `en-US,es-US `for `language_selections`.
2. Call the helpline.

**Expected behavior**
Yap should first read the title, then ask which language the caller wants.  If there is a custom greeting, it should still be played.

**Comment by dgershman** [comment]
I'm not sure this ever worked.  How did you have this configured?

**Comment by dgershman** [comment]
The issue with why the `title` is not said first is because you wouldn't know what language to say it in.  So ultimately it was a design decision at the time this was implemented to not declaratively say a title in a bunch of languages.  I'm open to implementing this another way that would make sense for all service bodies.

Interestingly enough, there was a bug fix for overriding words for different languages that was broken.  

Question, why is this marked a bug?

**Comment by alanb2718** [comment]
If I call the helpline, I'd like it to say that it's the helpline .... if I just hear "press 1 for English, 2 for Spanish" how do I know what I'm calling?  I marked it as a bug because I thought this must have worked at some point in the past.  But clearly I was wrong about that.

I agree, it's not entirely clear what to say if yap is reading the title with the automated voice.  A reasonable choice would be to read it just in the first language.  But if we want to not do that, how about at least playing the recorded greeting if one is provided?  In that case, the service body can decide what to say there (but including the "press 1 for English, 2 for Spanish" part).

**Comment by dgershman** [comment]
Yes the challenge is that you don't know what language to say "this is the helpline" in because you haven't said it yet.

**Comment by dgershman** [comment]
I think the way to solve this is to let someone record their own prompt and then it can cover whatever you want it to.

**Comment by dgershman** [comment]
Will be in 4.5.0
