### ISSUE TITLE
Volunteer database import

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#128]
We have a current database of about 120 volunteers with phone numbers and service body info we would like to bring into Yap.

**Comment by radius314** [comment]
this is a feature for a one-time operation?

**Comment by Redguy1959** [comment]
We may want to refresh it on a regular basis from an external source.
  ----- Original Message -----

**Comment by radius314** [comment]
Any feature of this nature would conform to a specific CSV format that Yap would expect.  The external source would have to be formatted to this request.  

A couple of things here:

1) No one else has asked for a request like this, so it would be pushed to the bottom of the stack.
2) What are the assumptions about scheduling?  Days + times?
3) What are your timelines, given that this is a low-priority feature request?

**Comment by Redguy1959** [comment]
If it was a one-time import, could it be handled more quickly?

----- Original Message -----

**Comment by Redguy1959** [comment]
Currently, everyone is scheduled 24/7.
  ----- Original Message -----

**Comment by radius314** [comment]
Thanks.

**Comment by Redguy1959** [comment]
Hi Danny, we have recently verified our volunteer list and would like to revisit this one-time database import.
  ----- Original Message -----

**Comment by radius314** [comment]
It’s not likely that this will happen by me.  Not sure who else would be willing to volunteer to do this.

**Comment by Redguy1959** [comment]
You mention an undocumented API. I have a test BMLT system in addition to the live one. If you have any API instructions I can try it myself.
  ----- Original Message -----

**Comment by radius314** [comment]
After further investigation, it’s not going to work.  There is no
documentation that I will be able to provide.

**Comment by Redguy1959** [comment]
OK, I will get some poor sucker to input them by hand.
  ----- Original Message -----

**Comment by radius314** [comment]
Yeah that’s my suggestion.  It’s not worth sweat equity to develop a feature here.  This would take away from the ton of new features in Yap 3.x

**Comment by Redguy1959** [comment]
Hi Danny,

Happy Holidays!

We have our Helpline Committee meeting tomorrow. Do you have a .pdf of the documentation available here https://yap.bmlt.app/ ?

Thanks,

--Paul R.

**Comment by pjaudiomv** [comment]
[yap.pdf](https://github.com/bmlt-enabled/yap/files/2703731/yap.pdf)

**Comment by Redguy1959** [comment]
That's just one page - did that already. I am looking for the entire documentation as a single .pdf. 
  ----- Original Message -----

**Comment by pjaudiomv** [comment]
that pdf is 28 pages long

**Comment by radius314** [comment]
Patrick you could also do this: https://github.com/abeMedia/jekyll-pdf

>

**Comment by Redguy1959** [comment]
You are correct, I see all 28 pages when opening offline, not in Chrome.

Thanks!
  ----- Original Message -----

**Comment by pjaudiomv** [comment]
cool thanks danny ill check that out
