### ISSUE TITLE
Select Volunteers by Language 

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#146]
We have a fairly large community of Farsi and Vietnamese speakers in the Australian NA Community and it was asked if there was a way of configuring an option to ask to choose someone based on language (rather than location).

**Describe the solution you'd like**
We would like to be able to add a prompt to ask to speak to someone in alternative language and perhaps set up "Areas" with volunteers who speak those languages to be routed to. 

**Describe alternatives you've considered**
Haven't thought of any alternatives.

**Comment by pjaudiomv** [comment]
This is mostly available here https://github.com/radius314/yap/blob/master/README.md#language-options

**Comment by pjaudiomv** [comment]
The only difference would be redirecting the call to a single 'area' depending on language selection

**Comment by pjaudiomv** [comment]
Which I think at least one other person has requested this

**Comment by pjaudiomv** [comment]
In the meantime a good place to start would be getting translations for everything in the lang folder

**Comment by pjaudiomv** [comment]
I'm not sure how Farsi would work though as it's written right to left?

**Comment by radius314** [comment]
Put left to right in the quotes

**Comment by pjaudiomv** [comment]
Twilio doesn't support Farsi but does Vietnamese. Farsi would have to just be a language->service body redirect to helpline I think

**Comment by brustar64** [comment]
Thanks guys with your insights into this.
I'll take it back to the committee.
We can work on the Vietnamese translations...
________________________________

**Comment by radius314** [comment]
@brustar64 were you able to test this?

**Comment by brustar64** [comment]
Is this configured by creating a language group?

**Comment by radius314** [comment]
There is a two-part step to this.  

1) Enabling language call routing: https://yap.bmlt.app/docs/general/language-options/
2) Tagging volunteers with language(s).  

Groups are not required.

**Comment by californiasteve** [comment]
Has anyone created a Spanish one?

**Comment by radius314** [comment]
There hasn’t been one done yet.

**Comment by californiasteve** [comment]
I'm working on one right now with Johnny Lamprea. Should be ready by the weekend. 




Steve Scranton 


210.279.9199







On Mon, Mar 18, 2019 at 8:11 PM -0500, "Danny Gershman" <notifications@github.com> wrote:










There hasn’t been one done yet.





On Mon, Mar 18, 2019 at 8:53 PM Steve Scranton <notifications@github.com>


wrote:

**Comment by brustar64** [comment]
An initial issue is that once I've added in another language in the config file the "Title" gets read out but the audio file doesn't get played.  Not sure whether or not this is a precedence issue in my config file...
In terms of functionality it appears to route to volunteers in pig-latin or English. I don't speak pig latin very well so I'm challenged by the prompts but in terms of functionality it seems to work.

**Comment by radius314** [comment]
Have you set the prompt for that specific language?

**Comment by brustar64** [comment]
This is what's set:
<?php
static $en_AU_greeting ="https://na.org.au/audio/naintrov5.mp3";
static $title = "Thank you for calling Narcotics Anonymous Australia. This service helps connect you with Narcotics Anonymous helplines around Australia, or find meetings during the next 24 hour period near the location you choose. Don't worry about trying to write anything down as this service will SMS you the three closest meetings with directions. If there are no convenient meetings near your location, look for an online meeting on the Narcotics Anonymous Australia website";
static $language_selections = "en-AU,pig-latin";

However If i change the language selection to en-US or the greeting to $en_US_greeting it doesn't seem to have any effect (other than the accent of the reader).  It still reads out the title.  If I remove the title I get an error on the Yap status page advising that the Title is missing.

**Comment by radius314** [comment]
Have you tested the rest of the functionality.

**Comment by californiasteve** [comment]
It's working on my instance.

**Comment by radius314** [comment]
I’m not sure I’m understanding the prompt issue.  If you have two languages you need to create a specific the audio file for both of them.

**Comment by radius314** [comment]
You would need to do the following:

For example if you have the following language selections:

static $language_selections = "en-AU,pig-latin";

You'd need to do this (have both)...

static $en_US_greeting = "test_en.mp3";
static $fr_CA_greeting = "test_fr.mp3";

**Comment by brustar64** [comment]
It reads it before any language prompts.

**Comment by radius314** [comment]
It should first be asking for the language.

**Comment by radius314** [comment]
```
static $language = “en-AU”
static $gather_language = “en-AU”
static $language_selections = “en-US,fr-CA”;
static $en_US_greeting = “test_en.mp3”;
static $fr_CA_greeting = “test_fr.mp3";
```
