### ISSUE TITLE
New Messaging Send Functions Cause Errors on Landlines

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#171]
If calling from a landline the SMS functions now throw errors in the Twilio console.  it's not terrible but it's related to the Destination Handset Unknown errors.

**Comment by radius314** [comment]
I think it's impossible to detect this.

**Comment by pjaudiomv** [comment]
Yea I looked into it too, and came up with same result. Seems you'll either get those errors or use sms ask if you don't want to see errors for some reason.

**Comment by radius314** [comment]
Opening a support ticket with Twilio.  If there isn't an obvious solution, I think it makes sense to add something to the documentation possibly.

**Comment by pjaudiomv** [comment]
Cool agreed.

**Comment by pjaudiomv** [comment]
More will be revealed as we say.

**Comment by radius314** [comment]
Apparently, the Lookup API lets you do this https://www.twilio.com/docs/lookup/api.   Would add an additional 0.005 per call.

**Comment by pjaudiomv** [comment]
that information isn't %100 accurate and can return null results, but would certainly weed some out. I found this out when playing with their lookup api for nationwide phoneline.

**Comment by radius314** [comment]
Ah, yeah I wonder if it’s worth the sweat equity and cost to add this error handling.

**Comment by pjaudiomv** [comment]
I don't know that it is, I do remember it was more accurate with mobile devices. like more times than not it could tell you a device was a mobile, but couldn't neccisarily tell you if it was a landline.
