### ISSUE TITLE
add ability to block numbers from user interface

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#183]
as phone chairs often may not have the technical expertise to edit a config.php file and this feature is easy to use on existing non yap phone systems, It would nice to be able to have this feature included in the web interface in a future version.

**Comment by pjaudiomv** [comment]
Im not sure how this would be implemented or work with different user levels and such so just leaving here for discussion

**Comment by radius314** [comment]
there is really only one user level in yap.  service body administrator that has rights to said service body.

**Comment by pjaudiomv** [comment]
yes and it would make no since to try and block numbers only for for certain service bodies, there are a couple features like this that would be a nice enhancement but would most likely require a different user level.

**Comment by pjaudiomv** [comment]
theoretically could there be a reserved user login, like say if you had a bmlt user yap_phone_admin, could potentially yap treat that login differently

**Comment by radius314** [comment]
Not sure I fully understand the use-case, and what other features would be included.

**Comment by pjaudiomv** [comment]
this has been asked before, adding features that are normally only set in the config.php or querystring in the admin ui

**Comment by radius314** [comment]
It's not a question of implementation, it's a question of the user persona and how they differ from the server admin.

**Comment by pjaudiomv** [comment]
gotcha

**Comment by pjaudiomv** [comment]
so without an enhancement to bmlt semantic admin this wouldnt be possible

**Comment by pjaudiomv** [comment]
and possibly more i guess

**Comment by radius314** [comment]
Totally untrue.  There are other ways to "bless" a user.

**Comment by radius314** [comment]
Gonna leave this alone, it would be quite some time before this would be implemented, given how high class of a problem this is.

**Comment by pjaudiomv** [comment]
yes its not something I need, I mainly was thinking of making it easier for phone line chairs to configure certain aspects

**Comment by pjaudiomv** [comment]
you can close this if wanted, I could open up a more general feature request on this topic at some point

**Comment by radius314** [comment]
this will be do-able in Yap 3.x

**Comment by radius314** [comment]
on the latest beta, go to service bodies, then under configuration you should be able to add items to the "blocklist"

**Comment by radius314** [comment]
to use the blocklist you can use either override_service_body_id or override_service_body_config_id.  The 2nd one will not force calls to be routed to a specific service body.  Also configuration settings are inherited from the service body above it.

**Comment by radius314** [comment]
can you test this?
