### ISSUE TITLE
IE11 javascript error.

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#188]
Missing semicolons and getmeetings function not found on Yap.

**Comment by radius314** [comment]
How does this relate to Yap?  Can you send a screenshot?

**Comment by radius314** [comment]
File crouton tickets here https://github.com/bmlt-enabled/crouton.  Please include a full description of the bug and a screenshot (since this is a UI issue).

**Comment by radius314** [comment]
![image](https://user-images.githubusercontent.com/1850811/48665702-44c14e00-ea81-11e8-9ef6-4930df62c196.png)

**Comment by radius314** [comment]
What's the side effect of this?  I see a javascript console error, but what is the end result of the issue?

**Comment by gutterwall** [comment]
Yap admin is blank and non-functional. The volunteers, the scheduling.

**Comment by radius314** [comment]
Thanks for that clarification.

**Comment by gutterwall** [comment]
2.5.0

**Comment by gutterwall** [comment]
I just downloaded the master branch (it says 3.0 alpha) and the schedule
page is blank for me on Chrome and Edge, although it does have the shifts
on the people page.  Just thought you should know.

The IE browser still is blank with Volunteers and Schedule after you select
a service body.  I am not sure it's worth struggling to fix IE errors,
maybe just say only modern browsers work?  Edge, Firefox, and Chrome all
work great!

**Comment by radius314** [comment]
master is bleeding edge, not production ready.

**Comment by gutterwall** [comment]
I will revert to 2.5.1 then...

**Comment by radius314** [comment]
2.5.1 and master are two different things.  2.5.1 did not fix your issue.

**Comment by radius314** [comment]
2.5.1 is working off a different branch.

**Comment by gutterwall** [comment]
That one works great!  Thanks for all your help in coding and supporting
this project!

**Comment by radius314** [comment]
2.87% of the world uses IE11.  It's fair to say that it's not a good usage of time for Yap to try to make this work.
