### ISSUE TITLE
meeting results arent being filtered properly

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#189]
meetings are being returned passed meeting time (including grace period)
for instance at 2pm in the afternoon on sunday a 7:30am meeting is being returned. this seems to have been introduced in 2.5.0 with introduction of Custom Query support. I will be submitting a PR that fixes this, not sure if we should cut a 2.5.x or something idk.  im just gonna submit to master.

**Comment by radius314** [comment]
send it to 2.5.0 branch that I'm about to make.

**Comment by pjaudiomv** [comment]
cool

**Comment by radius314** [comment]
branch is called `2.5.x`
