### ISSUE TITLE
list meetings for more than one day

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/yap#202]
I was experimenting with adding this: static $meeting_search_radius = 30;
i didn't have it added to my config file.  I also didn't have the meeting limit added either until now.

If there was a rural meeting / area and I wanted to list the next 8 upcoming meetings within 30 miles.  It would stop after 1 meeting if there was only one meeting today/tomorrow.  If it could just keep listing the next day and the next until 8 meetings were listed, it seems like that would be helpful for someone looking for a meeting in a particular zip code.

**Comment by radius314** [comment]
There is a default setting of returning the 50 closest meetings.  https://yap.bmlt.app/docs/meeting-search/meeting-search-radius/

**Comment by radius314** [comment]
You can already do this with a custom query.  https://yap.bmlt.app/docs/meeting-search/custom-query/

**Comment by lucy12187** [comment]
> You can already do this with a custom query. https://yap.bmlt.app/docs/meeting-search/custom-query/

I will go see if I can figure that out! Thanks!

**Comment by lucy12187** [comment]
static $custom_query="&services[]={SETTING_SERVICE_BODY_ID}" is the example, but I would want to use the {DAY} - will use the day of today / tomorrow.

How would i use it so it kept listing the next 8 meetings? within whatever the radius I had set... 
$custom_query="&services[]={DAY}"  ???

**Comment by radius314** [comment]
why are you wanting to use `{DAY}`?

**Comment by radius314** [comment]
Before we proceed here would like to nail down what's going on in #199

**Comment by lucy12187** [comment]
> Before we proceed here would like to nail down what's going on in #199

ok.

**Comment by lucy12187** [comment]
So we nailed down it was working as expected.... it had just never happened before because of the time i tried it was at a time when there were no meetings in the next 24 hours, it seems, that were close by.

how does the custom query work to get additional days past the default 24 hours

**Comment by lucy12187** [comment]
Nothing I try lists more than one days worth of meetings.

**Comment by radius314** [comment]
What's your search radius and how many results would be returned by a query of that nature?

**Comment by lucy12187** [comment]
I have tried both of these
static $meeting_search_radius = 40;
static $meeting_search_radius = -50;
i'm not sure if they work together or need to be separate...

But for an example.  
Say I wanted meetings in Clarksville. 
They have 8 meetings a week.
I tell YAP clarksville or the zip code and it lists 1 clarksville meeting tomorrow... and then goes on to list meetings i guess the next closest tomorrow... but Maybe it would be nice to just list all the clarksville meetings first... for tomorrow, thursday, etc.  

And I guess I'm trying to figure out the best settings.  i thought i had it all set up how it was best, but realized tonight because of the time i sent the message for meetings that i dont since it showed meeting so far away from the zip.  

I just want to see if it would be a good setting to tell it to show more than one days worth of meetings (and so far I have only been able to get it to show one day)

**Comment by radius314** [comment]
You cannot have two settings.  If you are listing 40 meetings and there at least 8 of them within 40 miles, it will never list another day.

**Comment by lucy12187** [comment]
the 40 is for miles and the -50 is for 50 closest meetings.  so i would choose one or the other.

which one would show meetings for more than one day.  using -50?

**Comment by radius314** [comment]
neither if the range is too far... you should familiarize yourself with BMLT queries before you delve deeper into this topic.

**Comment by radius314** [comment]
what i mean, is if there are 100 meetings within 40 miles and you are only listing 5, you will not get to the next day unless that time of day has passed.

**Comment by lucy12187** [comment]
so these are bmlt options and not yap by themselves.  I was just looking on the bmlt website for a list of all this but hadn't found it so assumed it was just yap settings

**Comment by radius314** [comment]
it's a combination of some magic variables and standard BMLT query

**Comment by radius314** [comment]
i feel a bit frustrated explaining this to you over email, this is not a productive form of communication.

**Comment by lucy12187** [comment]
I thought it would have an easy answer.  i apologize.  im just trying to find the best solution to not showing meetings 200 miles away.

**Comment by lucy12187** [comment]
i'll give it a rest and work on it tomorrow. you can delete this question/request if you'd like

**Comment by radius314** [comment]
The ticket was already closed as it’s not a bug.

**Comment by radius314** [comment]
Or a feature enhancement that doesn’t already exist.

**Comment by lucy12187** [comment]
ok, one more thing then i'll give it a rest.  is there not some simple setting to get meetings for more than one day?  
this
static $custom_query = "&long_val={LONGITUDE}&lat_val={LATITUDE}&geo_width={SETTING_MEETING_SEARCH_RADIUS}";
static $meeting_result_sort = 0;

only listed meetings for tuesday starting early this morning.
