### ISSUE TITLE
ability to make calls from helpline number

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#209]
my service body asked about this feature. The ability to return helpline calls or make helpline calls as the helpline number and not the volunteers number. this is a feature that grasshopper offered. Not sure how it would work with twilio without adding the helpline volunteers number as a verified number or if thats even necessary. Also not sure how this would work maybe, helpline volunteer calls into helpline enters say 9 or 0 to make call, enters pin then enters the phone number they wish to call.

**Comment by pjaudiomv** [comment]
this also wasn't something that was a deal breaker or anything, we simply had this feature before and they were asking if we could do it with yap. basically to protect anonymity and/or not having addicts returning calls to helpline volunteers personal number.

**Comment by DeathCamel58** [comment]
Doesn't Twilio support SIP? Because it does, they could just use a SIP client to make outgoing calls from your number.
[Their page about SIP](https://www.twilio.com/voice/sip-interface)

**Comment by DeathCamel58** [comment]
Just noticed that they also have [this page](https://www.twilio.com/voice/pricing/us) for pricing.

**Comment by radius314** [comment]
1) Using SIP here is overkill.
2) There is a simpler way to implement this feature.
3) This is a low priority feature given the other things that have been asked for months.

**Comment by pjaudiomv** [comment]
yup my service body didnt seemed to concerned, so just wanted to add it here for the record

**Comment by pjaudiomv** [comment]
oh wow i guess I already brought this up, well another service body brought this up

**Comment by radius314** [comment]
This would need to be more like a callback feature, rather than a dial as.

**Comment by radius314** [comment]
It should only allow calling from numbers that are already in Yap.

**Comment by radius314** [comment]
Can you describe how the feature worked in Grasshopper?

**Comment by pjaudiomv** [comment]
so for grasshopper, they had a mobile and dekstop app and from the app you could go to your missed calls or just make any call as your phone number.

**Comment by californiasteve** [comment]
I also had this request because most callers will not answer a callback from a number they don't recognize.

**Comment by radius314** [comment]
So does everyone on the volunteer list have the app and are signed in on their mobile device?  Which login do they used?  What if they don't own a mobile device or a computer (does this limit their ability to do a callback)?

**Comment by pjaudiomv** [comment]
With grasshopper every volunteer had the option of using the app, if they didn't have the ability to have the app then they couldn't do a callback as the helpline number. They may not of been able to do callback at all, can't remember it's been a awhile

**Comment by radius314** [comment]
It sounds like this would be not be a good way to develop the feature.  What I'm thinking is the following.

1) Volunteer calls back the number of Phoneline.
2) They press * (star), which is configurable to reach the callback feature.
3) There could be a validation step here added later which would prevent someone from abusing this feature by confirming they are a current volunteer.
4) They are prompted to dial the number to callback.
5) They are added to the conference while a call is made back to the calling person.  If the person called answers they are added immediately into the conference.  This allows you to leave a voicemail back if your committee allows it.

**Comment by pjaudiomv** [comment]
makes sense to me

**Comment by radius314** [comment]
We might need to add a new metric for Dialbacks (what this feature is called).  There could also be multiple phone numbers that are used for a single database, so the breakdown might be by number.  

The other way to do this is to not allow free entry of numbers to callback and instead have a special code that is entered (retrieved from the incoming SMS).  This way we know the original service body.

**Comment by radius314** [comment]
delivered in master as an MVP, needs some kind of access control however.

**Comment by pjaudiomv** [comment]
I tested this and is working

**Comment by radius314** [comment]
will be in 3.5.0
