### ISSUE TITLE
Overnight Shift

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#210]
When adding volunteers that have an overnight shift (6 pm - 8 am) it would be nice for it to pick up that end time is after the start and add it to the next day. Right now if you enter it 6 pm to 8am defaults to 8 pm. I'm sure there's some logic that will have to happen here. Right now we are adding it to both days but I'm not sure if it covers the whole time or misses a minute, ie 6 pm to 11:59 pm to 12:00 am to 8 am the next day.

**Comment by radius314** [comment]
It covers the whole time.

**Comment by californiasteve** [comment]
I'm not seeing that on the schedule page.
![image](https://user-images.githubusercontent.com/31661648/49177810-c469db00-f313-11e8-83be-173071b77672.png)

**Comment by californiasteve** [comment]
The overnight Wed is a 6 pm to 8 am.
![image](https://user-images.githubusercontent.com/31661648/49177886-f8dd9700-f313-11e8-9bcc-56b6e03c1742.png)

**Comment by radius314** [comment]
you need to specify as two separate shifts.  6:00 PM to 11:59 PM and then 12:00 PM to 8:00 AM

**Comment by radius314** [comment]
Yap currently doesn't support crossing over the midnight barrier for shift selection.

**Comment by radius314** [comment]
We need to add some javascript validation here to prevent someone from getting into this state.  It's somewhat of a known issue.

**Comment by radius314** [comment]
will be available in yap 3.0.1
