### ISSUE TITLE
Route voicemail to volunteers, not just the coordinator

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#211]
I'd like to be able to route voicemail to helpline volunteers not just the coordinator.
We have a particular Area which has a single volunteer on per shift and they are not keen on the voicemail to email solution.

**Describe the solution you'd like**
if a call comes through and there is only a single volunteer we would like to ability to route the voicemail to the volunteer or the coordinator (or both)

**Describe alternatives you've considered**
Just the shared mailbox but they are saying it's complicated for volunteers to set up. (I disagree but I'm just the messenger)

**Additional context**
This would empower volunteers if they accidentally miss a call.  They'd get the voicemail straight away.
Not sure how it would work with multiple volunteers... Maybe only enable this if you have a single volunteer on per shift.

**Comment by pjaudiomv** [comment]
you can currently add multiple voicemail notifications per service body, simply comma separate the values. this can be done with both numbers and emails.  so ex. 508-555-1212, 617-555-1212, 555-555-1212   or someemail@domain.com, somevolunteer@domain.org

**Comment by pjaudiomv** [comment]
https://yap.bmlt.app/docs/helpline/voicemail/

**Comment by brustar64** [comment]
That's understood however that will send voicemail irrespective of the volunteer's shift whereas I'd like to limit it to when they are rostered on.

Regards
Bruce

________________________________

**Comment by pjaudiomv** [comment]
true true. makes sense.

**Comment by radius314** [comment]
This is a reasonable feature request.

**Comment by brustar64** [comment]
Hi Danny, 
I noticed that this option was removed from the Backlog.  Does this mean its been integrated into YAP 3 now?
Thanks in advance.

**Comment by radius314** [comment]
I am limiting what goes into Yap 3.0, given it's a large release already.  It would be available in a subsequent release.

**Comment by brustar64** [comment]
Thanks Danny
Understood.
Will I need to re-request it when we have gone live?
Regards
Bruce

Regards
Bruce

________________________________

**Comment by radius314** [comment]
The ticket is still present, not closed, so it will be handled eventually.

**Comment by radius314** [comment]
This is in master now and slated for yap 3.0.0-beta4

**Comment by radius314** [comment]
@brustar64 can you test this?

**Comment by brustar64** [comment]
Will do later tonight

Regards
Bruce

________________________________

**Comment by radius314** [comment]
@brustar64 reported this feature wasn't working.

**Comment by radius314** [comment]
patched in beta6.1

**Comment by radius314** [comment]
@brustar64 were you able re-test this?

**Comment by brustar64** [comment]
Yes - this now works perfectly
