### ISSUE TITLE
Volunteers disappearing from one of our Areas

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#215]
**Describe the bug**
On two occasions we have lost quite a few of the volunteers for one area.
The first time all volunteers were deleted except for 1.
The next time half the their shift times have all been moved to the same time on the same day.
The Service body had a login but I was unable to see any evidence that they had logged in when looking at the BMLT logs (Under YAP DATA) in the meetings).
An error which I get if I do open one of these "meetings" to read the history is that I'll lose changes if I exit now but I haven't changed anything (I'm pretty sure this is a BMLT bug but its actually got me nervous now).

**What version are you running**
YAP version 2.5.1
BMLT Root Server 2.11.1

**To Reproduce**
Unable to reproduce the error or identify when the volunteers were removed (is this a function of some other error/save issue?)

**Expected behavior**
We expect Volunteers to remain configured

**Comment by jbraswell** [comment]
I would like to investigate the possible BMLT bug you pointed out. The one about being warned that you’ll lose changes when switching between meetings. Will you reach out on Slack with some temporary credentials and reproduction steps?

**Comment by radius314** [comment]
I got a dump of the db, would that work?

**Comment by jbraswell** [comment]
Yeah, probably

**Comment by brustar64** [comment]
I'm closing this - there have been no disappearing volunteers since I took over managing their volunteers.
