### ISSUE TITLE
Weather closings

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#216]
An option for weather closings?  I dont know the best way to request it or best practices

**Comment by pjaudiomv** [comment]
in my area we mark the meetings as unpublished for weather closings, this way it wont show up in bmlt. then when weathers nice mark as published again.

**Comment by radius314** [comment]
Update the title to indicate so?  Seems like something that would apply at the BMLT data level.

**Comment by radius314** [comment]
It's likely that this feature would never be implemented.
