### ISSUE TITLE
Twilio errror, Invalid content was found starting with element 'br'. One of '{Sms, Message, Redirect}' is expected.

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#217]
I'm getting this response from Twilio. I have tried a new number thinking it could be something with there number but it still errors. I have reloaded the instance twice to make sure with a fresh download (2.5.1) also. Help!
![image](https://user-images.githubusercontent.com/31661648/49950401-5699e380-febd-11e8-9969-44f31b4c6019.png)

![image](https://user-images.githubusercontent.com/31661648/49950644-d162fe80-febd-11e8-8346-de6b673c5a5f.png)

**Comment by pjaudiomv** [comment]
are you sure your using the proper twilio creds for that number, check that first.

**Comment by pjaudiomv** [comment]
that error indicates that the number your twilio creds arent valid from the number your trying to send FROM

**Comment by californiasteve** [comment]
Yep, my bad I had the wrong config file.

**Comment by pjaudiomv** [comment]
Yep no prob, ive done the same thing. that how i knew right away your issue ha
