### ISSUE TITLE
Edit Volunteers directly from the schedule page

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#218]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to edit volunteers directly from the schedule page.
That way you could see immediately that their schedule has gone where you need it to and you could immediately identify gaps.  

**Describe the solution you'd like**
Combine the Volunteer and Schedule page so you don't have to switch between screens the Volunteer and Schedule gui.  

**Describe alternatives you've considered**
Click on Volunteer A in the schedule page and go directly to his/her details.
Have an option to add a new volunteer off to the side or above the schedule.
Save the new volunteer an it switches back to the schedule page so you can see immediately where they've gone.

**Additional context**
Here's a mock up of what I mean.
![add volunteer](https://user-images.githubusercontent.com/29008815/49989785-13c43280-ffc7-11e8-9ebb-abf6be261a90.PNG)

**Comment by dgershman** [comment]
Not going to implement this.
