### ISSUE TITLE
Amazon Polly SSML integration.

### ISSUE THREAD

**Issue by rdtripp** [bmlt-enabled/yap#219]
I'm having issues with location mispronunciations.  Several text to voice services were tried and the Google Text to Speech worked much better than the others.  Can this be implemented in Yap?
A demo is at:
 https://cloud.google.com/text-to-speech/
The docs are at:
https://cloud.google.com/text-to-speech/docs/

**Comment by radius314** [comment]
ref: https://www.twilio.com/docs/voice/twiml/say/text-speech#ssml

**Comment by radius314** [comment]
Which voice are you using?

**Comment by radius314** [comment]
This has been released in 3.2.0
