### ISSUE TITLE
Can't See Service Bodies

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#220]
**Describe the bug**
When logged in with the credential that gives me access to all of services bodies on the server. I'm only seeing two in the schedule and volunteer tabs that I had set up before with a different login. I see all in the service bodies tab. We have 7 yap instances currently running.

**What version are you running**
2.5.1

**To Reproduce**
1. Login with a credential that has access to all service bodies on server.

**Expected behavior**
I should be able to see any Yap instance I have access to.

**Screenshots**

![image](https://user-images.githubusercontent.com/31661648/50044349-c3d98000-0047-11e9-8a98-f230ee6ef1f8.png)

![image](https://user-images.githubusercontent.com/31661648/50044359-dd7ac780-0047-11e9-8738-7d0413f1007e.png)

**Comment by pjaudiomv** [comment]
Only service bodies whos configuration setting for `Helpline Routing` is set to `Volunteers` or `Volunteers and SMS` will show up in the schedul eor as availabl,e to add volunteers

**Comment by pjaudiomv** [comment]
double check the other service bodies and that helpline routing is set to `Volunteers`

**Comment by californiasteve** [comment]
I have seven set up for helpline routing/sms and only see the two

**Comment by pjaudiomv** [comment]
so those 7 all look like this then?

![screen shot 2018-12-15 at 10 10 09 am](https://user-images.githubusercontent.com/34245618/50044459-a0b3ce00-0051-11e9-8891-cf5da5984df4.png)

**Comment by pjaudiomv** [comment]
what are the names of the 7 service bodies

**Comment by californiasteve** [comment]
I just figured it out. All of those instances are set up with a different login that gave me access to them. I need to change them to that service bodies BMLT credentials

**Comment by pjaudiomv** [comment]
all of the service bodies in that photo have volunteer routing disabled,  except Bayo and North Louisiana

**Comment by pjaudiomv** [comment]
cool

**Comment by radius314** [comment]
Did this answer your question?

**Comment by californiasteve** [comment]
Yes, I had the wrong credentials 




Steve Scranton 


210.279.9199







On Sat, Dec 15, 2018 at 1:31 PM -0600, "Danny Gershman" <notifications@github.com> wrote:












Did this answer your question?
