### ISSUE TITLE
error with reports page

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#226]
1.sql failed, had to run through cpanel to get it to work.

once i did that` and made some calls i started to see data populate in my mysql database. however im getting js errors accessing reports.

I used the latest build link from facebook

![screen shot 2018-12-25 at 7 12 53 pm](https://user-images.githubusercontent.com/34245618/50427563-9b3c5c00-0879-11e9-8bc2-9a24ec1c249e.png)

PHP 7.2
mysql 5.6
yap 3.0.0-beta1
siteground shared hosting

**Comment by radius314** [comment]
gonna rip out the custom function

**Comment by radius314** [comment]
fix is in master, you can use this build 
https://archives.bmlt.app/yap/yap-677-05c168c33e89ce91ef32acee63d6c34a1fde9d65.zip

**Comment by pjaudiomv** [comment]
im still getting same error

**Comment by pjaudiomv** [comment]
![screen shot 2018-12-26 at 10 12 47 pm](https://user-images.githubusercontent.com/34245618/50463744-6a345800-095b-11e9-83aa-d0d5b7ac1448.png)
![screen shot 2018-12-26 at 10 12 38 pm](https://user-images.githubusercontent.com/34245618/50463745-6a345800-095b-11e9-8f36-79b26383c22a.png)

**Comment by pjaudiomv** [comment]
![screen shot 2018-12-26 at 10 14 45 pm](https://user-images.githubusercontent.com/34245618/50463804-abc50300-095b-11e9-8bc6-e2fb662c9f6a.png)

**Comment by radius314** [comment]
This is a different error.  Has to do with the fact that you have no volunteer lookups happening yet.  Working on a fix for it.

**Comment by pjaudiomv** [comment]
ah yes cool, yea as soon as i made a volunteer call it worked. thanks.

**Comment by radius314** [comment]
fix pushed for the 2nd issue

**Comment by pjaudiomv** [comment]
cool just tested and confirmed that fixed it
