### ISSUE TITLE
incorrect MOH url gives error

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#228]
**Describe the bug**
When the MOH file has an incorrect url it throws a Twilio error code 13233

**What version are you running**
(3.0.0-beta1)

**To Reproduce**
Leave the extension or an incorrect folder in url in the MOH for service area

**Expected behavior**
Maybe have it default to another file or play nothing and continue with call.
Or better yet on save verify that url is correct.

**Comment by radius314** [comment]
What does "leave the extension" mean?

**Comment by radius314** [comment]
Had you experienced this in prior versions of yap?

**Comment by californiasteve** [comment]
Forgot to put "off". The last time I did this I left the .org off. The first time was last week when I didn't have the MOH file pointing at the correct location.

**Comment by pjaudiomv** [comment]
the easiest thing here would be to just check that the syntax of the url is valid, otherwise would probably have to do curl calls to check if urls don't 404 which would come at a higher cost.

**Comment by radius314** [comment]
Could probably do an HTTP validation step on save.

**Comment by californiasteve** [comment]
That would be good. I'm seeing a lot of the phoneline chairs really don't have computer skills beyond basic.

**Comment by radius314** [comment]
fixed in 3.0.2
