### ISSUE TITLE
JFT issue with text "H&I"

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#229]
**Describe the bug**
The JFT is not rendering today due to an ampersand in "H&I".

**What version are you running?**
2.5.1

**Did this happen on prior versions to the one you are running?**
Not sure

**To Reproduce**
1. Go to any fetch-jft.php page.
2. Page isn't rendering xml.

**Expected behavior**
Text should show.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pjaudiomv** [comment]
Cool should be easy enough maybe add htmlspecialchars to it

**Comment by radius314** [comment]
Couldn't repro.
