### ISSUE TITLE
Web results as an alternative to SMS

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#230]
**Is your feature request related to a problem? Please describe.**
Our costs are really creeping up. People are promoting the SMS search functionality offered by the new service and many people are switching to YAP SMS as their primary search mode.

**Describe the solution you'd like**
Send the results as a single SMS which returns a URL with the search results rather than multiple SMS.

**Describe alternatives you've considered**
It would also be great to have a similar search functionality built into BMLT.
EG A button on the default page which offers X (configurable) closest meetings within the next 24 hour period where people simply enter their town or postcode and don't have to search through the results for days ahead and behind.

**Mention any other of the Github handles that are also interested in this enhancement**
BMLT

**Additional context**
This would potentially reduce our SMS costs by 80% (instead of 5 SMS we are sending 1)

**Comment by radius314** [comment]
add the config.php option `static sms_summary_page = true;`

**Comment by radius314** [comment]
i had to make a slight display tweak for responsiveness use 2.5.3
https://github.com/bmlt-enabled/yap/archive/2.5.3.zip

**Comment by brustar64** [comment]
Thanks Danny that happened so quickly!, What do I need to change in the config file?  I've been looking through the readme but I can't see an option for the new feature.

**Comment by radius314** [comment]
Didn’t add it to the documentation.  Add

$static sms_summary_page = true;
