### ISSUE TITLE
Remove postcodes as a search option

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#231]
**Is your feature request related to a problem? Please describe.**
We have had unreliable search results in Australia for many years when searching by post code.
This has been exacerbated with the YAP option of sending postcodes and getting inaccurate results.
We worked with Chris M over the years to try to resolve this issues but we haven't really had a great deal of success.

**Describe the solution you'd like**
We would like to be able to switch off the Postcode option and just have the option of finding meetings by town or suburb (keep the option of asking for State or Territory first so places with the same name in multiple cities can be delineated) 

**Describe alternatives you've considered**
Perhaps this can be achieved within the config file already but I'm unsure of what options we would need to change.

**Comment by radius314** [comment]
Chris M has nothing to with Yap.  Which postal codes are having an issue?

**Comment by radius314** [comment]
There is no way to do this today.

**Comment by brustar64** [comment]
I've worked with Chris on the issues with Oz postcodes in BMLT.
I was hoping that at some stage this could be implemented.
I understand if we can't implement it straight away.  It would be really great to have this option added in a future release.
________________________________

**Comment by radius314** [comment]
Chris is not involved with the yap project, so I’m not sure what relevance
this has.

**Comment by brustar64** [comment]
Thanks Danny,

Some examples below
Postcodes which cause the webpage button issue are:

2008 (Darlington)
2009 (Pyrmont)
2016 (Redfern)
2028 (Double Bay)

Yap searches of these post codes send a single result from Broken hill over 1000klms away

Postcodes which return "no meeting" results but have meetings listed are:
2011 (this is inner city and should return lots of meetings from the surrounding suburbs)  (also returns Broken hill on a Yap search)


________________________________

**Comment by radius314** [comment]
https://github.com/bmlt-enabled/yap/archive/2.5.4.zip

**Comment by brustar64** [comment]
Thanks Danny,
Is set up and working well.
The initial prompt to search by state or suburb is now redundant but I won't trouble you with fixing that. 
I'll just have to update the script/intro so that it aligns with the revised inputs and outputs.

**Comment by radius314** [comment]
The assumption here is that someone could possibly have the JFT enabled and then if skipping the helpline routing it would not allow this option to be selected.  

This is opening up the door to some call flow complexities that I’m not prepared to tackle right now.
