### ISSUE TITLE
Ordering Multiple Volunteers Per Shift

### ISSUE THREAD

**Issue by awinter82** [bmlt-enabled/yap#233]
Hello. We used to use Onebox phone system which was a great layout for our helpline schedule. We were able to enter helpline volunteers just once into the database. The we could go into a calendar view of the week and enter per shift which volunteers were scheduled and the order in which they are scheduled (very important because we have people specifically requesting 1st, 2nd and 3rd shift orders). We didn't have to manipulate a main volunteer list based on their shift schedule or have to enter volunteers in multiple times to get the correct order.

Is this a possibility for YAP?

**Comment by radius314** [comment]
You can only sequence the master list.  There is no per shift order sequencing.

**Comment by radius314** [comment]
You can change the sequence by dragging and dropping the volunteers.

**Comment by awinter82** [comment]
Will this feature ever be available?

**Comment by radius314** [comment]
Do you have a screenshot from OneBox I can see?

**Comment by awinter82** [comment]
Not anymore, we discontinued their service to switch to grasshopper.

**Comment by radius314** [comment]
Nothing is impossible, it really comes down to the demand of a feature/usability and priority compared to other feature requests/bugs that have been sitting in the hopper for a while.

**Comment by radius314** [comment]
Have you installed Yap and played around with it yet?

**Comment by awinter82** [comment]
we basically have a sunday - monday schedule of midnight to 8am, 8am to noon, noon to 4pm, 4pm to 8pm, 8pm to midnight. I was able to enter a master list of volunteers and select one of the specific time slots and enter any amount of volunteers and change the order of which they are called.

**Comment by awinter82** [comment]
I had Mat S set it up for us and I logged in and started to play around with it. It seems similar to grasshopper when it comes to what I'm trying to do. For grasshopper I had to enter all of the volunteers with a "1" after their name for first shifts and then re enter them in with "2" for second shifts, etc.

**Comment by awinter82** [comment]
Mat wanted to make sure I told you that the AD from South Florida is an asshole

**Comment by radius314** [comment]
Time slots are set on the volunteers in which you can set any number of shifts times and days.  You can sequence the order in which they are called, but the ordering is not going to be unique per person per shift.

**Comment by awinter82** [comment]
Yeah, I understand that it's the same with Grasshopper. We have about 20 volunteers and we have 3 shifts per time slot so it gets very complicated to arrange and organize the shifts. Is it possible to add this feature to YAP at some point?

**Comment by radius314** [comment]
Potentially, it's a rather large change to implement.  It requires decoupling scheduling from volunteers.  There are a number of other "in-demand" features that have been waiting a while to implement, and this is the first time that this request has been placed.

**Comment by radius314** [comment]
similar related issues #218 and #115

**Comment by awinter82** [comment]
Alright, well in the meantime I will setup the volunteer list and schedule the same way I have it set up in the Grasshopper system. This way we can at least test out and play around with YAP. Is it possible to make my request into a formal request? Maybe at some point in the near future that option can be implemented?

**Comment by radius314** [comment]
This ticket serves as a formal request.

**Comment by awinter82** [comment]
Ok cool. Thank you very much!

**Comment by radius314** [comment]
Can you share some screenshots from Onebox so that I can see it for inspiration?

**Comment by dgershman** [comment]
Probably not going to implement this, since one person asked for it 4 years ago.
