### ISSUE TITLE
Twilio voice does not give out meeting location

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#235]
When we dial our Yap number and do a meeting search, meetings are returned correctly but only the group name and time are given out by the voice. The meeting location is missing. This occurs even with "static $include_location_text = true;" in config.php.

We are running Yap 3.0 beta 4

The problem did not occur on Yap 2.5.1. In this version the group name, time and meeting location are given out.

**Comment by radius314** [comment]
What was your search criteria?

**Comment by radius314** [comment]
Nvm, able to repro.

**Comment by Redguy1959** [comment]
Either way - voice recognition on "Aberdeen" or zip code input on 07747.

Twilio number 732-639-5482. Just tried again using "New Brunswick" as the search - same result, I get the group name and start time for 5 meetings but no location info.
  ----- Original Message -----

**Comment by radius314** [comment]
will be released in yap 3 beta 5

**Comment by radius314** [comment]
@Redguy1959 were you able to retest this?

**Comment by Redguy1959** [comment]
Haven't had a chance yet. This week sometime
  ----- Original Message -----

**Comment by radius314** [comment]
Ok sounds good, things are moving pretty fast now, so check to see you are using the latest beta.  https://github.com/bmlt-enabled/yap/releases

**Comment by radius314** [comment]
@californiasteve can you test this bug fix?

**Comment by californiasteve** [comment]
Works as expected, says Group name, time and location

**Comment by radius314** [comment]
Have you tried out the new setting as well?

**Comment by radius314** [comment]
@californiasteve have tried with `static $include_location_text = true;`

**Comment by californiasteve** [comment]
It's not saying the location, ie "First Baptist Church"

**Comment by californiasteve** [comment]
I did it in the admin, haven't tried to code in the config.php file

**Comment by radius314** [comment]
How did you force yap to use the setting in the admin?

**Comment by californiasteve** [comment]
![image](https://user-images.githubusercontent.com/31661648/54078371-7b1f1500-428c-11e9-88e0-970b69addd28.png)

**Comment by radius314** [comment]
Yap does not know to use those setting automatically unless you tell it to.  You will need to set on your webhook `override_service_body_id=x`, where x is the ID of the service body.

**Comment by radius314** [comment]
At this point in the callow Yap doesn't know what area to use in it's config.

**Comment by californiasteve** [comment]
It's working as expected, saying meeting location.

**Comment by radius314** [comment]
thanks
