### ISSUE TITLE
Alphabetically List Service Bodies in Service Bodies Tab

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#236]
Make Service Bodies list alphabetically in "Service Bodies" tab.

![image](https://user-images.githubusercontent.com/31661648/53673404-e3e30d80-3c4c-11e9-9d1c-d986f1ca032c.png)

**Comment by radius314** [comment]
will be fixed in yap 3

**Comment by californiasteve** [comment]
Beta 5.1
Service bodies and Volunteers are sorted but Schedules are not.
![image](https://user-images.githubusercontent.com/31661648/53813922-4cb7d780-3f24-11e9-8142-626a47692878.png)

**Comment by radius314** [comment]
fixed in 3.0.0-beta5.2

**Comment by radius314** [comment]
@californiasteve were you able test this?

**Comment by californiasteve** [comment]
Yes, works as expected
