### ISSUE TITLE
3.0 Beta 5 SMS fail

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#237]
Fresh install 3.0 Beta 5,
Error occurs at sms send with both voice and text
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <br />
    <b>Fatal error</b>:  Uncaught Error: Call to a member function create() on null in /home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php:31
Stack trace:
#0 /home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php(94): sendSms('A New Way Monda...')
#1 {main}
  thrown in 
    <b>/home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php</b> on line 
    <b>31</b>
    <br />
Voice Error,
<Say voice="woman" language="en">starts at Monday 1:30 PM</Say>
    <Pause length="1"/>
    <Say voice="woman" language="en">127 McCullough San Antonio, Texas</Say>
    <Pause length="1"/>
    <Say voice="woman" language="en">number 5</Say>
    <Say voice="woman" language="en">Lifeguard</Say>
    <Pause length="1"/>
    <Say voice="woman" language="en">starts at Monday 8:00 PM</Say>
    <Pause length="1"/>
    <Say voice="woman" language="en">6800 Wurzbach Rd San Antonio, Texas</Say>
    <br />
    <b>Fatal error</b>:  Uncaught Error: Call to a member function create() on null in /home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php:31
Stack trace:
#0 /home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php(94): sendSms('A New Way Monda...')
#1 {main}
  thrown in 
    <b>/home/eanaonli/public_html/bmltyap/test/endpoints/meeting-search.php</b> on line 
    <b>31</b>
    <br />

**Comment by californiasteve** [comment]
I see what's up. the meeting-results.php file is calling the functions.php which I'm not seeing in the endpoints folder.

**Comment by radius314** [comment]
That’s true, but the error isn’t from that file.

**Comment by radius314** [comment]
fixed in 3.0.0-beta5.2

**Comment by radius314** [comment]
related to #241
