### ISSUE TITLE
sms_summary_page not respecting sms_ask option

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#238]
**Describe the bug**
when using the $sms_summary_page = true option it overrides overrides $sms_ask = true. and is sent regardless. It would make sense for the sms summary to respect the sms_ask option.

**Comment by tempsaint** [comment]
Thank you. I was just about to add this.

**Comment by radius314** [comment]
Are you asking for the settings to be mutually exclusive?

**Comment by pjaudiomv** [comment]
Yes so the idea being if you wanted to use both of these settings you can. Where it asks you if you want sms and can send summary page

**Comment by radius314** [comment]
Ok, thanks for clarifying.

**Comment by radius314** [comment]
will be released with yap 3.0.0

**Comment by radius314** [comment]
testable here: 
https://archives.bmlt.app/yap/yap-840-0addc7d2687cc3eec4bf08c06640badcc6e9cd17.zip
