### ISSUE TITLE
groups not adding

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#239]
when trying to add a group, I get a endless "Saving Group..." spinner of death. I tried adding a group and not assigning it to a service body, as well as adding one with adding it to service body. I get the following error in my javascript console. 

TypeError: xhr.responseJSON is undefined. yap.js:695:25

`var new_group_id = xhr.responseJSON['id'];`

after refreshing the page and trying again my console gives me these two errors

Source map error: request failed with status 404
Resource URL: https://phoneline.nerna.org/yap3/admin/js/popper.min.js
Source Map URL: popper.min.js.map

and 

Source map error: request failed with status 404
Resource URL: https://phoneline.nerna.org/yap3/admin/js/bootstrap-4.1.0.min.js
Source Map URL: bootstrap.min.js.map

Im using latest version of FireFox on mac os high sierra

**Comment by radius314** [comment]
What are you pressing to add a group?  Include group or manage groups?

**Comment by pjaudiomv** [comment]
I think I did manage groups, not at computer to double check

**Comment by californiasteve** [comment]
I get the same spinner after going to volunteers, manage groups, then the add button.

**Comment by radius314** [comment]
fixed in 3.0.0-beta5.2

**Comment by pjaudiomv** [comment]
cool this works fine now.

**Comment by radius314** [comment]
thanks for testing.
