### ISSUE TITLE
3.0 beta 5.3 install error

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#240]
Clean install with an empty database. Tables were created in db. I get these errors. 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data - from upgrade-advisor
This when I attempt to login.
Warning: require_once(/home/eanaonli/public_html/bmltyap/test/endpoints/_includes/../../vendor/autoload.php): failed to open stream: No such file or directory in /home/eanaonli/public_html/bmltyap/test/endpoints/_includes/twilio-client.php on line 2

Fatal error: require_once(): Failed opening required '/home/eanaonli/public_html/bmltyap/test/endpoints/_includes/../../vendor/autoload.php' (include_path='.:/usr/local/php70/pear') in /home/eanaonli/public_html/bmltyap/test/endpoints/_includes/twilio-client.php on line 2

**Comment by radius314** [comment]
could not reproduce.

**Comment by californiasteve** [comment]
I will try it again

**Comment by californiasteve** [comment]
All good, reinstalled. May have had cookie file still in the directory.

**Comment by radius314** [comment]
This would happen if you cloned from GitHub rather than using the build process.  Dependencies are no longer checked into source control and are generated for each build artifact.
