### ISSUE TITLE
Yap 3 beta 5.4 - Ignores $postal_code_length overide and doesn't offer "say" option at for postcode

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#242]
**Describe the bug**
static $postal_code_length = 4; is configured however 5.4 beta asks callers to enter a 5 digit code
It also just says "enter your 5 digit postcode" instead of "Please enter or say your 5 digit postcode"

**What version are you running?**
3 Beta 5.4

**Did this happen on prior versions to the one you are running?**
New to 5.4 - Ideally we would like to be able to switch off the request postcode option and just have people enter or say their state or territory and town or suburb as we are getting very sketchy results.

**To Reproduce**
1. Call the newly configured number
2. press or say 2 to search for meetings
3. Polly asks user to enter a 5 digit postcode
4. Enter a 4 digit postcode and correct results are displayed

**Expected behavior**
Override should request a 4 digit postcode
Option to remove asking for postcode at all is desireable as our search results are proving to be more accurate when enter the state/territory and town or suburb

**Comment by radius314** [comment]
Switching off postal code gathering is a new feature.  Please open a separate ticket for that.

**Comment by radius314** [comment]
Just to clarify `static $postal_code_length = 4` does not control the prompts.  It merely tells the gathering to stop after 4 digits are entered.

**Comment by radius314** [comment]
Able to repro, working on a fix now.

**Comment by brustar64** [comment]
But this does right - $override_please_enter_your_digit = "please enter your four digit";

**Comment by radius314** [comment]
Only if you are disabling speech gathering (static $speech_gathering = false).   Otherwise use `static $override_please_enter_or_say_your_digit = "please enter or say your four digit";`

**Comment by radius314** [comment]
did this work for you?

**Comment by brustar64** [comment]
adding  static $override_please_enter_or_say_your_digit = "please enter or say your four digit" fixes the 5 digit question

static $speech_gathering = false causes the application to fail
________________________________

**Comment by radius314** [comment]
please provide more information about the failure.

**Comment by brustar64** [comment]
Apologies I forgot the ; after the static line - sytax error
