### ISSUE TITLE
Turn off the question for postcode search options

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#243]
**Is your feature request related to a problem?**
Australian postcodes are buggy when searching the BMLT
Hours have been spent trying to work this bug out.
We have found that searching by state/territory and city/suburb produces much more consistent results.
We would just like to remove the prompt to ask for postcodes. 
 

**Describe the solution you'd like**
Just ask for state/territory and town/suburb 
We would still like postcodes to work as many people still like to send a postcode to the SMS number to get a list of meetings in the next 24 hours.

**Describe alternatives you've considered**
Fix the Australian Postcode issue.

**Comment by radius314** [comment]
will be slated for a future release

**Comment by radius314** [comment]
This feature was already completed some time ago.  Set `static $disable_postal_code_gather = true;`

**Comment by radius314** [comment]
ref: #231 

https://yap.bmlt.app/docs/meeting-search/disabling-postal-code-gathering/
