### ISSUE TITLE
Feature Request - Configure initial pause

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#244]
Add a feature to control the initial pause length.

**Comment by radius314** [comment]
The pause lengths have not changed.

**Comment by radius314** [comment]
There is a 2 second pause that occurs before the prompt is played.

**Comment by brustar64** [comment]
Can we test removing the pause? Or shortening it to half a second?

**Comment by radius314** [comment]
I am not going to add any new features to this release.

**Comment by radius314** [comment]
This code has not changed since July 2018.  https://github.com/bmlt-enabled/yap/commit/761a43e9498516ba47316e9ca85b9555ee86d668

**Comment by brustar64** [comment]
Do you want me to close this and add a feature request for a later release?  Or can this be converted from a bug to a feature request?

**Comment by radius314** [comment]
The feature request should read as, being able to control the initial pause length.

**Comment by radius314** [comment]
You can edit the ticket description if you'd like.

**Comment by radius314** [comment]
fixed in 3.0.2
