### ISSUE TITLE
YAP 3 Beta - Not routing to Volunteers

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#245]
**Describe the bug**
tested volunteer routing in Yap but its just going straight to voicemail.
I thought maybe its because I hadn't filled in some of the extra fields (Gender, Responder) but I added them and its still just going straight to voicemail. 

**What version are you running?**
(3.0.0-beta5.4)

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
1. Call the test number
2. Press 1 to find someone to talk to
3. Press 2 to find someone by postcode
4. Enter postcode for the configured Service body. (Polly advises that she's connecting my call and the on hold music starts.
5. Goes to voicemail about 3 seconds later

**Expected behavior**
Calls route to volunteers who are rostered on.

**Comment by radius314** [comment]
bump to beta5.5, there was a bug that would've hit you in 5.4
