### ISSUE TITLE
SMS to volunteer no longer includes incoming call number

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#247]
**Describe the bug**
A message is passed to volunteers when selected in the "Call handling" config however it no longer includes the caller's number so they are unable to be called back if the volunteer misses a call.

**What version are you running?**
Beta 3 v 5.5

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
1. Call and ask to speak to someone
2. Route to volunteers
3. Volunteer call comes through and so does SMS however the SMS no longer includes the callers number.

**Expected behavior**
We would like to include the caller's number as this is a valuable feature that allows us to call back if a call is missed.  

**Additional context**
Not sure if this is slated for a future release or not but I did previously put in a feature request to be able to send voicemail to the rostered on volunteer/s.

**Comment by brustar64** [comment]
i just read the release notes nad now understand the "responder" option which sends a voicemail to the volunteer as well.  Testing this now.

**Comment by brustar64** [comment]
Unable to get voicemail to send to Volunteers...

**Comment by radius314** [comment]
Please do not conflate issues.  #211 is still open, so please add those comments there about that specific issue.

**Comment by radius314** [comment]
patched in beta6.1

**Comment by brustar64** [comment]
tested and working - thank you!

**Comment by radius314** [comment]
Cool, thanks!
