### ISSUE TITLE
Missing meetings for Northeast Alabama Area

### ISSUE THREAD

**Issue by Navykel** [bmlt-enabled/yap#248]
**Describe the bug**
BMLT listst meetings in Jackson AL 35771 but when we call our helpline is gives a different zipcode for Jackson AL than what is listed. In addition if you input 35771 it will not list Section Serenity group. 

**What version are you running?**
2.5.x

**Did this happen on prior versions to the one you are running?**
Uknown
**To Reproduce**
1. Call XXX-XXX-XXXX
2. option 2, option one "Jackson AL" (returns a different zipcode that what is in bmlt)
3. option 2, option two "35771" meeting information for Wednesday Section Serenity group doesn't come up.  

**Expected behavior**
Meeting should show up. 

**Screenshots**
![No Section Serenity Group](https://user-images.githubusercontent.com/48535627/54320287-69a27980-45ba-11e9-8123-c65199d07691.jpg)

**Additional context**

**Comment by Navykel** [comment]
Section is the town. When I say "Section Alabama" it returns the correct Zipcode but again, no listing for the Section Serenity group.

**Comment by radius314** [comment]
What do you mean it returns the incorrect zip code?

**Comment by Navykel** [comment]
I was saying "Jackson" thinking it was the city. It was the county. So, when I said Jackson, I was getting a zipcode for a Jackson Alabama?

**Comment by radius314** [comment]
Is it returning 36545?

**Comment by radius314** [comment]
@jbraswell for your awareness.

**Comment by radius314** [comment]
Google Maps API returns 35771 as "Section, AL"

**Comment by Navykel** [comment]
Yep, and it looks correct in BMLT right? (screen shot)

**Comment by Navykel** [comment]
![Section AL](https://user-images.githubusercontent.com/48535627/54321073-7b395080-45bd-11e9-9c1a-48c3189a37eb.jpg)

**Comment by radius314** [comment]
The coordinates in that record seem off, a quick search in Google Maps returns a result west of Montgomery, AL.  https://www.google.com/maps/place/32°19'05.6%22N+86°54'08.3%22W/@32.2190354,-87.189033,9.26z/data=!4m5!3m4!1s0x0:0x0!8m2!3d32.3182314!4d-86.902298

**Comment by Navykel** [comment]
Delete the coordinates?

**Comment by radius314** [comment]
Follow up the BMLT administrator to see what's going on.
