### ISSUE TITLE
Plus (+) previously added to voicemail message to allow click to dial requires modification

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#249]
**Describe the bug**
Related to Issue #137 
Message currently looks like this:
"You have a message from the X Area helpline from caller  61488xxxxx+ 614880xxxxx, https://twilio voicemail link"

Volunteers have to click the second number and its a bit clunky and confusing for them.
**What version are you running?**
Beta 3 v6.1

**Did this happen on prior versions to the one you are running?**
Yes
**To Reproduce**
Leave a voicemail message 
View the SMS

**Expected behavior**
Ideally the change would append a leading + to the number posted by Twilio to look like this:

"You have a message from the X Area helpline from caller  +61488xxxxx, https://twilio voicemail link"

**Screenshots**
![Screenshot_20190315-082805_Messages](https://user-images.githubusercontent.com/29008815/54395846-b4c4a580-46fc-11e9-8b93-afc5d3342380.jpg)

**Additional context**
As we are rolling out voicemail to volunteers it would be better to have this feature looking 100%

**Comment by radius314** [comment]
This is patched in 
https://github.com/bmlt-enabled/yap/releases/download/3.0.0-beta6.2/yap-3.0.0-beta6.2.zip

**Comment by radius314** [comment]
@brustar64 can you test?

**Comment by brustar64** [comment]
Fixed - thanks very much! :)
