### ISSUE TITLE
Language selection support for Australia English

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#253]
Australian English needs help, as it's not going to fit into an English US translation model.

**Comment by radius314** [comment]
@brustar64, this is going to be handled simply by adding a separate language file for Australian English.

**Comment by brustar64** [comment]
Thanks Danny,

Do you need me to do the translation for that?
Is it the same template that I used for the Farsi one?

regards,
Bruce
________________________________

**Comment by radius314** [comment]
I took care of it.  Nothing to do on your end for this.

**Comment by radius314** [comment]
fixed in 3.0.2
