### ISSUE TITLE
No map link on SMS

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#254]
**Describe the bug**
No map link on SMS 
Yet map link is configured in config - static $include_map_link = true;
**What version are you running?**
Yap (3.0.0-beta7.1)

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
sms twilio number for search results.
results are posted but without links

**Expected behavior**
Expect a link

**Comment by brustar64** [comment]
Did this get fixed in 3.01?

**Comment by radius314** [comment]
It has not been released yet.
