### ISSUE TITLE
"An application error has occurred" when requesting text message at the end of meeting listing

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#258]
Dialed in, requested meeting info by zip code 07747. Five meetings were correctly spoken to me, I was given the option to press 1 to have a text message sent. I press 1 and get "we're sorry, an application error has occurred". Tried again with 07724, same thing.

**Comment by radius314** [comment]
Not enough information to proceed.  Need error logs from your server emailed to help<at>bmlt<dot>app.  Please also email a full listing of the error from Twilio.  In the future always include enough information that someone who was not familiar with your configuration could make sense of the ticket.

**Comment by Redguy1959** [comment]
Please provide a full email address for emailing the logs.
  ----- Original Message -----

**Comment by radius314** [comment]
help@bmlt.app, please include the application name and the ticket number as reference in the subject.

**Comment by radius314** [comment]
@Redguy1959 we have not received any additional details from you.

**Comment by Redguy1959** [comment]
Leave the ticket open. You will eventually be given the info.
  ----- Original Message -----

**Comment by radius314** [comment]
please upgrade to the latest version of yap 3.0.2 and test again

**Comment by radius314** [comment]
able to repro on the version of yap you are on?

**Comment by radius314** [comment]
Closing this, many versions have been released since.  Please re-open if it's still occurring on the latest version.

**Comment by Redguy1959** [comment]
We haven’t touched it in a while. Will install the latest version.
