### ISSUE TITLE
No volunteer routing

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#259]
I call in and select to speak to someone, choose zip code, then put in a zip code in Central Jersey Area. I have two Volunteers in the database - one in New Jersey Region and one in Central Jersey Area. Both service bodies are set for Volunteer routing. Both volunteers are set for 24/7 shifts. I have access to the destination phone numbers on phones sitting in front of me. Call puts me on hold forever.

**Comment by radius314** [comment]
Not enough information to proceed.

**Comment by radius314** [comment]
what's the yap url?

**Comment by Redguy1959** [comment]
https://mail.freedomweb.net:442/yap
  ----- Original Message -----

**Comment by radius314** [comment]
Seems configured correctly.  Need to see the Twilio logs for that specific all to see what happened.

**Comment by Redguy1959** [comment]
OK, just got back to this. Upgraded to 3.1.0 (earlier versions didn;t route to volunteers, other features worked). Twilio shows my server throwing 500 errors, which I can confirm. Will look at the server logs and see if anything obvious.
  ----- Original Message -----

**Comment by radius314** [comment]
Yes please share the log details to admin-at-bmlt-dot-app

**Comment by radius314** [comment]
Reference "yap issue #259"

**Comment by radius314** [comment]
@Redguy1959 anything on those logs?

**Comment by Redguy1959** [comment]
Please remove me from the reminder app.
  ----- Original Message -----

**Comment by radius314** [comment]
Reminder app?

**Comment by Redguy1959** [comment]
Yes, somehow I just got an email asking for logs.
  ----- Original Message -----

**Comment by radius314** [comment]
That was me following up on this issue.  Not an app.

**Comment by radius314** [comment]
```Fatal error: Uncaught Twilio\Exceptions\RestException: [HTTP 500] Unable to fetch page: An internal server error has occurred in C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Page.php:54 Stack trace: #0 C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Page.php(34): Twilio\Page->processResponse(Object(Twilio\Http\Response)) #1 C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Rest\Api\V2010\Account\ConferencePage.php(16): Twilio\Page->__construct(Object(Twilio\Rest\Api\V2010), Object(Twilio\Http\Response)) #2 C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Rest\Api\V2010\Account\ConferenceList.php(114): Twilio\Rest\Api\V2010\Account\ConferencePage->__construct(Object(Twilio\Rest\Api\V2010), Object(Twilio\Http\Response), Array) #3 C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Rest\Api\V2010\Account\ConferenceList.php(57): Twilio\Rest\Api\V2010\Account\ConferenceList->page(Object(Twilio\Values), 'Twilio\\Values\\N...') #4 C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Rest\Ap in C:\inetpub\wwwroot-nanj-nt\yap\vendor\twilio\sdk\Twilio\Page.php on line 54```

**Comment by radius314** [comment]
If you are trying to call the webhook directly it won't work for a non-active call.  No one is scheduled during this time shift.  You can however, view what would happen in the event of an actual call.

https://mail.freedomweb.net:442/yap/helpline-dialer.php?service_body_id=17&Caller=+17326395482&ysk=j8l8mkbquo86n44rms8n8aqvk6&Debug=1&FriendlyName=123

object(app\bmltenabled\yap\CallConfig)#35 (4) { ["voicemail_url"]=> string(121) "https://mail.freedomweb.net:442/yap/voicemail.php?service_body_id=17&caller_id=17326395482&ysk=j8l8mkbquo86n44rms8n8aqvk6" ["volunteer_routing_params"]=> object(VolunteerRoutingParameters)#36 (8) { ["service_body_id"]=> string(2) "17" ["tracker"]=> int(0) ["cycle_algorithm"]=> int(0) ["volunteer_type"]=> string(5) "PHONE" ["volunteer_gender"]=> int(0) ["volunteer_shadow"]=> int(0) ["volunteer_responder"]=> int(0) ["volunteer_language"]=> int(0) } ["options"]=> array(7) { ["url"]=> string(135) "https://mail.freedomweb.net:442/yap/helpline-outdial-response.php?conference_name=123&service_body_id=17&ysk=j8l8mkbquo86n44rms8n8aqvk6" ["statusCallback"]=> string(161) "https://mail.freedomweb.net:442/yap/helpline-dialer.php?service_body_id=17&tracker=1&FriendlyName=123&OriginalCallerId=17326395482&ysk=j8l8mkbquo86n44rms8n8aqvk6" ["statusCallbackEvent"]=> string(9) "completed" ["statusCallbackMethod"]=> string(3) "GET" ["timeout"]=> int(20) ["callerId"]=> string(12) " 17326395482" ["originalCallerId"]=> string(12) " 17326395482" } ["volunteer"]=> object(Volunteer)#33 (2) { ["phoneNumber"]=> string(10) "0000000000" ["volunteerInfo"]=> NULL } }

**Comment by radius314** [comment]
No one is enabled https://mail.freedomweb.net:442/yap/helpline-schedule.php?service_body_id=x

**Comment by Redguy1959** [comment]
Thanks. I enabled a volunteer in Central Jersey Area: https://mail.freedomweb.net:442/yap/helpline-schedule.php?service_body_id=17

I can see from the Report tab in Yap now that my test call is being directed to Central Jersey Area.

Phone still doesn’t ring (it’s my cell) and Twilio shows no error.

I am glad the 500 error is gone. What is next step to diagnose?

**Comment by radius314** [comment]
1) Do you see an outgoing API call in the call log in Twilio?
2) Are there any other errors that are coming up in your server logs (Twilio wouldn't necessarily be aware of them).
3) Are you hearing on music on hold on the calling end?

**Comment by radius314** [comment]
Closing this ticket, please re-open if it's still happening.
