### ISSUE TITLE
To add option to specify different Polly settings for each language.

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#260]
To enhance user experience with different languages specified.

**Comment by radius314** [comment]
@californiasteve available for testing here https://archives.bmlt.app/yap/yap-892-cc6e3ecc420e225b17756538c4ae901a613f37a1.zip

**Comment by radius314** [comment]
@californiasteve have you been able to test this?

**Comment by radius314** [comment]
https://yap.bmlt.app/docs/general/language-options/, see the bottom of the page

**Comment by californiasteve** [comment]
I can test it in the am




Steve Scranton 


210.279.9199







On Sun, Apr 14, 2019 at 2:50 PM -0500, "Danny Gershman" <notifications@github.com> wrote:












@californiasteve available for testing here https://archives.bmlt.app/yap/yap-892-cc6e3ecc420e225b17756538c4ae901a613f37a1.zip

**Comment by californiasteve** [comment]
Works as expected. I'm wondering if we could use the spanish voice for the second part on the "press or say  1 for english, or presione o diga dos por espanol"? Right now the accent is pretty english, lol

**Comment by radius314** [comment]
It should do that already.  You need to specify voices for both languages,
so your config should look something like.

en_US_voice = "Polly.Kendra"
es_US_voice = "Polly.Penelope"
language_selections "en-US,es-US"

--Danny

**Comment by radius314** [comment]
Ignore my syntax errors, you get the point hopefully.

**Comment by californiasteve** [comment]
Got it, testing now.

**Comment by radius314** [comment]
How did this work out ?

**Comment by californiasteve** [comment]
It works as expected once you pick a language. The first part where it asks to pick a language the Spanish prompt is still in the English voice and makes it hard to understand.

**Comment by radius314** [comment]
Can you bump up to the latest build, it looks like you might be on a version prior to this change being implemented.  Use the latest build 899 https://archives.bmlt.app/index.html#yap/

**Comment by californiasteve** [comment]
Works as expected with language-specific voices. I'll have Johnny L. test it here in a few.

**Comment by californiasteve** [comment]
Johnny says "totally clear now"

**Comment by radius314** [comment]
Excellent, thanks for your help.

**Comment by radius314** [comment]
released in yap 3.1.0
