### ISSUE TITLE
The word "today" is not translated

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#261]
https://github.com/bmlt-enabled/yap/blob/803df8412ab0c56dd4909578392a7d26131454be/endpoints/address-lookup.php#L17

**Comment by jbraswell** [comment]
The spanish translation is `hoy`

**Comment by radius314** [comment]
looks like I may have started implementing a feature (for day selection) and never completed.

**Comment by radius314** [comment]
fixed in 3.0.2
