### ISSUE TITLE
es-US translation fixes

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#262]
`$to_find = "encontrar";` should be `$to_find = "para encontrar";`

`$please_enter_your_digit = "por favor, ingrese su dígito";` should be `$please_enter_your_digit = "por favor, ingrese su cinco dígito";`

`$please_enter_or_say_your_digit = "por favor, ingrese o diga su dígito";` should be `$please_enter_or_say_your_digit = "por favor, ingrese o diga su cinco dígito";`

I will update this issue with more corrections as Charlie finds them.

**Comment by radius314** [comment]
could you open a pull request for this rather than opening tickets?

**Comment by jbraswell** [comment]
I am happy to open a pull request, but not right now. This issue is so that I know what to fix when I'm able to do that.

**Comment by radius314** [comment]
released in yap 3.1.0
