### ISSUE TITLE
Prompts not working from service body config

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#268]
**Describe the bug**
If you set custom mp3s on service body config (not call handling), they will not be utilized.

**What version are you running?**
3.0.3

**Did this happen on prior versions to the one you are running?**
yes

Set a custom mp3, and then use `override_service_body_config_id` on your web hook for that service body.  Notice that the setting won't be pulled.

**Comment by radius314** [comment]
@reallango you should be able to test this with this https://archives.bmlt.app/yap/yap-882-9e8f95bcd540b98824f1f2cdc8f2c8c9e9c59fa9.zip

**Comment by radius314** [comment]
Will be in Yap 3.1.0

**Comment by radius314** [comment]
@reallango find any other issues with this?

**Comment by reallango** [comment]
Nope the features I've tried all appear to be working now.

**Comment by radius314** [comment]
Thanks.
