### ISSUE TITLE
Shift start time should be before end time. warning.

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#269]
**Describe the bug**
The 'Shift start time should be before end time.' doesn't clear once this happens. I can go and add a new volunteer and the warning is still there even though I haven't entered anything yet. This doesnt clear till page is refreshed.

**To Reproduce**
Edit or add volunteer, add time say 7pm -1am, warning will pop up. change time save. now either add another day for that volunteer or add new volunteer and warning is still there.

**Expected behavior**
The warning message should clear if problem that caused that warning is corrected or very least you change schedule day or volunteer.

on latest yap version 3.0.3

**Comment by radius314** [comment]
it's available in master and will be in yap 3.1.0

**Comment by radius314** [comment]
@pjaudiomv available for testing https://archives.bmlt.app/yap/yap-892-cc6e3ecc420e225b17756538c4ae901a613f37a1.zip

**Comment by radius314** [comment]
@pjaudiomv can you test this?

**Comment by pjaudiomv** [comment]
Yea I'll test tonight

**Comment by pjaudiomv** [comment]
this works great however I would make it 5000 instead of 2000. 2000 wasnt enough time to read message and with 5000 you could read it and even with fastest work flow the message would be gone.

**Comment by radius314** [comment]
pr it
