### ISSUE TITLE
Allow Volunteer to send a text to caller once call is completed

### ISSUE THREAD

**Issue by reallango** [bmlt-enabled/yap#272]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to tell a caller what are website address is. it typically requires me to repeat the address several times before they get it right. I typically end up texting them the link from my personal number.

**Describe the solution you'd like**
A method to allow volunteers to send a text to a caller after the call is complete.
one option would be after a call is completed the volunteer could get a texted with a case # 
The volunteer could then respond to the text with the case # and link. This would text the caller the website link configured for the service body.
Ex. Volunteer would respond with "4568 link" and the caller would receive a text with the programmed link URL

**Describe alternatives you've considered**
Alternative would be to not have the programmed link but instead just add a method of responding to the caller with a text like in the example below.

**Mention any other of the Github handles that are also interested in this enhancement**

**Additional context**
This method could also work for opening up other post call options.
Method could be used for enhancement #270 
Ex. Volunteer would respond with "4568 note this caller was a sales rep from cable provider" This would then add the note to the call record "this caller was a sales rep from cable provider"

Ex. Volunteer responds "4568 call" and this could have the system call the Volunteer and when they answer attempt to call the caller back.

Ex. Volunteer responds "4568 text Serenity group is having a celebration tonight" Which would send text to the caller "Serenity group is having a celebration tonight"

**Comment by radius314** [comment]
The feature request in #308 might be related to this.

**Comment by dgershman** [comment]
Not going to implement.
