### ISSUE TITLE
JFT parse error on Spanish 

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#273]
Version 3.1.0
When you select a language other than English and have the JFT option enabled you get an error.

Call 210 880 3434 select 2 for Spanish the 3 for the JFT

Should default to English or say text "JFT is not available in this language"

**Comment by californiasteve** [comment]
![image](https://user-images.githubusercontent.com/31661648/56378907-07015680-61d4-11e9-8e7c-0e17587be488.png)

**Comment by radius314** [comment]
Are you sure that it's happening for all languages?  This error indicates a parsing issue, not that the JFT doesn't exist (because it clearly does).  Basically the description of the bug doesn't appear to be indicative of the actual error.

**Comment by californiasteve** [comment]
My bad, I saw this when I posted it and then got pulled into something else. I agree with you it just didn't parse correctly.

**Comment by radius314** [comment]
Here's the parse error https://bmltyap.org/test/fetch-jft.php?language=es-US&word_language=es-US

**Comment by radius314** [comment]
testable https://archives.bmlt.app/yap/yap-902-d06b771d8a4def20c0cbe0264d5d797659fb2e8d.zip

**Comment by californiasteve** [comment]
Works as expected.

**Comment by radius314** [comment]
will be released in yap 3.1.1
