### ISSUE TITLE
PHP Notice:  Undefined index: delete 

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#276]
[Mon Apr 22 23:17:21.951951 2019] [php7:notice] [pid 24971] [client 68.42.63.54:64217] PHP Notice:  Undefined index: delete in /var/www/bmlt/zonal-yap/endpoints/_includes/functions.php on line 493, referer: https://bmlt.sezf.org/zonal-yap/admin/groups.php

Not high priority - just noticed this in the logs for Yap 3.1.0.

**Comment by pjaudiomv** [comment]
im guessing the word hadnt been added yet because there is no delete function yet.

**Comment by radius314** [comment]
will be in 3.1.1
