### ISSUE TITLE
JFT Option not disabling JFT text or voice option

### ISSUE THREAD

**Issue by spiritualtheory** [bmlt-enabled/yap#287]
**Describe the bug**
the jft_option only turns off the voice prompt for saying the JFT, but the JFT text or voice option 3 still retrieve the JFT (no condition checked against jft_option)

**What version are you running?**
2.5.1

**To reproduce**
set jft_option to false (it is false by default) and text JFT or call in and press 3 without the prompt

**Comment by radius314** [comment]
The same issue in on 3.3.1

**Comment by radius314** [comment]
The fix for this is the latest build and will be pushed in Yap 2.4.0
