### ISSUE TITLE
No catch for invalid number/option on phone call

### ISSUE THREAD

**Issue by spiritualtheory** [bmlt-enabled/yap#288]
**Describe the bug**
When you call and press a number other than 1 (meeting search), 2 (talk to someone), or 3 (jft), it just says that is an invalid option and ends the call

**What version are you running?**
2.5.1

**To Reproduce**
Call and press anything other than 1, 2, or 3

**Comment by radius314** [comment]
The same issue in on 3.3.1

**Comment by radius314** [comment]
This issue is fixed with the changes made in #292 and will be released in Yap 2.4.0
