### ISSUE TITLE
Pagination for call records

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#289]
as call records grow it would be nice to have some sort of pagination.

**Comment by brustar64** [comment]
Agreed, this is what our region is calling for in terms of reporting.
Being able to filter month by month as well.
If perhaps an export to csv could be enabled we could filter and graph ourselves..

**Comment by radius314** [comment]
In order for this to be actually sustainable, the call records stuff needs to be re-worked.  Currently we are hitting the Twilio API for the records which is very slow.  It also lacks certain contextual information which is specific to Yap.

The best way to handle this is to store all call records in the database and then adding things like date filtering and CSV exports becomes simplified immensely.

I would suggest creating a data migration mechanism that would pull all the current call records back into these new tables and then completely disconnect the existing methodology.

**Comment by brustar64** [comment]
As long as there is is some kind of purge functionality for old records to manage database growth that sounds like an excellent approach

Regards
Bruce

________________________________

**Comment by radius314** [comment]
Pagination is available in the new reporting features in Yap 3.5.0

**Comment by brustar64** [comment]
Thanks Danny, l will install it on my own server to test and provide feedback.
________________________________

**Comment by radius314** [comment]
will be in yap 3.5.0 (there is another step to this which is to paginate the endpoints), will push to a future release in #338
