### ISSUE TITLE
Ability set default state or Region independent of phone Number area code

### ISSUE THREAD

**Issue by rdtripp** [bmlt-enabled/yap#291]
I found a really cool phone number 585-dont-use and I'd like to use it for Louisiana Region.  
Currently yap defaults to the location of the area code of the phone number (in this case 585, New York) for the "Search by city or county".  I would like to override that in config.php

**Comment by radius314** [comment]
Please test this feature here: https://archives.bmlt.app/yap/yap-972-e44bde10f637e0f43274c4624327ce5bcb37790c.zip

Here is the documentation on the new feature: https://github.com/bmlt-enabled/yap/wiki/Province-Bias

Add `$static toll_province_bias = "LA";` to your config.php

**Comment by rdtripp** [comment]
Works perfectly.  Thanks
