### ISSUE TITLE
Allow for changing of input digits

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#292]
**Is your feature request related to a problem? Please describe.**
it would be nice to be able to change call routing and meeting lookup from 1 + 2 respectively. to have meeting lookup be 1 and volunteer routing be 2. this would have to be implemented in a way to not effect call records. I know of at least one other person requesting this feature.

**Additional context**
Nerna would like this change, we have high volunteer routing requests, which is good but we think they can get lowered if we can reverse the menu. we have limited volunteers and don't want to burn them out.

**Comment by radius314** [comment]
This sounds reasonable.  I have a few pending tickets to work on, I'll include this in the bunch.
