### ISSUE TITLE
jft getting routed to location gathering

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#295]
With unreleased 2.4.0, instead of playing jft it gets routed to location gathering.

**Comment by radius314** [comment]
Can not reproduce.

**Comment by pjaudiomv** [comment]
Using ['1' => SearchType::MEETINGS, '2' => SearchType::VOLUNTEERS, '3' => SearchType::JFT];

**Comment by radius314** [comment]
No change.

**Comment by pjaudiomv** [comment]
`static $digit_map_search_type = ['1' => SearchType::MEETINGS, '2' => SearchType::VOLUNTEERS, '3' => SearchType::JFT];` with latest build 3 now says you might have invalid entry

**Comment by pjaudiomv** [comment]
maybe im using wrong build

**Comment by pjaudiomv** [comment]
https://phoneline.nerna.org/yap-new/upgrade-advisor.php

**Comment by pjaudiomv** [comment]
build `e99abd21b2565a1b3d4f03736142da1f86789f90`

**Comment by pjaudiomv** [comment]
oh deer, nm. there must of been another bug that got fixed.

**Comment by pjaudiomv** [comment]
I didnt have jft_option enabled, however in older version i didnt have it enabled either but it worked. now that i enabled it for 3.4.0 its working as expected
