### ISSUE TITLE
location gathering not working

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#296]
**Describe the bug**
for meeting search or volunteer routing, it gos to the location gathering prompt, but when i select a digit (1 for city, 2 for zip) it says I might have an invalid entry.

**What version are you running?**
3.4.0 build `e99abd21b2565a1b3d4f03736142da1f86789f90`

**Comment by radius314** [comment]
able to repro

**Comment by radius314** [comment]
fix in build `7d9b927`

**Comment by pjaudiomv** [comment]
I tried this, now its not respecting my `digit_map_search_type` setting is this the right format i should be using `static $digit_map_search_type = ['1' => SearchType::MEETINGS, '2' => SearchType::VOLUNTEERS, '3' => SearchType::JFT];`

**Comment by pjaudiomv** [comment]
shit nm i was using this build `143e712062675f86fd20fd675aa1171416ced9d3`

**Comment by radius314** [comment]
💩

**Comment by pjaudiomv** [comment]
yes this indeed is fixed, thanks
