### ISSUE TITLE
Recording script

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#298]
A script to record prompts for use as prompts in Yap... I run a call center and it's really helpful to have a script we could either access through a back door or set up a dev number to, so you can get prompts recorded easily. After recording manually renaming and then using in our scripts would be manual or better yet a prompt library that you could select a prompt for this or that step...

**Comment by radius314** [comment]
Not sure I understand the content of what you are asking for, the benefit / goal.  Can you please add some clarification to this?
