### ISSUE TITLE
Wiki Editorial Access Request

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/yap#299]
**Do you want to help with Yap documentation?** 
Yes

**Do you agree to post useful and meaningful content?**
Yes

Holding off doing anything until after Danny's orientation.

ILS, Ann V

**Comment by radius314** [comment]
Wiki editing does not require git training.  I can give you access now.

**Comment by radius314** [comment]
You should have received an invite to become a collaborator on the wiki.
