### ISSUE TITLE
add ability for passing the service body id as a digit pass through

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#302]
this would be useful for using tomato service body routing, with only one or two numbers. nerna only has one number for region and areas dont need/want their own number, but we would still liek to use tomato routing.

**Comment by radius314** [comment]
in master and will be in 3.4.0

**Comment by radius314** [comment]
have you validated this @pjaudiomv ?

**Comment by pjaudiomv** [comment]
I have not, its on the short end of my todo list. if I cant test tonight, I should be able to tomorrow.

**Comment by radius314** [comment]
@pjaudiomv had you gotten a chance to get to this?

**Comment by pjaudiomv** [comment]
we may have to "pair" on this, I tried and couldn't get it configured properly.

**Comment by radius314** [comment]
What's the web hook on your second phone number look like?

**Comment by pjaudiomv** [comment]
second phone number is `index.php?override_extension_dial=true`

first, main number `index.php?override_tomato_helpline_routing=false`

**Comment by radius314** [comment]
What's the decision behind disabling tomato helpline routing on the initial number?

**Comment by pjaudiomv** [comment]
my bad thats set to true, i set it to false after it didnt work

**Comment by radius314** [comment]
You could also set it to nothing, set it to true in the configuration and then set it to false on the second number.

**Comment by radius314** [comment]
Did you get this to work?

**Comment by pjaudiomv** [comment]
Nope

**Comment by radius314** [comment]
Can you provide a little more detail about what that means?

**Comment by pjaudiomv** [comment]
I was finally able to get this to work, I had to use `override_extension_dial=true` because I am using tomato for meeting searches so if i used my config i would not of been able to login to the admin.

**Comment by radius314** [comment]
That should not matter, you do not set the helpline_bmlt_root_server to tomato.

**Comment by pjaudiomv** [comment]
yes but then yap doesnt know where my root server is for authentication

**Comment by pjaudiomv** [comment]
static $bmlt_root_server = "https://tomato.bmltenabled.org/main_server";
static $tomato_helpline_routing = true;

**Comment by pjaudiomv** [comment]
yap then has no way to know what root server to use and tries to authenticate with tomato

**Comment by pjaudiomv** [comment]
this is mentioned in docs https://github.com/bmlt-enabled/yap/wiki/Tomato-Helpline-Routing

**Comment by radius314** [comment]
Could you use this?

https://github.com/bmlt-enabled/yap/wiki/Using-A-Different-BMLT-server-for-routing

**Comment by pjaudiomv** [comment]
yes thats what im using works fine.

**Comment by radius314** [comment]
What you said doesn't make sense to me.  Tomato helpline routing does not use `bmlt_root_server` or `helpline_bmlt_root_server` settings.

**Comment by radius314** [comment]
Perhaps this a conversation better held over a plate of chicken.

**Comment by pjaudiomv** [comment]
sounds finger lickin good to me. I think we were both confused, if I did not set `$helpline_bmlt_root_server = "https://www.nerna.org/main_server";` in my config I would not be able to login to the admin because I had `static $bmlt_root_server = "https://tomato.bmltenabled.org/main_server";` set but yea tomato helpline routing doesnt care

**Comment by radius314** [comment]
You should be able to login into admin with those exact settings.

**Comment by radius314** [comment]
I don’t see why those settings hold any bearing about this ticket then.
