### ISSUE TITLE
Update Documentation URL

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/yap#303]
Can't update title of #303 to: Update Documentation URLs in Admin Console

**Describe the bug**
404 error on https://yap.bmlt.app/docs URLs.

**What version are you running?**
3.3.1

**Files affected**
yap/admin/home.php - Documentation URL
yap/admin/service_bodies.php - moh and configuration-precedence URLs

**Comment by radius314** [comment]
will be in 3.4.0
