### ISSUE TITLE
Not seeing check box to enable Volunteer Routing

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/yap#304]
**Describe the bug**
While installing a new Yap instance from scratch and following installation directions precisely, Not seeing check box to enable Volunteer Routing

**What version are you running?**
3.3.1

**Did this happen on prior versions to the one you are running?**
N/A

**To Reproduce**
1. Go to {yap_url}/admin
2. Click on Service Bodies, then Configure
3. Popup displays "Configure (Tidewater Area Service)"
4. See error - No check box to enable Volunteer Routing visible.

**Expected behavior**
From the Voluteer Routing Wiki page: "5. Go to the Service Bodies tab and click "Configure". From there you should see a check box to enable Volunteer Routing. Check it off and save."

**Screenshots**
![Nocheckbox](https://user-images.githubusercontent.com/43420450/63205726-aba67e80-c076-11e9-8b6a-7a2e8c8facce.png)

**Additional context**
Have had several issues with installations of Yap for testing. Re-trying and precisely following directions, unable to find this checkbox.
All other features of Yap are working except Volunteer Routing.

**Comment by devyces** [comment]
![Nocheckbox](https://user-images.githubusercontent.com/43420450/63205717-89146580-c076-11e9-8012-2de65d7f7664.png)

**Comment by pjaudiomv** [comment]
just updated wiki, https://github.com/bmlt-enabled/yap/wiki/Volunteer-Routing. this is in the vall handling, you would select volunteers under the helpline routing drop down.
