### ISSUE TITLE
ability to use different twilio number for sending messages

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#307]
this is in relation to #302 for nerna. by using this feature in conjunction with forced caller id the volunteers still get calls from our main line. however txt messages come through as the 2nd number used for service body id digit pass through. If we could override the from number on sending txt messages to our main line this would be great then everything appears as one line. this function would only be useable with phone numbers owned under the same twilio account and could not be used with just verified numbers.

**Comment by radius314** [comment]
This sounds like a bug more than a feature.

**Comment by pjaudiomv** [comment]
kind of but you can use forced caller id with verified numbers that arent in your twilio account, however that same verified number cant be used to send txts because of twilio regs

**Comment by radius314** [comment]
what happens when someone tries to text back.

**Comment by radius314** [comment]
It’s a bug in the fact that it should work this way already.  It shouldn’t require a second setting.

**Comment by pjaudiomv** [comment]
yea so if you txt back, it just sends you txts as the 2nd number. I manually changed it to the forced_caller_id number to test and it worked fine

**Comment by pjaudiomv** [comment]
like in the codez i changed the from of every instance of `$twilioClient->messages->create` to be the forced_caller_id number

**Comment by radius314** [comment]
It should be a function call to use the current number unless that is set.

**Comment by radius314** [comment]
You should probably stop making changes that no one can support.

**Comment by pjaudiomv** [comment]
yea this was just for testing, im not using it in production. I wouldnt use a feature if it wasnt in the main codebase. I stopped doing that a long time ago, it became unmanageable. the only thing left that ive changed that we use is bread.

**Comment by radius314** [comment]
I'd make a function called `getDialedNumber()`.

**Comment by pjaudiomv** [comment]
cool, I shall do the things

**Comment by radius314** [comment]
You wouldn’t actually be able to text back a forced called ID number.  The flow would drop off.

**Comment by radius314** [comment]
It’s the same issue as when someone tries to call back a forced caller if number.

**Comment by radius314** [comment]
This is in master
