### ISSUE TITLE
Ability for caller to have meeting schedule link sent to them by sms.

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#308]
Add option to caller menu to request a link to a meeting schedule by sms.

**Comment by radius314** [comment]
Which meeting schedule?  Which link?  When you open a feature request, could you be a little more descriptive in what you want the feature to be and what challenge you believe it will it address?

**Comment by californiasteve** [comment]
The caller would be able to request by option in the menu to have a link (bread meeting schedule) sent by SMS from the RSC/ASC they are calling to.

Say or push 1 to talk to someone
Say or push 2 to get meeting information
Say or push 3 for JFT
Say or push 4 for a link to our printable meeting schedule

**Comment by radius314** [comment]
Why would someone want a url to a printable meeting list on their phone?

**Comment by radius314** [comment]
There is already a feature which send a summary page of meetings to a caller https://github.com/bmlt-enabled/yap/wiki/SMS-Summary-Page

**Comment by californiasteve** [comment]
Correct, I had an ASC ask if this could be done also.

**Comment by radius314** [comment]
This does not seem like a good feature to build.

**Comment by californiasteve** [comment]
Ok
