### ISSUE TITLE
Random once then voicemail

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#310]
our service bodies have limited volunteers and it would be nice to be able to randomize who is called and then go to voicemail, so we dont have to randomize it ourselves every so often. and the same volunteers arent the once always getting the call first.

**Comment by radius314** [comment]
would it  be random for a time period and then voice mail?

**Comment by pjaudiomv** [comment]
Random till it gets through current volunteers on schedule then voicemail.

**Comment by radius314** [comment]
`Random once, then voicemail`

**Comment by pjaudiomv** [comment]
Omg yea, my bad

**Comment by radius314** [comment]
delivered in master ready to be tested

**Comment by pjaudiomv** [comment]
I tested and is working
