### ISSUE TITLE
Keeping Callers Phone Number Anonymous to Volunteers ?

### ISSUE THREAD

**Issue by SteveG-Gso** [bmlt-enabled/yap#315]
Testing the phone line using test number at this time.

The callers phone number appears on the answering volunteers phone / Caller I.D

Is there a setting to have the callers number not show on the volunteers phone ? Do have the Area Helpline number show on the volunteers phone or same incoming number all the time so volunteer can program it into their phone ?

**Comment by radius314** [comment]
It should already be anonymized.

**Comment by SteveG-Gso** [comment]
I'm using my Google Voice number to call the helpline. I request a person. 

The request comes through my cell phone showing my Google Voice / callers phone number.

**Comment by SteveG-Gso** [comment]
It is working properly. Helpline number shoes on volunteer's phone.

Mod can delete this thread
