### ISSUE TITLE
SMS Address URL bleeds into time field on Android mobile devices.

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/yap#317]
**Is your feature request related to a problem? Please describe.**

Using Yap version 3.3.1, generating SMS meeting output to a Samsung S8 mobile phone.
I'm inconvenienced when I can't click on the map link for driving directions to a meeting.
Address URL parsing is not consistent.

![20191008_183737](https://user-images.githubusercontent.com/43420450/66506434-53e72b00-ea9b-11e9-901a-09fa08707d12.jpg)

**Describe the solution you'd like**
Limit the URL to address information only.

**Describe alternatives you've considered**
n/a

**Mention any other of the Github handles that are also interested in this enhancement**

**Additional context**
Discussed on FB BMLT Group on 10/9/2019:
"Danny G: Would need help testing this on a couple different versions of the Android OS (there are a couple of versions out there), as well as iOS. The goal here being to find an OS neutral way of formatting."

**Comment by radius314** [comment]
I have fix that is worthy of testing out.  It's been pushed into yap 3.5.0-beta2

**Comment by radius314** [comment]
will be in yap 3.5.0
