### ISSUE TITLE
Yap instances without phone numbers

### ISSUE THREAD

**Issue by rdtripp** [bmlt-enabled/yap#319]
We have put up a helpline for the Louisiana Region.  It is set up to route calls to the appropriate area.  
1.  Is it possible to have instances of yap for each area that could be routed to from the region yap number without each area having a phone number of their own?

2.  Alternately could one instance of yap allow login by each areas credentials (in addition to region credentials) so that helpline scheduling for that area would be set up by each area.  

One of the above options (or both) would allow us to use one number for the whole region but allow each area control of their helpline volunteers.  The ability to forward to areas that still want to use their existing numbers would also need to be kept.

**Comment by radius314** [comment]
Yes this is entirely possible.  It’s the default behavior of yap.

**Comment by rdtripp** [comment]
I see what I was doing wrong.  I had the call handling for the area set up incorrectly.  Will work now.  Thanks!
