### ISSUE TITLE
Not retrieving - just spinning on "Retrieving Volunteers" or "Retrieving Service Body call handling"

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#320]
**Describe the bug**
Log into Yap 
Go to Volunteers - select an area - activity notice appears and just spins without producing results
Go to Service Bodies - click on Call Handling for any area - activity notice appears and spins without producing results

**What version are you running?**
3.5.0

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
as above

**Expected behavior**
expected to be able to see and edit volunteers or view and edit call handling.

**Screenshots**

**Additional context**
running on my test server

**Comment by radius314** [comment]
Suggestion is to roll back, this is beta software not to be used in production.

**Comment by brustar64** [comment]
Not in production.  In testing only.

**Comment by radius314** [comment]
Did you close this because it was resolved?

**Comment by brustar64** [comment]
No, I thought you meant you  would be addressing it in a later release
________________________________

**Comment by radius314** [comment]
Can you send an screenshot of the javascript console?

**Comment by brustar64** [comment]
[cid:c5abc38b-4a16-481d-9767-0e303a4174a0]
It just sits there doing this...

________________________________

**Comment by radius314** [comment]
No images attached

**Comment by gutterwall** [comment]
It just started happening to me too on older version  3.3.1. no response from any lookup query yet the webpage returns results

**Comment by radius314** [comment]
Hopefully you backed up your database before installed this.

**Comment by radius314** [comment]
Ok 3.4.0 is the latest.

**Comment by radius314** [comment]
I’m assuming this is not affecting production?

**Comment by gutterwall** [comment]
It is we are down :(

**Comment by radius314** [comment]
define down?  are calls not completing?

**Comment by gutterwall** [comment]
No searches or volunteers are being retrieved, the only thing that works is
the just for today

**Comment by gutterwall** [comment]
I have my homegroup and then I'll be looking into trouble shooting at after
7 or so

**Comment by radius314** [comment]
Ok let's move this to outside this ticket, because it's totally unrelated to what you are seeing.

**Comment by radius314** [comment]
this fix will be in yap 3.5.0 beta 2

**Comment by brustar64** [comment]
Thanks Danny
________________________________
