### ISSUE TITLE
Answer calls without having to press 1

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#321]
**Is your feature request related to a problem? Please describe.**
Volunteers have mentioned that there is about a five second delay between when they answer the call and when the announcement to "You have a call from the helpline. press one to answer press any other key to hang up".  Others have also mentioned that they accidentally hit the wrong key and hanged up on the caller. 

**Describe the solution you'd like**
I'd like an organic scenario where if they answer the call they don't have to press anything, they just take the call.  If they are unable to take the call they hang up without answering and the call goes to the next volunteer (or voicemail if there are no more volunteers left in the cycle). 

**Describe alternatives you've considered**
Haven't considered any alternatives at this point. Open to suggestions.

**Mention any other of the Github handles that are also interested in this enhancement**
@radius314 thought it was a reasonable request.

**Comment by radius314** [comment]
this feature will be available for testing in the 3.5.0-beta3

**Comment by radius314** [comment]
Keep in mind that this feature would possibly cause calls to go to someone's personal voicemail.  The press 1 feature is protection over that happening.

https://github.com/bmlt-enabled/yap/wiki/Volunteer-Auto-Answer

**Comment by brustar64** [comment]
Ah ok, that makes sense. I didn't think about that aspect. It will be switchable right?
________________________________

**Comment by radius314** [comment]
It is switchable, off by default

**Comment by radius314** [comment]
will be in yap 3.5.0 https://github.com/bmlt-enabled/yap/wiki/Volunteer-Auto-Answer
