### ISSUE TITLE
Yap Specialized Routing

### ISSUE THREAD

**Issue by webfacilitator** [bmlt-enabled/yap#325]
Spanish meeting helpline in North Atlanta Area of Georgia Region having several issues.  First, each caller is presented with English and Spanish as choices.  But, when Spanish is chosen, if I am looking in Twilio at call logs and refreshing, Yap dials a mix of English and Spanish speaking volunteers, regardless of the fact that each group is carefully setup just to answer 1 language.  Also, Yap never calls all 6 volunteers on Spanish list but stops after 3-4 and leaves the caller in a perpetual muzak with no option to voicemail even though Cycle Once, Then Voicemail is selected and an email address set.

**Comment by webfacilitator** [comment]
![Spanish Yap settings](https://user-images.githubusercontent.com/24917511/68536145-08cf6a80-031c-11ea-9e1c-420fb4e78b64.png)

**Comment by webfacilitator** [comment]
![Spanish Yap settings](https://user-images.githubusercontent.com/24917511/68536156-3ae0cc80-031c-11ea-8db3-4750a9bf9ce6.png)

**Comment by webfacilitator** [comment]
![Spanish Yap settings](https://user-images.githubusercontent.com/24917511/68536161-4c29d900-031c-11ea-97ec-4e5f1e0ef249.png)

**Comment by webfacilitator** [comment]
![Spanish Yap call handling](https://user-images.githubusercontent.com/24917511/68536175-898e6680-031c-11ea-9061-952d8d18cb9c.png)

**Comment by radius314** [comment]
Have you tagged the volunteers with the correct language?

**Comment by webfacilitator** [comment]
Yes. J

**Comment by radius314** [comment]
This is definitely a bug.  Fix will be in yap 3.5.0

**Comment by radius314** [comment]
The fix for this is in master.

**Comment by radius314** [comment]
will be in yap 3.5.0
