### ISSUE TITLE
Cycle Once, Then Voicemail

### ISSUE THREAD

**Issue by webfacilitator** [bmlt-enabled/yap#327]
Calls are not almost never completing list of volunteers in a group or indivdually listed.  As a result, call are never arriving to voicemail.  Callers report waiting 45 - 75 minutes and sill no voicemail.
Georgia Region is having to switch Call Strategy to Blast and insert an external number with voicemail to get the desired effect.

Enter the version number: 3.4.0 at https://xxxx/zonal-yap/admin/index.php

**Comment by radius314** [comment]
Can you share a sample log from your Twilio account?  Send to help@bmlt.app.

**Comment by radius314** [comment]
Hey @webfacilitator can you provide any information further?

**Comment by webfacilitator** [comment]
It appears to only happen when we use multiple groups. So, we narrowed our
setup to only use 1 moderate sized group and that works. The cycle once,
then voicemail takes too long for more than 6-7 volunteers.

My region liked Telzio which did Blast for a specified time period and then
voicemail.

Our volunteers are also struggling with the need to press 1 to accept the
call after already answering. I don’t want to turn that feature off because
the call going to their personal voicemail is a problem.

And, lastly, my region preferred option 1 being automatic meeting info and
option 2 to speak with someone.

Jay Hall

**Comment by pjaudiomv** [comment]
The next release will have better support for call blasting, so you could have it call everyone for say 20sec then go to voicemail. you can change meeting info to one and two for someone to talk to by setting the following in your config. 
`static $digit_map_search_type = ['1' => SearchType::MEETINGS, '2' => SearchType::VOLUNTEERS, '3' => SearchType::JFT];`
