### ISSUE TITLE
Yap SMS Summary Link not working with Sprint

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/yap#328]
We've had multiple reports of YAP's SMS feature where you type the zip code to get the meetings not working.

We're using the most recent version

It's not been reported before recently

I asked a sprint user again yesterday to try the SMS and zip code, and they get nothing
They type in a zip code and get nothing.

The Twilio SMS logs look ok to me. 

[sms-log-AC006cdbb04e6632ca8ec1a34f347b5c0e_2019-11-16.xlsx](https://github.com/bmlt-enabled/yap/files/3854285/sms-log-AC006cdbb04e6632ca8ec1a34f347b5c0e_2019-11-16.xlsx)

901-219-5397 is a sprint user
901-497-0691 is me... 
the logs look the same.
the sprint users aren't getting a response when using SMS, but when calling it works,  (although not getting the meetings by text as well as voice option)

**Comment by radius314** [comment]
Did they accidentally block the number?

**Comment by radius314** [comment]
On their phone?

**Comment by radius314** [comment]
Also @lucy12187 did any other sprint users report the same issue?

**Comment by lucy12187** [comment]
The member I was talking to today (glen, the 901-219-5397 number in the log) and who also checked the other day when I was first made aware of the problem, said that he checked and he is not blocking the number.
And yes it was on his phone.  

And yes when i first heard about it, Stephen Z from knoxville reported it (the 865-951-8298 number...  this may not be on the log i uploaded because that log was just for a few hours last night/this morning.
So, i've only found 2 sprint users to check it... both with issues.  

Stephen  sent a couple screen shots... apparently it did work... then it stopped.
![stephen2](https://user-images.githubusercontent.com/15731404/69001201-48f49700-08a0-11ea-9d55-6f047c53b5d7.jpg)
![stephen](https://user-images.githubusercontent.com/15731404/69001202-48f49700-08a0-11ea-9472-90a79d95a262.jpg)

**Comment by radius314** [comment]
Ok please pass on the logs.

**Comment by lucy12187** [comment]
I noticed when searching for "sprint and twilio problems" it comes up several times... some recent, some a few years ago... always eventually resolved.  the issues frequently mention 'short codes and long codes'

**Comment by lucy12187** [comment]
> Ok please pass on the logs.

I sent logs for last night/today in my first post... I'll go back to the first of the week and send them.  
[sms-log-AC006cdbb04e6632ca8ec1a34f347b5c0e_2019-11-16. this eveningcsv.xlsx](https://github.com/bmlt-enabled/yap/files/3855108/sms-log-AC006cdbb04e6632ca8ec1a34f347b5c0e_2019-11-16.this.eveningcsv.xlsx)

**Comment by radius314** [comment]
There are periodic issues with Sprint.  I would suggest opening a ticket with them to investigate.

**Comment by radius314** [comment]
This issue has been reopened to track the issues with the SMS Summary Link feature and Sprint.

**Comment by radius314** [comment]
@lucy12187 can you try sending a test text yourself to this person with the same exact contents of the message received back from yap.  I'd like to see if it's a Twilio thing or if it's a general block by Sprint.  I'd also suggest texting different variations to the person to try to isolate maybe why it's being blocked.

**Comment by lucy12187** [comment]
@radius314  I sent them the link I get on my phone... although on my phone i have to click twice to get the meetings.  They both got the link  - the 2 sprint users I most recently asked to check our yap number.  

Would you like me to put our yap back temporarily to the summary option?

**Comment by radius314** [comment]
What do you think that would accomplish?

**Comment by lucy12187** [comment]
It would be easier to see when it started back working like it should for sprint users.

**Comment by radius314** [comment]
It’s worth a shot.

**Comment by radius314** [comment]
Can you try this patch to see if it fixes the issue?

replace .htaccess in the root and meeting-results.php in the endpoints folder.  Be sure to take a backup of both those files before.  Have a sprint user test.

[sprint-patch.zip](https://github.com/bmlt-enabled/yap/files/3903228/sprint-patch.zip)

**Comment by lucy12187** [comment]
I should have responded here instead of just the Facebook group. Please
forgive me. But it was working a couple or so days ago.
Not sure if it was fixed as a result of me reporting it to twilio and they
got with sprint or not. They did say they would be in contact with the
carrier after I reported it.

Lucy

**Comment by radius314** [comment]
Could you also test this change?

**Comment by lucy12187** [comment]
Sure. When I get to my computer. Although I’m paranoid to mess with the
htaccess file. Seems like i had issues with something to do with it early
on.

I’ll let you know when I’ve tried it.

Lucy

**Comment by radius314** [comment]
Ok that's fine, I'll ask someone else to test.

**Comment by lucy12187** [comment]
i'm back to my room... i'm at VRC. 
i'll give it a try... 
my htaccess file has this in it.
# Added by provider
Options +Indexes
RewriteEngine On
RewriteCond %{HTTP_HOST} natennessee\.org [NC]
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://natennessee.org/$1 [R,L]

should i add what is in the other one to this one?

**Comment by radius314** [comment]
there should be one inside the yap folder.  not this one.

**Comment by lucy12187** [comment]
i uploaded the 2 files.  and it works for me.  should i ask the sprint folks to try it?

**Comment by radius314** [comment]
can you send a screenshot of what you got?

**Comment by radius314** [comment]
both on the text and the url location bar in your web browser.

**Comment by lucy12187** [comment]
![screenshot yap](https://user-images.githubusercontent.com/15731404/69843079-84417f00-122b-11ea-8479-2c3cc6e309ca.jpg)

**Comment by lucy12187** [comment]
that first screen shot was after you clicked, click here... about to upload the screen shot BEFORE i click here.

**Comment by lucy12187** [comment]
this is the first screen shot before i click here. ...

![first screenshot yap](https://user-images.githubusercontent.com/15731404/69843374-cdde9980-122c-11ea-9b67-c275d911fe28.jpg)

**Comment by radius314** [comment]
Have one of your sprint users test.

**Comment by lucy12187** [comment]
this is the 2nd screen shot with the web icon (i'll ask some folks to try it.
![first screenshot yap](https://user-images.githubusercontent.com/15731404/69843512-72f97200-122d-11ea-8e15-175122038840.jpg)

**Comment by lucy12187** [comment]
my 3 sprint users get the link.

**Comment by radius314** [comment]
will be in yap 3.5.0
