### ISSUE TITLE
Call Strategy Blasting Time Delimited, Then Voicemail

### ISSUE THREAD

**Issue by webfacilitator** [bmlt-enabled/yap#332]
We (Georgia Region) are frustrated that the only call strategy that ends in voicemail is Cycle which leaves the caller on hold a long time.  We would like to see the Call Strategy Blasting have a time limit setting and then go to Voicemail.

**Comment by radius314** [comment]
there are several improvements to call strategy in 3.5.0 including random once, then voicemail, and improved call blasting.

**Comment by radius314** [comment]
In the future, it’s probably not great to start your feature ask with “frustration”.  The people who do this work are not paid., and do it as a labor of love.

**Comment by webfacilitator** [comment]
Sorry man. I was trying to follow the template. I am not really frustrated.
🤗

**Comment by radius314** [comment]
Will explore adding voicemail to call blasting.

**Comment by webfacilitator** [comment]
Thanks for your help.  We really do appreciate all you do and have done.
Georgia is very thankful for the whole BMLT team.  I cannot imagine trying
to find the time for it.  Seriously.  I get how it benefits your recovery
but life gets full.

Jay Hall

**Comment by radius314** [comment]
I think I might have a way to do this, will test my theory out soon.

**Comment by radius314** [comment]
call blasting will have voicemail in 3.5.0

**Comment by webfacilitator** [comment]
Awesome!!!!

**Comment by pjaudiomv** [comment]
just tested this with build `ae6288b9722744bd00a3e566a8a7b969a621f14d` works great, thanks.

**Comment by webfacilitator** [comment]
Thank you guys so much! Even good vendors take a year for program changes.
We were really fortunate to have your help!!

Jay Hall

**Comment by radius314** [comment]
@pjaudiomv what version of MySQL are you running?

**Comment by pjaudiomv** [comment]
5.6.40

**Comment by spiritualtheory** [comment]
5.6.30 looks like

**Comment by radius314** [comment]
will be in yap 3.5.0

**Comment by radius314** [comment]
> Sorry man. I was trying to follow the template. I am not really frustrated. 🤗
> […](#)

I recognize what you meant now, my bad.  I have fixed the template to not say this anymore.  https://github.com/bmlt-enabled/yap/commit/5dd42a80ab386d29456e356a9a3618c07738a7d8
