### ISSUE TITLE
Call records not displaying in list

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#335]
**Describe the bug**
In reports calls show in the graph but the records don't show in the list. Note that voicemail records are displaying fine.

**What version are you running?**
I'm on `0ec0a0a688f89e691ed19395ec1fc6b5cea28d1c` but this also doesn't work in `3.5.0-beta4`

**Expected behavior**
Records display in list, not just graph.

**Screenshots**
![Screen Shot 2019-12-01 at 2 59 33 PM](https://user-images.githubusercontent.com/34245618/69919484-373bf380-144b-11ea-849a-761e774d3866.png)

**Comment by radius314** [comment]
Any records in `records_events` or `records`?

**Comment by pjaudiomv** [comment]
no, not in either.

**Comment by radius314** [comment]
Did you ensure to point your status webhook to status.php?

**Comment by pjaudiomv** [comment]
no, no I did not. I shall do that. forgot about that

**Comment by radius314** [comment]
I couldn't think of a great way to let people know to set this.  Because you could have many phone numbers (and some of them may not be used for Yap).

**Comment by pjaudiomv** [comment]
should i do it for sms to or just voice

**Comment by radius314** [comment]
Call Status Changes only exist for "Calls".

**Comment by pjaudiomv** [comment]
yes just saw that, that makes sense hah

**Comment by radius314** [comment]
https://github.com/bmlt-enabled/yap/wiki/Call-Detail-Records

**Comment by pjaudiomv** [comment]
works fine now that status hook is set, closing this
