### ISSUE TITLE
reports not sorting by call time correctly

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#346]
3.5.1 commit `0a841a3beb69d22370d0dbc82eb18918037e5c27` call records aren't being sorted correctly chronologically. note the underlined entry should be on top

![Screen Shot 2019-12-10 at 7 16 30 PM](https://user-images.githubusercontent.com/34245618/70580430-b9ca5e80-1b81-11ea-8c9f-a0ab2a7961d4.png)

**Comment by radius314** [comment]
can you test against the latest build?

**Comment by pjaudiomv** [comment]
yes that worked, thanks.

**Comment by radius314** [comment]
available in 3.5.1
