### ISSUE TITLE
Custom Greeting Not Working

### ISSUE THREAD

**Issue by rdtripp** [bmlt-enabled/yap#347]
When I put in a url to an mp3 for a custom greeting in the yap call handling it doesn't work. When I try to play it to test it by selecting the "play" option in YAP it opens a web page "about:blank:" . Tried several urls to mp3 files with the same result.

The url I need is at: https://voice.nlana.net/message3.mp3 and plays fine everywhere else.

YAP 3.5 stable

**Comment by radius314** [comment]
To clarify, this has nothing to do with playing back custom greetings.  This is merely a testing feature to ensure the URL is correct.  The workaround for making this work, is to copy and paste the url in a new browser window / tab.  If the browser plays back the URL then the audio file should work.  If there is some other bug related to playing back custom prompts then the repro steps for that scenario should be clearly outlined.

**Comment by radius314** [comment]
Fix for this specific issue is in the latest master build.

**Comment by radius314** [comment]
available in 3.5.1
