### ISSUE TITLE
full call records not displaying on reports for all service bodies

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#348]
When viewing call records on the `All` Service Bodies dropdown not all info on call record is displaying, however if I go to that service body it does display there.

all service bodies

![AllServiceBodies](https://user-images.githubusercontent.com/34245618/70805010-ef3f9980-1d85-11ea-9939-5c5196842d95.png)

the individual service body 

![:IndividualServiceBody](https://user-images.githubusercontent.com/34245618/70805012-f1a1f380-1d85-11ea-9338-2cd763ad9413.png)

**Comment by radius314** [comment]
check the latest build

**Comment by radius314** [comment]
for a fix for this

**Comment by pjaudiomv** [comment]
cool that fixed it, it also removed all call records with zero events (robo callers) which is nice

**Comment by radius314** [comment]
Actually that would delete records where no one pressed a button too.

**Comment by radius314** [comment]
Not delete, hide.

**Comment by pjaudiomv** [comment]
👍

**Comment by radius314** [comment]
available in 3.5.1
