### ISSUE TITLE
mapping report data

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#353]
I'm just creating this here to track somewhere.

with the new reporting features, I could envision creating a yap plugin that could map the reporting data. For ex. a google map with points of where all volunteer lookups are being done for over a set period of time. A way to visualize the data geographically.

**Comment by radius314** [comment]
This should be listed under reports section, not as a plugin.

**Comment by radius314** [comment]
in master will be 3.6.0
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1850811/71645749-df431780-2caa-11ea-9d70-8401dee20cbf.png">

**Comment by radius314** [comment]
I'm thinking it might make sense to make a way to export the data, for example, to layer the results over where meetings are.  What do you think is the best format for returning the results?

**Comment by radius314** [comment]
POI CSV downloads are in master now.

**Comment by radius314** [comment]
released in 3.6.0
