### ISSUE TITLE
Helpline Redirect Issue

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#354]
Since upgrading to 3.5.0 (I'm guessing that the issue has occurred since then we just noticed it today), We've had a weird configuration issue for the Sydney Metro "Helpline Field" redirect.
The config screen shows options for Primary Contact Recorded greeting and Voicemail greeting.
![sydney metro fields](https://user-images.githubusercontent.com/29008815/71329106-676b4380-256c-11ea-9d88-95e3f353241f.png)
Calls are not being routed through to their helpline.
If I change their option to Volunteers, save then change it back to Helpline it shows the correct options before I save but when I reopen it shows the additional fields again.
- before save
![image](https://user-images.githubusercontent.com/29008815/71329185-c5e4f180-256d-11ea-9092-5ad4186dad9c.png)

**Comment by radius314** [comment]
This is not a bug.  You cannot use volunteer redirection for helpline field routing.
