### ISSUE TITLE
Activities Option in YAP

### ISSUE THREAD

**Issue by jwatson12** [bmlt-enabled/yap#355]
Would like to see the option where users call in and have an option for activities like dances, conventions,etc. This should be read off as an MP3 file.

Our old activities line was a phone option where someone would just read off flyers a group or area provided. This could stay the same with the new option with MP3.

Lastly,  it would be nice to just upload PDF files of flyers to a specific location and have a computer voice read off the content in each of the pdf files effectively creating that MP3 (text to speech engine)

**Comment by radius314** [comment]
Reading PDFs is very unreliable, unless formatted correctly.  Most likely this would require reformatting as most folks do not understand the semantics how to do this.  I get the intention of this feature though, and there seems like there could be a way to automate potentially some other way.

**Comment by jwatson12** [comment]
Can we do the mp3 option where the flyers are read off by a person and updated on a regular basis?

**Comment by radius314** [comment]
Not currently.  There would have to be a change to support this.

**Comment by radius314** [comment]
Custom extensions option will be available in version 3.7.0.  Details are here: https://github.com/bmlt-enabled/yap/wiki/Custom-Extensions

You could do a few things with this.

1) Set the custom extension option to play back a recorded MP3 with the announcements.  
2) Add a custom extension that redirects to another phone number in Twilio that has a TwiML bin that plays back announcements.
3) With a few future enhancements to `sub`, we could create the ability to automatically text-to-speech announcements (assuming you are using it).

https://github.com/bmlt-enabled/sub/issues/4
https://github.com/bmlt-enabled/sub/issues/5
https://github.com/bmlt-enabled/sub/issues/6

**Comment by radius314** [comment]
This is in master and testable https://archives.bmlt.app/yap/yap-1379-ae2fa62c5507aa4b79b36dc4e698cb8a8e7b1483.zip
