### ISSUE TITLE
not displaying map markers on 3.6.0

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#363]
this is for sezf server, getting the followng errors. 

![Screen Shot 2020-01-04 at 9 54 16 PM](https://user-images.githubusercontent.com/34245618/71774445-f0a35280-2f3c-11ea-88f8-44c7c1ac6dae.png)
![Screen Shot 2020-01-04 at 9 53 43 PM](https://user-images.githubusercontent.com/34245618/71774446-f0a35280-2f3c-11ea-9678-31a41067fea1.png)
![Screen Shot 2020-01-04 at 9 52 47 PM](https://user-images.githubusercontent.com/34245618/71774447-f0a35280-2f3c-11ea-9937-35267528e26c.png)

**Comment by radius314** [comment]
could repo.  looks like there are cases where null responses are logged.  one use case someone entered `31` for a zip code.  i will filter these out of the map metrics endpoint.

**Comment by radius314** [comment]
Try latest master please.

**Comment by pjaudiomv** [comment]
so the map markers are displaying now but the browser is still bombing out and freezing.

![Screen Shot 2020-01-04 at 11 03 14 PM](https://user-images.githubusercontent.com/34245618/71774968-8abbc880-2f46-11ea-86cb-1923cbc1bd1e.png)

**Comment by pjaudiomv** [comment]
![Screen Shot 2020-01-04 at 11 11 25 PM](https://user-images.githubusercontent.com/34245618/71775024-9491fb80-2f47-11ea-8dc9-f0e2dda6c110.png)

**Comment by radius314** [comment]
Unable to repro.

**Comment by pjaudiomv** [comment]
it happens when i log in as carolina region admin but not as yap admin user

**Comment by radius314** [comment]
Able to repro now.

**Comment by radius314** [comment]
Patched in the laster master build.

**Comment by pjaudiomv** [comment]
cool that fixed it

**Comment by radius314** [comment]
will be in 3.6.1
