### ISSUE TITLE
call records displaying for service bodies outside user scope

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#364]
when displaying all call records im seeing results for all service bodies not just within scope of user, not sure if this is intended or not. For instance i login with carolina region admin and call records for georgia are showing up

**Comment by radius314** [comment]
What would you like to see instead?

**Comment by pjaudiomv** [comment]
call records only for the carolina region

**Comment by radius314** [comment]
What about cases where the call is in the General bucket?  For example, if someone calls to do a meeting search, there is no service body sometimes at the point of lookup.

**Comment by pjaudiomv** [comment]
or records only within scope of logged in user

**Comment by pjaudiomv** [comment]
yea i mean maybe thats just the rub with using shared yap server

**Comment by radius314** [comment]
It has more to do with whether a service body is specified up front.  When doing a meeting lookup, there are no service bodies typically defined.

**Comment by pjaudiomv** [comment]
yea I understand, totes makes sense.

**Comment by pjaudiomv** [comment]
it would be cool if selecting carolina region would display all records for the region

**Comment by radius314** [comment]
It could probably if anything not return results for service bodies it doesn’t have access to, but still show all the General ones.

**Comment by pjaudiomv** [comment]
yea I'm not too worried about it, squeeze probably is not worth juicing.

**Comment by radius314** [comment]
Ok file a separate ticket for a feature request to recurse service bodies.

**Comment by pjaudiomv** [comment]
Cool

**Comment by radius314** [comment]
fix is in master

**Comment by radius314** [comment]
released in 3.6.2
