### ISSUE TITLE
marker color mixup

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#370]
on  the map meeting lookup is green but the chart/tally its orange and vice versa with volunteer lookup.

on 3.6.2

**Comment by radius314** [comment]
was this on prior versions?

**Comment by pjaudiomv** [comment]
yes

**Comment by radius314** [comment]
ok this seems like a simple fix, sending over now.

**Comment by radius314** [comment]
in master

**Comment by radius314** [comment]
released in 3.6.3
