### ISSUE TITLE
sms hyperlink of summary page response is 500 error

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#374]
I upgraded to 3.6.3 latest, and now I get the SMS of the meeting links page, but it gives a 500 internal error when I run that page.

I have a new instance https://yap.centralatlanticregionofna.org/

the page for instance is https://yap.centralatlanticregionofna.org/endpoints/msr/37.5464259/-774644607

I don't know if I did everything I needed to as far as table cleanup, which I did see in the instructions, but the reporting seems to be working fine. (I added the status.php callbacks successfylly).  I am trying to get this 100% working so I can motion we adopt it,..

**Comment by pjaudiomv** [comment]
how did you upgrade, is there a .htaccess file in the directory. whats in your server logs.

**Comment by radius314** [comment]
What is the actual error?  A 500 is a browser response.

**Comment by gutterwall** [comment]
I copied the new release up and renamed the folder to fit the mapping.

Yes I am using the .htaccess file that came with the release. I tried it
with a rewrite base and without, and I removed the subfolder problem
completely by using a subdomain. Calling works, sms works it's just this
one piece

**Comment by radius314** [comment]
everything is throwing a 500, so not sure how that is possible.

**Comment by gutterwall** [comment]
I am not sure. That was working a minute ago still fiddling

**Comment by gutterwall** [comment]
I will start over with 3.6.2 upload and see what happens

**Comment by gutterwall** [comment]
I re uploaded the code and reapplied the config and still get the same
errors. The admin site works and now the calling fails.

Maybe my subdomain mapping isn't working? Pain in the...

I have a PR meeting will come back in an hour or so

**Comment by gutterwall** [comment]
I had to readd the RewriteBase /
To the htaccess for 1and1... Sorry please close the ticket

**Comment by radius314** [comment]
closing
