### ISSUE TITLE
Timezone?

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#376]
I did a zip code search in my Yap and it only returned meetings from tomorrow. Is there a timezone setting I need to correct?  I had a 15 minute grace and there are tons of meetings tonight not displaying

**Comment by radius314** [comment]
There are no timezone settings.  Timezone is automatically calculated by the location search criteria.

**Comment by gutterwall** [comment]
Now it works right... Never mind. Maybe I need to verify before next
ticket. Sorry to bother you...
