### ISSUE TITLE
Eliminate single service body drop down choice

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/yap#377]
**Is your feature request related to a problem? Please describe.**
I think it would be a good feature to simplify the UI for non-admin users that only have access to one service body.

**Describe the solution you'd like**
Eliminate the Select a Service Body drop down menu and automatically display the single service body for non-admin users that only have one service body to select.

**Describe alternatives you've considered**
Leave the UI as is, train non-admin users to select the service body.

**Mention any other of the Github handles that are also interested in this enhancement**

**Additional context**
![2020-01-24 (1)](https://user-images.githubusercontent.com/43420450/73056884-1a75d800-3e5e-11ea-9821-7c96d9140baa.png)

**Comment by radius314** [comment]
This feature was completed by @pjaudiomv and it's in master.

**Comment by radius314** [comment]
released in 3.6.3
