### ISSUE TITLE
Dropdowns not working on IE11 / Win10

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#389]
**Describe the bug**
Dropdowns not working on Internet Explorer 11 (Windows 10)

**What version are you running?**
3.6.4

**Did this happen on prior versions to the one you are running?**
Not sure.

**To Reproduce**
1. Log into an account that has one service body enabled.
2. Go to Volunteers
3. Note that the dropdown doesn't auto select the first choice.
4. When you select the dropdown choice manually, it also doesn't list the volunteers.

**Expected behavior**
1. That if there is one choice in a dropdown that it's auto-selected.
2. Volunteers are displayed after a choice is selected (if they already exist).

**Screenshots**
![image](https://user-images.githubusercontent.com/1850811/74968685-38951080-53e9-11ea-956c-3a43c77b5a8c.png)

**Additional context**
N/A

**Comment by radius314** [comment]
It's becoming untenable to maintain IE11.  Ending support.

**Comment by pjaudiomv** [comment]
the juice just wasn't worth squeezing.

**Comment by radius314** [comment]
There was a lot more causing this than I realized.
