### ISSUE TITLE
Message Blast ?

### ISSUE THREAD

**Issue by SteveG-Gso** [bmlt-enabled/yap#390]
Is there a way to message blast information to volunteers ?

**Comment by pjaudiomv** [comment]
No, you could use sub though https://github.com/bmlt-enabled/sub

**Comment by radius314** [comment]
The current data model for volunteers would not easily support such a feature.  There would have to be a significant restructuring for this to occur.  I do think there are benefits to doing this, but it's not a top priority.

**Comment by dgershman** [comment]
There are other solutions out there for this, including messaging platforms.  Building out broadcast solutions into Yap is also something that doesn't seem to fit the model of what Yap was designed for.
