### ISSUE TITLE
Error to start YAP

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/yap#409]
**Describe the bug**
when we try to access:
https://csa-saopaulo.org/bmlt/yap-master/index.php
Fatal error: require_once(): Failed opening required '/home/ts00013/public_html/bmlt/yap-master/endpoints/_includes/../../vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/ts00013/public_html/bmlt/yap-master/endpoints/_includes/twilio-client.php on line 2

**What version are you running?**
last version

**Did this happen on prior versions to the one you are running?**
first time
**To Reproduce**

**Expected behavior**
https://csa-saopaulo.org/bmlt/yap-master/index.php

**Screenshots**

**Additional context**
Even if we change PHP version from 5.* to 7.*

our file

<?php
require_once __DIR__ . '/../../vendor/autoload.php';
use Twilio\Rest\Client;

try {
    $twilioClient = new Client(setting("twilio_account_sid"), setting("twilio_auth_token"));
    $GLOBALS['twilioClient'] = $twilioClient;
} catch (\Twilio\Exceptions\ConfigurationException $e) {
    error_log("Missing Twilio Credentials");
}

function hup($callSid)
{
    $GLOBALS['twilioClient']->calls($callSid)->update(array('status' => 'completed'));
}

**Comment by abna-brasil** [comment]
our file sample

<?php
require_once __DIR__ . '/../../vendor/autoload.php';
use Twilio\Rest\Client;

try {
    $twilioClient = new Client(setting("twilio_account_sid"), setting("twilio_auth_token"));
    $GLOBALS['twilioClient'] = $twilioClient;
} catch (\Twilio\Exceptions\ConfigurationException $e) {
    error_log("Missing Twilio Credentials");
}

function hup($callSid)
{
    $GLOBALS['twilioClient']->calls($callSid)->update(array('status' => 'completed'));
}

**Comment by radius314** [comment]
Looks like you pulled the source code.  Be sure to use the release version in the zip file https://github.com/bmlt-enabled/yap/releases/download/3.6.4/yap-3.6.4.zip

**Comment by radius314** [comment]
Do you need help still?

**Comment by abna-brasil** [comment]
Hello
We finally set up a yap server here in Brazil!
Let me ask you guys...
How to make it talk with our help line sip account?

https://csa-saopaulo.org/bmlt/yap/admin/
![yap001](https://user-images.githubusercontent.com/61021590/82396917-91466a80-9a25-11ea-8dec-f42730854958.JPG)
![yap002](https://user-images.githubusercontent.com/61021590/82396919-92779780-9a25-11ea-97a7-d318ddaefc81.JPG)

**Comment by radius314** [comment]
You should be using Yap 3.7.3 https://github.com/bmlt-enabled/yap/releases/download/3.7.3/yap-3.7.3.zip.

Are you using yap for meeting lookups or for volunteer routing too?

**Comment by abna-brasil** [comment]
both

**Comment by radius314** [comment]
Did you set up the Twilio account?  This is going to handle all the phone circuiting and SMS.  Maybe we should schedule a call to go through this?

**Comment by abna-brasil** [comment]
upgrade done
![yap003](https://user-images.githubusercontent.com/61021590/82398414-2b5be200-9a29-11ea-8a75-544d3fd5a8da.JPG)

**Comment by radius314** [comment]
good

**Comment by abna-brasil** [comment]
about Twilio, yep... we have a ID and key...
but not sure about what we need to setup "inside" twilio

**Comment by radius314** [comment]
You will need to buy a phone number.  Once you do that you will configure your webhooks.

Be sure to follow Step 4 on this page.  https://github.com/bmlt-enabled/yap/wiki/Setup <https://github.com/bmlt-enabled/yap/wiki/Setup>.

Also you will want to change your default language and voice too.

https://github.com/bmlt-enabled/yap/wiki/Language-Options <https://github.com/bmlt-enabled/yap/wiki/Language-Options>

**Comment by abna-brasil** [comment]
buy a phone number from twilio api?

**Comment by abna-brasil** [comment]
we already have a SIP acount... we cannot use it?

**Comment by radius314** [comment]
You can buy a number from the Twilio dashboard.  You do not need to use the API.

https://www.twilio.com/console/phone-numbers/search <https://www.twilio.com/console/phone-numbers/search>

**Comment by radius314** [comment]
You cannot use your own SIP account unless you want to redirect the call.  You will still need a new phone number.  You could also port your old number over (if you own it), after you complete testing.

**Comment by abna-brasil** [comment]
Here in Brazil we have about 120 different helpline numbers. We currently have a number, based on a SIP account, which is a 0800 number (toll free).
How does it work:

1) Someone calls 0800 (not SIP)
2) the system answers with a recording and saves the source number of the call
3) our SIP account calls the source and connects it to one of the available extensions.


At first we thought of YAP to be one of the extensions of the SIP account
For example, when arriving at item 3 above, the SIP system offers:

a) Search for a meeting (YAP)
b) Volunteer (YAP)
c) talk to someone (another extension)

**Comment by radius314** [comment]
Yap is very flexible.  You could have a single number for the entire nation and then redirect the call based off the location of the caller (using voice recognition and the BMLT data lookup).

You could phase out the existing numbers or you could later port them over to point directly to Yap.

There are many approaches.  

We should set up a call to talk through this further.

**Comment by abna-brasil** [comment]
In fact, we currently have a unique three-digit number project underway. But, as you know our process need to be kind of slow

**Comment by abna-brasil** [comment]
How can I configure YAP to work with our SIP?

**Comment by radius314** [comment]
Please join the slack channel and let's talk there.
