### ISSUE TITLE
Error - 12100

### ISSUE THREAD

**Issue by orscna** [bmlt-enabled/yap#415]
**Describe the bug**
Document parse failure
Twilio was unable to parse the provided XML Document.
Your TwiML document must be a valid XML Document, or Twilio will not be able to read your document. You can debug XML parsing errors by getting the response body in the debugger, and then using an online validation tool like the W3C Validation Service.
Possible Causes
There is a leading space, or an empty line, before the XML type header (i.e. <?xml version="1.0" encoding="UTF-8"?>)
The root <Response> element is missing
There is an unclosed element
There is an unquoted attribute
There is an improperly nested element
Possible Solutions
Make sure there is no extra space or line at the beginning of the file before the type header
Make sure your root element is <Response>
XML is case sensitive, make sure your start and end elements match case. (Twilio elements begin with a capital letter)
Make sure characters such as < > and & are escaped properly, as &lt; &gt; and &amp;.

Msg=&parserMessage=Error+on+line+11+of+document++%3A+XML+document+structures+must+start+and+end+within+the+same+entity.+&ErrorCode=12100&LogLevel=ERROR

**What version are you running?**
3.6.4

 <b>Fatal error</b>:  Uncaught Twilio\Exceptions\RestException: [HTTP 400] Unable to create record: The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers. in /home/bmltorscna/public_html/yap/vendor/twilio/sdk/src/Twilio/Version.php:85
Stack trace:

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/63311454/79139847-079be100-7d85-11ea-8f85-88834c095c7a.png)

**Additional context**
Is it because of a trial account?
I had all the RCM's at our regional meeting call the number. Overload on the server?
205-749-4702

**Comment by radius314** [comment]
Yap is not supported here on trial accounts.  Not sure if anybody else has experience with this.
