### ISSUE TITLE
override_service_body not bypassing search for meeting

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#416]
**Describe the bug**
When the helpline number is called Yap goes through all the options instead of routing to helpline volunteers.

**What version are you running?**
3.7.0

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
Set Twilio to hook to ?override_service_body_id=1098

**Expected behavior**
Route to helpline volunteers directly of the service body called out in config.php

**Screenshots**

**Additional context**

**Comment by radius314** [comment]
Can you give a specific reasoning as to why you believe this is not functioning?

**Comment by californiasteve** [comment]
Usually, when I would call in we would not get the choice to search for meetings. It would go directly to the helpline. Like the caller had pushed/said "1".  Almost like how you can bypass the helpline with the "input-method.php?Digits=2"

**Comment by radius314** [comment]
Ok I was not able to repro this on 3.7.0 configuration, meaning it's working as expected.  Are you using a Tomato service body ID?

**Comment by radius314** [comment]
Closing out, as this was determined to not be a bug.
