### ISSUE TITLE
Hamburger Menu not responding on mobile devices

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#419]
**Describe the bug**
The hamburger menu does not respond on a mobile device

**What version are you running?**
3.7.1

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
1. log on to Yap on mobile 
2. Click on the hamburger menu and nothing happens. It won't expand

**Expected behavior**
The menu should expand.

**Screenshots**

**Additional context**
Issue also affects desktop browsers if you shrink the window to invoke the hamburger menu 
![yap error](https://user-images.githubusercontent.com/29008815/81763836-7cdd0c00-9513-11ea-83e0-7f66194071ec.png)

**Comment by radius314** [comment]
able to repro, looking at this now

**Comment by radius314** [comment]
related to the jquery 3.5.0 upgrade.  rolling back to jquery 3.4.1 https://stackoverflow.com/questions/61176484/cannot-convert-object-to-primitive-value-error-in-react-application

**Comment by radius314** [comment]
fix coming in yap 3.7.3

**Comment by radius314** [comment]
3.7.3 is available https://github.com/bmlt-enabled/yap/releases/download/3.7.3/yap-3.7.3.zip

**Comment by brustar64** [comment]
Thanks very much! Can't believe how quickly you were able to fix and release this! 🙂
________________________________

**Comment by brustar64** [comment]
I've still got the issue after updating.

**Comment by radius314** [comment]
verified to be fixed on slack
