### ISSUE TITLE
500 error on releases

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#421]
I don't know if my server changed something or what but on siteground I'm getting 500 errors on setting up new yap instance. my setup method is as follows

1. `wget https://github.com/bmlt-enabled/yap/releases/download/3.7.2/yap-3.7.2.zip`
2. `unzip yap-3.7.2.zip`
3. hit url for setup wizard https://phoneline.xxxx.org/yap-3.7.2/
I then get this error

![Screen Shot 2020-06-14 at 3 56 17 PM](https://user-images.githubusercontent.com/34245618/84602756-a1503f00-ae57-11ea-89a6-fa4149107094.png)

to fix I ended up having to run the following command `find ./yap-3.7.2 -type d | xargs chmod 755 && find ./yap-3.7.2 -name '*.php' | xargs chmod 644`

this sets the permissions on directories and php files appropriately. we may want to add this to the build stage as is done on crouton here https://github.com/bmlt-enabled/crouton/blob/2c934debe987a92e52201b96cb5adaaee4554ec1/.travis.yml#L73 and root server here https://github.com/bmlt-enabled/bmlt-root-server/blob/0c637cf47382edfa394394b2f301dedadf6b4154/.travis.yml#L32

**Comment by radius314** [comment]
Can you validate this is present on 3.7.4 which is the latest version?

**Comment by pjaudiomv** [comment]
yes I checked 3.7.4 too

**Comment by radius314** [comment]
@pjaudiomv can you test the build? https://archives.bmlt.app/yap/yap-1605-003871d91585d572b16e26de438afeef68dc8c21.zip

**Comment by pjaudiomv** [comment]
that build worked :)
