### ISSUE TITLE
How to make hyperlinks in BMLT

### ISSUE THREAD

**Issue by SteveG-Gso** [bmlt-enabled/yap#437]
Greensboro Area - we can fill in the (Zoom) url information but it does not result in a hyperlink showing in the browser. We suspect it is a Word Press issue, plug in of some sort. Any input would be helpful. 

At the present time, no Zoom links exist because they cannot be created.

https://greensborona.org/meetings/

**Comment by radius314** [comment]
You must either tag the meeting with the format `VM` as a virtual meeting, or `HY` for Hybrid (both F2F and Virtual)

**Comment by radius314** [comment]
also this needs to be opened under crouton if you want further support.
