### ISSUE TITLE
Whenever the BMLT Format Code TC is used alone, have YAP respond with"Meeting is temporarily closed".

### ISSUE THREAD

**Issue by Brooklynmaureen** [bmlt-enabled/yap#442]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I think it would be a good feature if [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Mention any other of the Github handles that are also interested in this enhancement**

**Additional context**

**Comment by radius314** [comment]
this seems like a reasonable request.  i have to think about how to implement it

**Comment by radius314** [comment]
Currently TC meetings are excluded, with no option to display them.   The thought process here is that the target audience for the phoneline would be folks not familiar with the existing set of meetings.  I'm not sure how to proceed on this.

**Comment by radius314** [comment]
https://github.com/bmlt-enabled/yap/pull/454

**Comment by Brooklynmaureen** [comment]
Hi Danny, 
Thank you for replying, but I am still receiving these TC meetings in my YAP response.    I just called the helpline and selected number 1, meeting  information. Then selected meetings by city or county, I then spoke Brooklyn NY.  YAP Replied with the top 5 meetings and four of the meetings had the TC format used, yet YAP replied that the meetings were open today in Brooklyn NY.    I also called the helpline and selected meetings by zip code and 4 of the 5 meetings returned had the TC Format code used.   Could this be I'm missing an update in the version of BMLT we are using?  thanks, Maureen

**Comment by Brooklynmaureen** [comment]
Note:   I have only one meeting physically open today in Brooklyn NY, zip code is 11201   Free At Last,  Maureen

**Comment by radius314** [comment]
What version are you on?

**Comment by Brooklynmaureen** [comment]
That's a good question.  I have no idea.   I do not update our web.  I will have to ask Lou, who has taken the reins form Chris Marshall.  What is the current version?   Maureen

**Comment by radius314** [comment]
The most recent version is always listed here:

https://github.com/bmlt-enabled/yap/releases/latest

—Danny

**Comment by Brooklynmaureen** [comment]
thank you.

**Comment by radius314** [comment]
If you go into your Twilio account, you will see your call webhook under the phone number.  You can take the URL and replace the PHP page with upgrade-advisor.php and paste that in your web browser to get the version.  

Example:

https://example.org/input-method.php?Digits=2

would be

https://example.org/upgrade-advisor.php

**Comment by Brooklynmaureen** [comment]
Danny, Are all BMLT changes made this way, in our Twilio account?         I emailed these instructions to Lou, but this seems like something I can do.

**Comment by radius314** [comment]
Twilio has nothing to do with BMLT changes.  It’s the call circuits that connect to Yap.

**Comment by Brooklynmaureen** [comment]
Danny, I'm in my Twilio account.  Can you baby step me through this.   I need the senior citizen instructions LOL.   What I am seeing is the dashboard, do I select settings?  I do not see the call webhook under the phone number?

**Comment by radius314** [comment]
You will need to find someone who is a litle more technical to help you at this point.  This is not the right forum to ask for this level of support.  Perhaps the facebook group is a better place.  

With regards to the specific request, TC meetings are filtered out automatically (as of version 3.7.0) if they are not tagged as VM in the BMLT.

I am implementing a feature that would allow someone to include descriptions for formats if they should choose to (for example indicating a meeting is meeting virtually or is a hybrid).

**Comment by Brooklynmaureen** [comment]
thank you
