### ISSUE TITLE
Blank webpage when using static $sms_summary_page = true;

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/yap#449]
I just upgraded to 3.8.0
I've been using the summary page true option since it became available.  
It had been a while since I 'tested' yap so I'm not sure if it had stopped working before my upgrade or not.
I get a summary link in text, but the summary page is a blank page when I click it.  This is the page it's trying to open: https://xxx/yap/endpoints/msr/35.0938483/-89.9346659

I changed to false on the summary page and get the meetings

the yap number is xxx (I'm using an iphone XI Pro Max

**Comment by radius314** [comment]
I have identified the issue and working on a fix now.

**Comment by radius314** [comment]
Can you try this build?  https://archives.bmlt.app/yap/yap-1707-db3b226dbd7708fd074eef4cf27c65bcc3fa4a92.zip

**Comment by lucy12187** [comment]
trying now.

**Comment by lucy12187** [comment]
It's working now!

**Comment by radius314** [comment]
Awesome, thanks for finding this and reporting it.  Cutting 3.8.1 now.

**Comment by tempsaint** [comment]
I just upgraded to 3.9.0 and I'm having the same issue.

**Comment by radius314** [comment]
please provide specific repro steps.

**Comment by tempsaint** [comment]
Upgraded my demo instance and called in for a meeting search. Pressed 1 for meeting results to be texted to me. I received the link but the summary page was empty. Will PM you the number.

**Comment by radius314** [comment]
thanks.
