### ISSUE TITLE
Reporting not working under 3.8.1

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#450]
**Describe the bug**
Map details or reports work at all in 3.8.1.

**What version are you running?**
3.8.1

**Did this happen on prior versions to the one you are running?**
Yes 3.7.1.4
**To Reproduce**
1. Go to reports select a service body
2. Click on any of the buttons to export and nothing happens

**Expected behavior**
reports should load on selection and be exportable.

**Screenshots**
![image](https://user-images.githubusercontent.com/29008815/88282523-14898280-cd2d-11ea-8134-bef5e3baca24.png)

**Additional context**

**Comment by radius314** [comment]
are you using HTTPS?

**Comment by brustar64** [comment]
Hi Danny,
Sorry for the late response.  It seems that its all working again now.
Very confusing.  I haven't done anything different.  Maybe it was cache....
