### ISSUE TITLE
Configuration Dropdown not populating with options.

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#451]
**Describe the bug**
When in the yap admin if i go to configure a service body the Configuration Dropdown is not populating with options. I tested this on SEZF and NERNA servers running 3.8.1

**What version are you running?**
3.8.1

**Did this happen on prior versions to the one you are running?**
not sure about 3.8.0 but it def didn't happen on 3.7.5.

**To Reproduce**
In the yap admin, go to configure a service body and try to add a configuration option.

**Expected behavior**
The configuration options are available to edit.

**Screenshots**
![Screen Shot 2020-07-25 at 12 35 50 PM](https://user-images.githubusercontent.com/34245618/88461658-63413480-ce73-11ea-8034-d247b71b2b39.png)

**Additional context**
If setting were set previously they still show up and work, just are not able to set new ones.

**Comment by radius314** [comment]
will be released in 3.8.2
