### ISSUE TITLE
Volunteer reminder - SMS or Email

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#468]
**Is your feature request related to a problem? Please describe.**
One of our areas organises volunteers on a one day each per month basis.  As an administrative practice the diligent coordinator contacts each volunteer before they are enabled to ensure that they can serve on their shift.  If they are unable to meet their commitment an alternative volunteer is programmed in their stead.

**Describe the solution you'd like**
I would like to enable a volunteer reminder which sends an SMS or email to volunteers 24 hours before their shift starts asking them to confirm with their coordinator that they are in fact available so the coordinator can pre-emptively program an alternative volunteer.  Currently there is significant overhead for the Coordinator and I'd really like to enable a feature like this to put the responsibility back on the volunteer.

**Describe alternatives you've considered**
Considered organising a calendar reminder which sends a notification to the scheduled volunteer but I'd really like to enable this in Yap/Twilio if possible so a second calendar would not need to be managed.

**Comment by radius314** [comment]
This feature is very specific and unique to your community.  What could be provided is an API endpoint that would allow you to write your own application that does this.  However, you'd have to get a developer to write it for you.
