### ISSUE TITLE
Disable BMLT ?

### ISSUE THREAD

**Issue by SteveG-Gso** [bmlt-enabled/yap#472]
Due to Covid - 19 the BMLT is not outputting correct meeting information to Help Line callers.

Obviously the meeting schedule is changing often.

1)How can the BMLT be disabled ? 
2)Provide the caller the option of being patched to a help line volunteer only ? 
3)Provide the caller a pre recorded message to visit a website and / or visit the website ? 
4) Provide all callers a text message of the website automatically or by request ?  Example of pre - recorded message: "Welcome to the Greensboro Area of Narcotics Anonymous  A text message with our website and meeting information is being sent to you at this time. If you need to speak to a Help Line volunteer - Recovering Addict press 7 at this time"

If there are any other suggestions for this environment please note them.

**Comment by radius314** [comment]
1) It's not clear from this question what your goal is.  The BMLT is a core piece of Yap and none of it will really work without a BMLT server.
2) Yes this is possible, but requires the BMLT for call routing.
3) I'm not sure the point of that, the BMLT is intended to keep meeting list information accurate.  Are you redirecting callers back to the website to see BMLT information?  If that's the case, Yap is only returning exactly what would be seen on a webpage.
4) Not possible.

**Comment by SteveG-Gso** [comment]
I have viewed the Twin Cities Area website below. I called their help line. At this time it allows for the caller to leave a message only. No BMLT output to the caller. I'm assuming it's because 1) Pre Covid info is not accurate 2) BMLT would provide a caller with Pre Covid and current Zoom meeting information that are in conflict.

To clarify, I agree that the the BMLT should be maintained (on the server) for the purpose it was created.

I would like to have the Help Line output accurate In Person and Virtual - Zoom  meeting information. I'm missing how this can be accomplished on the Help Line ? To provide accurate meeting information to the caller in need.


http://tcana.org/find-a-meeting/

**Comment by radius314** [comment]
This conversation is probably better had with your local webservant in the North Carolina Region (email webservant -at- ncregion-na.org.  This is a forum for development changes to Yap.  The scope of these questions seems a bit premature for an enhancement request.

**Comment by SteveG-Gso** [comment]
Ok thank you.
