### ISSUE TITLE
Unable to log into YAP - Server Timeout Error 500

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#485]
**Describe the bug**
Login attempts simply time out.

**What version are you running?**
YAP 3.9.5  BMLT 2.15.1 (tried upgrading from 3.9.3 to resolve the issue but it still exists)

**Did this happen on prior versions to the one you are running?**
Yes 3.9.3
**To Reproduce**
1. enter credentials at YAP admin page https://na.org.au/yap3/admin.php 
2. Press enter
3. server times out (I can see a cookies in the backend from users who've attempted to login)

**Expected behavior**
Login should work

**Screenshots**
![image](https://user-images.githubusercontent.com/29008815/95801491-d1dcb280-0d3d-11eb-8475-ede88e252432.png)

**Additional context**
To me this feels a bit like the same error we've been getting when we try and run reports.
That's the only thing that's caused timeouts on our YAP instance.

**Comment by radius314** [comment]
we also know about a bug with the caching layer that will be fixed soon.

this is known to cause DB issues.

try running `truncate table cache;`  on your yap database

**Comment by brustar64** [comment]
That didn't seem to make any difference.
![image](https://user-images.githubusercontent.com/29008815/95910537-9399ce80-0de3-11eb-8f98-e6ec1e5ac2e1.png)

**Comment by brustar64** [comment]
We still cannot login.
We have tried a BMLT database restore back to 8 Oct (the last change to users that was made)
We have not tried a YAP Database restore.
These timeouts feel very much like the same timeouts we get when we try to invoke reporting.  It just times out.

**Comment by radius314** [comment]
To deal with the incident, it was recommended that the user switches to native Yap users.  After further investigation, it was discovered that this was related to the hosting provider blocking at a network level HTTP POST requests to the following two URIs.

```
%s/local_server/server_admin/xml.php?admin_action=get_permissions
%s/local_server/server_admin/xml.php?admin_action=logout
```

This code was introduced in Yap 2.0.0-beta1 and has largely not been changed (ref: https://github.com/bmlt-enabled/yap/commit/389a31a3324950491703eb297cd099d91297cd82).

HTTP POST is not actually required to enable this feature to work, so it was suggested to use a patched version of Yap with POST disabled.  This cleared up the issue.

Yap 3.9.6 will be introducing file-less cookie storage for BMLT authenticated users.  As part of that change HTTP POST will be disabled as seen in this commit: https://github.com/bmlt-enabled/yap/commit/ceacef77bac0dd61b7f429ee819ec722a3dec7f6
