### ISSUE TITLE
Unexpected token < in JSON at position 0 at the REPORTS

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#502]
I just searched my database and found no < characters other than the cache table on all the JFT queries...

Here's my console log when I click around on Reports.  The chart at the top loads, it's the detail stuff on the lower half that has an ERROR

yap-reports.min.js:1 Ajax Load Error - Invalid JSON returned SyntaxError: Unexpected token < in JSON at position 0
(anonymous) @ yap-reports.min.js:1
Promise.catch (async)
(anonymous) @ yap-reports.min.js:1
Promise.then (async)
(anonymous) @ yap-reports.min.js:1
m.defaultLoaderPromise @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
m.sendRequest @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O._getRemotePage @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.trigger @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.setPage @ yap-reports.min.js:1
u._loadInitialData @ yap-reports.min.js:1
u._create @ yap-reports.min.js:1
t @ yap-reports.min.js:1
initReports @ yap.min.js:1
(anonymous) @ reports.php:344
h @ yap.min.js:1
c @ yap.min.js:1
setTimeout (async)
(anonymous) @ yap.min.js:1
l @ yap.min.js:1
fireWith @ yap.min.js:1
fire @ yap.min.js:1
l @ yap.min.js:1
fireWith @ yap.min.js:1
ready @ yap.min.js:1
W @ yap.min.js:1
yap-reports.min.js:1 Ajax Load Error:  SyntaxError: Unexpected token < in JSON at position 0
(anonymous) @ yap-reports.min.js:1
Promise.catch (async)
(anonymous) @ yap-reports.min.js:1
m.sendRequest @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O._getRemotePage @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.trigger @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.setPage @ yap-reports.min.js:1
u._loadInitialData @ yap-reports.min.js:1
u._create @ yap-reports.min.js:1
t @ yap-reports.min.js:1
initReports @ yap.min.js:1
(anonymous) @ reports.php:344
h @ yap.min.js:1
c @ yap.min.js:1
setTimeout (async)
(anonymous) @ yap.min.js:1
l @ yap.min.js:1
fireWith @ yap.min.js:1
fire @ yap.min.js:1
l @ yap.min.js:1
fireWith @ yap.min.js:1
ready @ yap.min.js:1
W @ yap.min.js:1
yap-reports.min.js:1 Ajax Load Error - Invalid JSON returned SyntaxError: Unexpected token < in JSON at position 0
(anonymous) @ yap-reports.min.js:1
Promise.catch (async)
(anonymous) @ yap-reports.min.js:1
Promise.then (async)
(anonymous) @ yap-reports.min.js:1
m.defaultLoaderPromise @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
m.sendRequest @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O._getRemotePage @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.trigger @ yap-reports.min.js:1
(anonymous) @ yap-reports.min.js:1
O.setPage @ yap-reports.min.js:1
u._setData @ yap-reports.min.js:1
u.setData @ yap-reports.min.js:1
updateCallRecords @ yap.min.js:1
updateAllReports @ yap.min.js:1
(anonymous) @ yap.min.js:1
dispatch @ yap.min.js:1
g.handle @ yap.min.js:1
ListPicker._handleMouseUp
yap-reports.min.js:1 Ajax Load Error:  SyntaxError: Unexpected token < in JSON at position 0

**Comment by gutterwall** [comment]
Yap (3.9.4), 
BMLT 2.15.6

**Comment by gutterwall** [comment]
16633-16639 url=cdr_api.php?service_body_id=0&page=1&size=50&recurse=false
is one of the json ajax calls failing with the < in JSON at position 0 of the response.

which calls:
https://metrorichna.org/yap/admin/cdr_api.php?service_body_id=0&page=1&size=50&recurse=false

Which gives the mySQL Collation error?  I guess I need to redo the database?  Loose my data?

<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '=' in /homepages/4/d330097172/htdocs/yap/lib/Database.php:73
Stack trace:
#0 /homepages/4/d330097172/htdocs/yap/lib/Database.php(73): PDOStatement-&gt;execute()
#1 /homepages/4/d330097172/htdocs/yap/endpoints/_includes/queries.php(79): Database-&gt;execute()
#2 /homepages/4/d330097172/htdocs/yap/endpoints/_includes/queries.php(88): quickExec('INSERT INTO `ca...')
#3 /homepages/4/d330097172/htdocs/yap/endpoints/_includes/functions.php(1988): getCallRecords(Array, 1, 50)
#4 /homepages/4/d330097172/htdocs/yap/admin/cdr_api.php(4): adjustedCallRecords(Array, 1, 50)
#5 {main}
  thrown in <b>/homepages/4/d330097172/htdocs/yap/lib/Database.php</b> on line <b>73</b><br />

**Comment by gutterwall** [comment]
looks like 
latin1_swedish_ci 
alerts
cache
conference_participants
config
flags
metrics
migrations
records
records_events
users

and latin1_general_ci
cache_records_conference_participants
cache_records_records_conference_participants

Do I just delete/recreate these tables or something?

**Comment by gutterwall** [comment]
I created a new database, and it's blank, but it works.  I am not sure the best method to import the historical data, but I just pulled it all out before I did the dump, so I guess I am good. Lets close this.

Was there a change in the database collation creation of differnet versions of upgrades?

**Comment by radius314** [comment]
Database creation + collation is not controlled or done by Yap.  The `CHARSET` is latin1 and hasn't changed.

**Comment by gutterwall** [comment]
Ok well odd sweden suddenly got involved. It must be my ISP since they got
bought and transformed ... Thanks!

**Comment by jbraswell** [comment]
For future reference, I think mysql allows you to alter the table collation and charset with an `ALTER TABLE` statement.
