### ISSUE TITLE
Initial configuration generator not working

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#503]
Fresh install of Yap 3.9.9. Created a blank mySQL database on Linux hosted site. Gave db user full rights. Browsed to yap folder on website, screen came up asking for root server, twilio info, database info etc. Filled it all out and clicked "Generate Config". The only thing that appears in the screen is "<?php ", then "waiting for config.php to exist" in red. There is nothing generated to put in the config file. No errors - just sits this way forever. Tried with Firefox and Chrome, same thing.

**Comment by pjaudiomv** [comment]
I think holly g reported the same thing on the book

**Comment by Redguy1959** [comment]
Yes, she asked me if there was a way to get a response so I posted on Github.

**Comment by radius314** [comment]
Can you include a screenshot?  Are there any errors from the javascript console?

**Comment by Redguy1959** [comment]
Hey Danny,

we got Yap installed by manually creating the config file and its contents. The installer just sat there and never came back with any contents to put in the file.
Just now I renamed the config.php to config-old.php to force the installer page up again, filled in the fields, and this time it worked and came back with content for the config.php file.
If I have time I will try on a fresh install to see if I can replicate the issue, but since we are good now and if nobody else has reported the same issue you can just close it.

Happy Holidays!

--Paul R.

**Comment by radius314** [comment]
Thanks for the update.  Glad you got it working.
