### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by kramer123** [bmlt-enabled/yap#504]
**Describe the issue**
Unable to install

going to the url   I get a 500 server error (no install page showing)
php 7.4  probably a setting  wrong ? 

**What version am I  running?**
4.0.0-beta4.zip

server is Linux shared hosting 

thanks

**Comment by radius314** [comment]
can you add a file called `.env` in the root of the folder and add the following to it?  `APP_DEBUG=true`

Reload the page, you should get a more details message.

**Comment by kramer123** [comment]
thanks

**Comment by radius314** [comment]
did this work?

**Comment by kramer123** [comment]
sorry old question,  my area is installing Yap on their server.  so I'm not testing it.   Thanks
