### ISSUE TITLE
Logout when loading a group without selecting a body first

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#505]
**Describe the bug**
I get logged out of yap 

**What version are you running?**
3.9.8

**Did this happen on prior versions to the one you are running?**
Unsure

**To Reproduce**
1. Go to https://bmlt.sezf.org/zonal-yap/admin/groups.php
2. Click on Load (do not select a body first)
3. Sent back to login screen with "Not Authorized" message

**Expected behavior**
A pop up that says "Select a service body"

**Additional context**
Doing this from frna-admin and frna_admin accounts

**Comment by radius314** [comment]
able to repro, thanks

**Comment by radius314** [comment]
will be fixed in version 4.0.0
