### ISSUE TITLE
SMS to volunteers not delivering when texting helpline

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#508]
**Describe the bug**
Trying to text a volunteer in Palm Coast Area with believed to be good setup for SMS handling and SMS-enabled, on-shift volunteers. Have tried zip codes and an assortment of locations with 'talk' keyword in front and getting the request received message followed by "could not find a volunteer for the location, please retry your request."

**What version are you running?**
3.9.8

**Did this happen on prior versions to the one you are running?**
unknown

**To Reproduce**
1. enable Volunteer and SMS handling for an area
2. enable a 24/7 PHONE,SMS volunteer
3. text 'talk' + location 
4. Receive text that indicates an exception was thrown.

**Expected behavior**
Receive sms alerting that someone is requesting help (my own number is the volunteer number expected to be contacted)

**Screenshots**
![image](https://user-images.githubusercontent.com/20930402/107836876-9fcf7180-6d6c-11eb-8031-2f71f9977fcc.png)
![image](https://user-images.githubusercontent.com/20930402/107836856-8b8b7480-6d6c-11eb-83e2-68f4878dc9f5.png)
![image](https://user-images.githubusercontent.com/20930402/107836998-0c4a7080-6d6d-11eb-8fa5-6803ef3ba12e.png)

**Additional context**
- the Safety measure of sending to primary contact number does work, if that field is set! I'll be opening another ticket in relation to this as the field is only available to specific call strategies, but SMS depends on this too.
- Tried with both SMS strategies: random and blast. both had same effect
- Tried "West Palm Beach, Florida" location from test Florida Region number 5619336969, test Palm Coast Area number 5919442069 (where the volunteers are set), and even NC State Number. all three return this issue.
- Tried "Raleigh, NC" location from NC State line and got no response at all. No received message, no BMLT lookup, no _"you cant text this number"_ message. Maybe NC disabled this completely? There should probably be a denial response built in when its not in use...

**Analysis**
So without being a yap/PHP expert or having a proper setup to debug, my analysis says the issue is in the `getHelplineVolunteer()` call in helpline-sms.php:20 when `$phone_numbers` is created. The function call seems to always be returning `SpecialPhoneNumber::UNKNOWN` for some reason, which is a problem. Thats the root issue. This is compounded by a second issue when `primary_contact_number` is not set. In that case, there is no failover number and twilio cant deliever a message to $phone_number, which would equate to be the default value of `$serviceBodyCallHandling->primary_contact_number` (ie, `SpecialPhoneNumber::UNKNOWN`) set in functions.php:299. This is a second issue that should be addressed, in the event no one enters a primary contact number or a CALL routing strategy is not used that exposes the PCN field needed for SMS functionality/safeguard. I'll open a separate ticket for that though. Back to the primary issue though, considering in my case there is one (should be) good SMS volunteer, `$phone_number` should not be `SpecialPhoneNumber::UNKNOWN` in the first place. Diving into the helper `getHelplineVolunteer()`, I did also note that the strategies checked were for calling and not SMS. The final `else` and catching a `NoVolunteersException` both return `Volunteer(SpecialPhoneNumber::UNKNOWN)`, so its a little harder for me to say which case is happening without more in depth knowledge, a proper debug setup, or a Yap lab I can screw with.

**Comment by alanb2718** [comment]
Verified that this isn't working in version 4.0.0-beta5 either.

**Comment by dgershman** [comment]
Will be Yap 4.0.0 Beta 6

**Comment by dgershman** [comment]
yap-4.0.0 was released.
