### ISSUE TITLE
Australian Postcodes often failing to return search results or return incorrect results

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#510]
**Describe the bug**
There are many Australian post codes which fail.
EG 2010 (Darlinghurst fails on Twilio but if we search on crouton it lands us in Kansas), 2015 Surrey Hills (fails on yap but sends us to Junction Hill in the USA on Crouton) 5000 (Adelaide - returns Sydney meetings), 3000 Melbourne (errors out), 3005 Docklands Melbourne (error's out) there are many others that don't work correctly. 
There are also many that do work correctly.  I have 

**What version are you running?**
3.9.9

**Did this happen on prior versions to the one you are running?**
It did but its really quite bad now with many post codes failing throughout Australia.
The post codes work if you add the state abbreviation after the postcode.

**To Reproduce**
Send 5000 (Adelaide) to our Twilio number and it returns Sydney meetings (600 klms away)

**Expected behavior**
Australian postcodes return results that correspond to the actual postcodes we enter.

**Comment by radius314** [comment]
I thought that you disabled postcodes due to their unreliability with the google maps API?

**Comment by radius314** [comment]
ref: https://github.com/bmlt-enabled/yap/issues/231

**Comment by brustar64** [comment]
We disabled them on the phone line but there's been a whole bunch of NA business cards and posters and TV CSA's produced that say enter your postcode.  🙁


________________________________

**Comment by radius314** [comment]
We determined that the Google Maps API was unreliable.  I'm sorry there
isn't anything I can do about that.

**Comment by radius314** [comment]
https://aceik.com.au/2018/09/25/geocoding-australian-postcodes/

**Comment by radius314** [comment]
If you want to do some research you are more than welcome.  

http://maps.google.com/maps/api/geocode/json?components=country:AU%7Cpostal_code:2340&sensor=false&api_key=

**Comment by brustar64** [comment]
I'm actually in the process of trying to verify the ownership of our site with a TXT record from the Google Developer Console added to DNS - we recently migrated our domain registrar but the DNS doesn't allow me to add TXT (or any other records).  I've logged a support call for that.
________________________________

**Comment by brustar64** [comment]
When we search for the failing postcodes on Crouton searchable map it returns a URL which produces the following message

({"meetings":{},"formats":[]});


________________________________

**Comment by brustar64** [comment]
How would we add a PostcodToState lookup for Australia or alteratively make a call to the Australia post API instead of Google?
This would probably require a forked development of the BMLT/Crouton/YAP for Australia right?

I think it would make more sense do a reprint of posters/business cards (other published information) to tell people to use postcode + State/Territory...
________________________________

**Comment by brustar64** [comment]
FYI here's the Australia Post API
https://auspost.com.au/developers/docs/api/locations/overview
________________________________

**Comment by radius314** [comment]
This is super low priority for me, I would suggest that you work out
alternative plans given that you were already aware of the shortcomings of
the Google Maps API for Australia with Postal Codes.

**Comment by brustar64** [comment]
I can't use http://maps.google.com/maps/api/geocode/json?components=country:AU%7Cpostal_code:2340&sensor=false&api_key= with our API key because its restricted 🙁
________________________________

**Comment by radius314** [comment]
You should be able to generate a new API key temporarily w/o restrictions (do not share it).

**Comment by radius314** [comment]
Per prior discovery, there is no ability for us to make the Google Maps API better.  We had determined that using Postal Codes for Austrailia was inaccurate and we had a shared understanding that you should disable the feature.

**Comment by radius314** [comment]
If you do further research and find some better way to use the API, we could consider making changes to support that.
