### ISSUE TITLE
metrics working only at area level

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#511]
the metrics dont appear to be working at a region level, for some service bodies it appears they stopped working in november and september. i am on 3.9.9 for both servers however i know this was happening on 3.9.5 as well

<img width="1207" alt="Screen Shot 2021-02-21 at 8 48 50 PM" src="https://user-images.githubusercontent.com/34245618/108647409-9a69d980-7486-11eb-926b-c2a272faa11d.png">
<img width="1167" alt="Screen Shot 2021-02-21 at 8 48 35 PM" src="https://user-images.githubusercontent.com/34245618/108647411-9b027000-7486-11eb-9135-9552a22716e8.png">
<img width="1166" alt="Screen Shot 2021-02-21 at 8 44 53 PM" src="https://user-images.githubusercontent.com/34245618/108647413-9b027000-7486-11eb-8dd4-af6644f7d9c7.png">
<img width="1174" alt="Screen Shot 2021-02-21 at 8 44 47 PM" src="https://user-images.githubusercontent.com/34245618/108647414-9b027000-7486-11eb-84b8-d1e9915e626c.png">

**Comment by dgershman** [comment]
ref: https://github.com/bmlt-enabled/yap/issues/365

**Comment by dgershman** [comment]
Will be delivered in Yap 4.0.0-beta6

![image](https://user-images.githubusercontent.com/1850811/130246692-044c795f-25cf-4dc6-9032-6700c88b60e7.png)

**Comment by dgershman** [comment]
@pjaudiomv can you verify that this is fixed on beta6?

**Comment by pjaudiomv** [comment]
yes clicking recursive now works

**Comment by dgershman** [comment]
yap-4.0.0 was released.
