### ISSUE TITLE
fallback.php redirect to volunteer group

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#515]
The solution found for fallback works however a lot of calls come through to the fallback number of a single volunteer. 

If we could configure fallback to an existing or perhaps new group of volunteers rather than an an individual number that would ease the burden against the single volunteer

**Describe alternatives you've considered**
I guess we could manually update the fallback number periodically.

@radius314

**Comment by radius314** [comment]
Why are there so many requests for the fallback?

**Comment by radius314** [comment]
Follow along with #516.

**Comment by brustar64** [comment]
If people mispronounce, have background noise or day a town more than 100klms it seems to go to fallback.


Bruce

________________________________

**Comment by radius314** [comment]
Ok, we should address those issues, this is not the intention of fallback.php.

**Comment by brustar64** [comment]
Thanks Danny,

I'm fairly sure you have developer access to our Twilio console.
if you search for calls to 61411607551 you can get a range of examples where it was redirected.

The only ones which show up with logs are the non-anonymous ones.
You have to go back through the parent call SID.

Yours in service
Bruce
________________________________
