### ISSUE TITLE
Reduce number of prompts

### ISSUE THREAD

**Issue by prbrian** [bmlt-enabled/yap#519]
Our Region would like the option of reducing the amount of prompts. For example, we’d like to remove “press 1 to search for meetings by city”.

**Comment by radius314** [comment]
How you would envision finding meetings would work then?

**Comment by prbrian** [comment]
It would skip right to “for ontario press 1, for manitoba press 2.” And then “please say the name of the city”

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org

**Comment by radius314** [comment]
I see.  How is this reducing the number of prompts?

**Comment by prbrian** [comment]
Because the first prompt it gives us is “to search by city press 1”. So if we eliminate that, it will only have 2 prompts instead of 3. Our test number is (647) 360-9350 if you’d like to take a listen.

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org

**Comment by jbraswell** [comment]
I'm currently scrubbing in as the admin for this server.

They've already disabled the zip code prompt, so it's only asking the caller if they want to search by city. Since searching by city is now the only possible option, the whole prompt is redundant. They'd just like to eliminate the redundant prompt by setting it to always search by city.

**Comment by radius314** [comment]
If you want to aIf you want to provide a list of pre-populated provinces you can do that with this setting.  

https://bmlt.app/yap/#stateprovincelookup

**Comment by jbraswell** [comment]
Thanks. This specific request is not to ask the user to press 1 to search by city, but instead to skip right to asking for the name of the city.

**Comment by radius314** [comment]
> Thanks. This specific request is not to ask the user to press 1 to search by city, but instead to skip right to asking for the name of the city.

Cool, that makes sense.

**Comment by prbrian** [comment]
Exactly. Sorry guys. Thanks for clarifying my thoughts 😬

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org

**Comment by radius314** [comment]
Will be released in Yap 4.0.0

**Comment by prbrian** [comment]
Thanks Danny.

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org

**Comment by dgershman** [comment]
yap-4.0.0 was released.

**Comment by prbrian** [comment]
Thank you!

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org
