### ISSUE TITLE
Nothing happen after the greeting message has been played

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/yap#521]
**Describe the bug**
If I enable our own-made greeting message, the audio-file play when I call the helpline phone but anything will process after and it hang-up after 20 sec of silence.

Claude St-Jean
Quebec IT Chairperson

**What version are you running?**
v3.9.7

**Did this happen on prior versions to the one you are running?**
not in used

**To Reproduce**
1. I insert the snippet in the config.php file: [static $en_US_greeting = "https://csr.naquebec.org/wp-content/uploads/2021/05/help-line-anglais.mp3"; ]
2. I call our helpline # 18555446362 and the message is playing and nothing is made after the message and it hangup after 20 sec.

**Expected behavior**
It suppose to reach one of available volunteers and if not, go to the voicemail.
**Screenshots**
not applicable
**Additional context**
I attach to this message the config file and the Twilio bug message

2021-06-01 17:15:06-04:002021-06-01 17:15:33-04:0027+18193182696+18555446362
2021-06-01 17:15:36-04:00Volunteer Answered but Caller HungupRégion de Québec [CSRQ] (32){"to_number":"+14383922476"}
2021-06-01 17:15:33-04:00Caller HungupRégion de Québec [CSRQ] (32){}
2021-06-01 17:15:27-04:00Volunteer DialedRégion de Québec [CSRQ] (32){"to_number":"4383922476"}
2021-06-01 17:15:26-04:00Caller Waiting for VolunteerRégion de Québec [CSRQ] (32){}
2021-06-01 17:15:19-04:00Volunteer SearchRégion de Québec [CSRQ] (32){}
[Twilio Cloud Communications _ Web Service API for building Voice and SMS Applications.pdf](https://github.com/bmlt-enabled/yap/files/6580638/Twilio.Cloud.Communications._.Web.Service.API.for.building.Voice.and.SMS.Applications.pdf)

[config.docx](https://github.com/bmlt-enabled/yap/files/6580671/config.docx)

**Comment by radius314** [comment]
When you record your audio you need to include what buttons to press.  Here is a sample audio file from another helpline system that does the same thing.  https://crossroadsarea.org/wp-content/uploads/9/2018/08/crossroads_v4_greeting.mp3
