### ISSUE TITLE
Options on gender selection

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#523]
We are having the discussion to move to Yap in New Jersey. Our Regions have a long history of "men with the men and women with the women". We note that the current Yap allows including "press 1 to speak to a man, press 2 to speak to a woman" or leaving this menu out.

* A motion was put forth to ask the developers of Yap if they would be willing to add a 3rd "no preference" option to the optional gender selection menu, so it would play "press 1 to speak to a man, press 2 to speak to a woman, press 3 for no preference".

**Comment by radius314** [comment]
I see no issue with adding this feature.

**Comment by dgershman** [comment]
This will be yap 4.0.0-beta8
