### ISSUE TITLE
Call as helpline security and advancement

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#527]
Two parts related to the same feature:

1) The ability to call as the helpline (option 9) should be restricted to people marked as responders or the Primary Contact Number. This can be easily abused without proper security. 

2) When a call is missed (with/without VM), it'd be super cool for Responders/PCN to get an SMS with a link that will have Yap call them and then call the missed caller (as the helpline Caller ID for both). This avoids the responder/PCN having to write down the number someway and then call back as the helpline and manually enter the number to call.

**Comment by dgershman** [comment]
I been thinking through this, and I have a couple of ideas:

1) Each call would get a unique 6 digit pin stored in the database along with the cal record.
2) When a call comes in, you get a text message with the full number and the pin in a string that you can use to re-dial.  Including the number for Dialback.  Example would be +12125551212,,,9,,,123456#.  
3) Dialback would have one additional security check which would be to determine if the person calling back is able to based on whether the number is registered with the current volunteer list.

**Comment by alanb2718** [comment]
This would work.  One issue is that you would need to get a text message back to be able to return a voicemail, and right now yap doesn't send a text if the volunteer is not taking calls at the time it comes in.  For example, I am not on the schedule to take calls in the middle of the night, so I don't get any notification currently if there is a voicemail left then; but I'd certainly be willing to call such a person back during the day if someone else hasn't done it already.  (Right now I do this by periodically manually checking for voicemails.)

Here are two simpler designs:

1. The UI lets a service body set a 6 digit pin for calling back.  This can be changed at any time, but is good for returning any call.  It could be included in the text message as above, but you could also return a call without it if you know the pin.
2. Only people on the current volunteer list can return calls, based on the number they are calling from.

Neither of these is as secure as the above design, but that seems ok -- this functionality should have some protection, but it doesn't need protection at the level of a complex password or two-factor authentication.

But ... the more secure design would work too, and if it were implemented I'd sign up for 24/7 shifts, letting my phone's "do not disturb" mode take care of the 3am callers.

**Comment by dgershman** [comment]
The issue with calling someone back during a time when you are not on the schedule has nothing to do with dial back.  It sounds like you are asking for something completely different and wanting it as part of the dial back ask.

**Comment by alanb2718** [comment]
If I'm a responder, and am not currently on the schedule, I don't get a text when someone leaves a voicemail.  So with the design as described, I wouldn't know the unique 6 digit pin.  Or are you proposing to change yap so that it still sends a text to responders even if they aren't on the schedule?

**Comment by dgershman** [comment]
Most service bodies do not use dial back.  The scenario you are suggesting exists for any call on any service body.  When considering changes in Yap, I'm thinking about most use cases.  So if you want to have volunteers that aren't on call respond, then this is a separate feature request.

**Comment by dgershman** [comment]
I also want to point out not only would you not know the pin, but you wouldn't know the number to call back.

**Comment by pjaudiomv** [comment]
I think option 3 would be the easiest MVP, just only allow dial back if the number exists on the volunteer list or responder regardless of schedule time

**Comment by dgershman** [comment]
The challenge with this is that we don't which service body was called easily, there could be multiple entries across multiple service bodies.  We'd have to look across all schedules across the entire instance.

**Comment by alanb2718** [comment]
Regarding:

> I also want to point out not only would you not know the pin, but you wouldn't know the number to call back.

I just look on the voicemail tab on the yap admin website and get the number from there.  But this suggests a solution if you do want to have a unique pin for each voicemail: include the pin in the information on the voicemail tab, as well as in the SMS that yap sends.

**Comment by dgershman** [comment]
Yes but this assumes that you are someone who has credentials to the admin interface.  Volunteers do not have login capability.

**Comment by alanb2718** [comment]
Good point.  But if you do want a unique pin for each voicemail, how about including it in the information in the voicemail tab in any case?  That would mean the admin could still deal with the voicemail if there were some issue with the SMS.

**Comment by dgershman** [comment]
Putting the pin in the voicemail section is fairly trivial to add to this.

**Comment by dgershman** [comment]
I need to think through this a little more.  Not all missed calls have voicemail associated.

**Comment by alanb2718** [comment]
Can I bubble this back up on the list of things to add please? I'd like to document the dial 9 to call back feature for folks in my zone who are using yap, but hesitate to publicize it until there is at least a minimum amount of security on the feature. (It doesn't have to be anything fancy.)

**Comment by jbraswell** [comment]
Would love to see this for my area.

**Comment by dgershman** [comment]
![Screen Shot 2022-10-15 at 3 05 04 PM](https://user-images.githubusercontent.com/1850811/196003795-5e8b1138-2db7-4bb6-9852-c88e55093637.png)

**Comment by alanb2718** [comment]
Looks good!  Just to make sure I'm understanding, if someone pushes 9 and puts in some random other phone number, it won't connect you, as opposed to the pin only protecting that one calling number?

**Comment by dgershman** [comment]
Correct, it will say "Invalid pin entry" and redirect you to the main menu again.

**Comment by pjaudiomv** [comment]
can we also have it return the pin in the voicemail sms notification or have an option too. a lot of my area volunteers never login to UI or even know about it

**Comment by dgershman** [comment]
Yes working that now.  Two SMS messages will have the dialback pin, both as a magic string (one click press), and also the PIN itself.  I'll post the sample SMS messages here shortly so you can give feedback on them.  This will be an option I'm thinking, since not everyone will by default want to have people use the dialback feature.

**Comment by dgershman** [comment]
SMS samples 
<img width="419" alt="Screen Shot 2022-10-15 at 7 56 47 PM" src="https://user-images.githubusercontent.com/1850811/196011762-649e290e-d2ff-4bb2-8939-4676b2115f8e.png">

**Comment by pjaudiomv** [comment]
heck ya

**Comment by dgershman** [comment]
Will be in 4.2.4

**Comment by alanb2718** [comment]
This looks great!  I do have one concern. Our area helpline guidelines say that volunteers should only call someone back if they leave a voicemail explicitly requesting a callback; they should not call back if someone hangs up before getting to the voicemail prompt, or if they leave an empty voicemail. (It could be a shared phone number, or a borrowed phone, or some other situation that means a call from NA could cause problems.) So maybe it would be better to omit the first "Tap to Dialback"?  And (maybe over the top?) at the end of the voicemail message there could be a note "Only return calls when there is an explicit request for a callback."  However, if other areas do have a policy of calling back if the call is dropped or the like, and the SMS stays as above, we can just incorporate these guidelines in our training instead.

**Comment by pjaudiomv** [comment]
I actually thought of this as well, you could make the sms options separate I guess too. Like default call sms should omit dial back but voicemail wouldn't idk

**Comment by dgershman** [comment]
I can create multiple options.

**Comment by dgershman** [comment]
This is documented here.  https://yap.bmlt.app/helpline/dialback

**Comment by dgershman** [comment]
4.2.4 released
