### ISSUE TITLE
support deleting voicemail messages once they have been handled

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#528]
Suggestion: support deleting voicemail messages once they have been handled.  This should delete them both from the yap database and also from Twilio.

**Comment by dgershman** [comment]
What is the use case for this?  Is there a strong need to delete it from Twilio, versus marking as deleted in the database, with the future ability to have some kind of recycle bin in the future?

**Comment by dgershman** [comment]
This feature is available in the latest build of 4.0.0.  Will be available in the next beta.
