### ISSUE TITLE
SMS enhancements

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#529]
Implement a very basic set of commands a user could send via SMS:

- `help` describe the commands that are available
- `talk <place>` text with a volunteer (as at present, except that it doesn't quite work at the moment - see #508)
- `meetings <place>` return a meeting list for `<place>`.

The current interface, which lets you just type in a place, would be retained for backward compatibility, but would be deprecated in favor of `meetings <place>`.

Would it be useful to also support plain `talk`, which connects you with a volunteer who is currently available (irrespective of location)?  Or does this break the underlying model too badly?

**Comment by radius314** [comment]
I would not deprecate meetings capability given the fact that 99% of use cases do not use the chat with SMS.  It could be something in the future, but I would not be in favor of that.

**Comment by radius314** [comment]
Supporting fallback for `talk` could be something that could be looked at, but seems like a separate feature request.

**Comment by radius314** [comment]
Actually, there is already a fallback number that can be specified.

**Comment by dgershman** [comment]
I'm not sure how useful this ticket anymore.  I don't really know what is something I'd implement.
