### ISSUE TITLE
More information in automated meeting SMS

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#541]
(Probably more like a Yap 4.1 thing...)
Would love to see format info added to the meeting info sent via SMS
This can help discern where there are gender specific meetings, disability accessible meetings, child friendly meetings, etc.

**Comment by dgershman** [comment]
You can include the details of any meeting format you want already.  For example, if you wanted to include information about if a meeting was virtual you could include that format in the setting below.

`include_format_details = ['VM']`

**Comment by EzraKuhr** [comment]
Interesting. So here’s my thought process… my region is acquiring all the area numbers into a regional twilio account they don’t have access to. With all the customization done in the webhook, every time an area wants something changed such as deciding to add format details or using tomato, they’d have to ask the region to make the change for them in the webhook. Is there a way to get these overrides and customizations into yap service body configs instead of long custom webhooks. The webhooks are also less intuitive and not as user friendly as configuring yap would be. 


Second thought (possibly a second ticket): a webhook semantic interface would be extremely helpful

**Comment by dgershman** [comment]
They don't need a webhook to make these changes, they can use service body configuration overrides.  I'm working on fixing a bug that was reported by @pjaudiomv in #543.  

https://bmlt.app/yap/#configurationprecedence

**Comment by EzraKuhr** [comment]
Oh. I didn't even think about doing that. Thank Danny. I guess that you can close up my ticket then.
