### ISSUE TITLE
meetings returned in a SMS summary page may not include all of the top 5 results

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#545]
If I set `$sms_summary_page = true;` to return the meeting search results as a single SMS summary page link, the page might not have all of the top 5 results that are read.  This seems weird.  This occurs both with the current release 3.9.9 and with 4.0beta7.

I called yap at 10:15pm on Sept 23 and asked for meetings in Spokane.  It read out a reasonable list of 5 meetings, the first one being an online meeting from Lapwai, Idaho that started at 11pm.  (Lapwai is 115 miles from Spokane, although the meetings are all in Northeast Washington Area.) The Lapwai meeting wasn't in the summary page when `$sms_summary_page = true;` but it was using the default of sending 5 separate SMS messages.

I then went and tried asking for meetings in Lapwai (by zip code -- voice recognition didn't work).  That did include the meeting on the summary page, so this probably occurred because the meeting was so far from Spokane.  The circumstances that cause this to happen may be unlikely enough that this wouldn't be a high priority to fix, but it still seems off.

**Comment by dgershman** [comment]
Can you share some screenshots to tell the story of your experience?

**Comment by alanb2718** [comment]
Here are screenshots.  First is the start of the SMS texts, from slightly earlier (10:05pm).  There are a couple of combined meeting searches, then the result of getting the texts individually.  Notice the first meeting in the individual texts is the 11pm Dream Catchers in Lapwai Idaho.

Next is a screenshot of all 5 texts with individual meetings.  These include the 11pm Thursday meeting, then the rest are on Friday.  This all seems correct.

Finally are two screenshots from the combined list of meetings showing all the Thursday meetings.  The second one shows the last of the Thursday meetings (Crazy NA at 9:45pm).  No Dream Catchers at 11pm, which is the unexpected part.


![SMS-start](https://user-images.githubusercontent.com/918773/135178341-43e5e675-340a-4654-9baf-e8014ecaf10b.jpg)



![SMS-5-meetings](https://user-images.githubusercontent.com/918773/135178451-ae4b32af-a9de-4360-9a0e-61f2e4542182.jpg)


![Thursday-combined-meetings-first](https://user-images.githubusercontent.com/918773/135178618-0025c167-96c2-4da1-a5d3-ae4b54ace0c3.jpg)

![Thursday-combined-meetings-last](https://user-images.githubusercontent.com/918773/135178630-d222a992-5886-4d73-aef3-8401104998d8.jpg)

**Comment by dgershman** [comment]
It doesn't look like it's actually combining anything.  This is what it looks like when `sms_combine` is set to `true`.

![image](https://user-images.githubusercontent.com/1850811/135932766-1c642e3b-221f-4e98-af7d-ec56fd0a4702.png)

**Comment by alanb2718** [comment]
Sorry!  I meant` $sms_summary_page = true;`.  `$sms_combine = true;` is working fine -- it's the summary page that has the weird behavior.  I'm going to edit the issue title and report accordingly (which I hope won't confuse things).

**Comment by dgershman** [comment]
Can you send the URI for the summary page?

**Comment by alanb2718** [comment]
https://bmlt.wszf.org/yap-4.0/msr/47.658693/-117.4225481
