### ISSUE TITLE
YAP 4.0.0 - Option 1 doesn't route to Volunteers only gives meeting info

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#568]
Upgraded to Yap 4.0.0
1. Call in to helpline
2. Press 1 to find someone to talk to
3. Say the State/Territory
4. Say the Town/Suburb
5. Meeting results are SMSed

**What version are you running?**
4.0.0

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
As above

**Expected behavior**
Press 1 should route to volunteers
Press 2 should search meeting information

Simply copied my config over from V3.9.9 to V4.0.0
Did I miss anything?

**Comment by dgershman** [comment]
What's the uri of your Yap instance?

**Comment by brustar64** [comment]
Is this what you mean?

https://na.org.au/yap/

But I've reverted to 3.9.9

I've set v4 to a test number at https://na.org.au/yap4/



Bruce
________________________________

**Comment by dgershman** [comment]
regression related to #522
