### ISSUE TITLE
Yap Reports

### ISSUE THREAD

**Issue by MCANAYAP** [bmlt-enabled/yap#582]
1. On 2.23.22, we updated to the latest version Yap v4.0.4 and thought this issue would be resolved. However, based on the raw data we ran from the twilio, all the calls are not being populated on the site. We tested the day we upgraded and it reported just fine. Not sure if there's a bug?

2. We used twilio for the data. 
3. Screenshot of latest calls populated. 
![image](https://user-images.githubusercontent.com/97411209/158501182-e0ef0057-e760-4a9e-b572-c4cffdc4a3f9.png)

4. Madison County Area (125) / Alabama North West Florida Region (91)

**Comment by pjaudiomv** [comment]
Is this a live help line, if so Can you please redact the from numbers from the photos or remove them.

**Comment by MCANAYAP** [comment]
Updated - Sorry about that & TY

**Comment by dgershman** [comment]
Can you clarify when you say "all the calls are not being populated on the site"?  What calls are missing?

**Comment by MCANAYAP** [comment]
I replied via email on 4.3.22 so i'm adding here as well. 
"Hi,
Sure. No calls are showing up under the "reports" tab since 2.23.22, which is the day we updated to the latest version. We're having to use twilio. This site is not populating the calls being received. "

**Comment by dgershman** [comment]
For example?  Can you give a detail of a call that you are expecting to be
there but isn’t?

**Comment by dgershman** [comment]
You can email sensitive information to ***@***.*** and reference this
ticket.

**Comment by dgershman** [comment]
Help at bmlt dot app

**Comment by MCANAYAP** [comment]
Based off Twilio we got 43 calls for the month of March. Not one populated off the site. See screenshot below of the last 2 calls that show as received. 

![image](https://user-images.githubusercontent.com/97411209/162628760-aab7d047-ad86-4b48-854e-571afd03b085.png)

**Comment by dgershman** [comment]
You can try out [4.0.5-beta1](https://github.com/bmlt-enabled/yap/issues/586)https://github.com/bmlt-enabled/yap/releases/download/4.0.5-beta1/yap-4.0.5-beta1.zip which should fix this.

**Comment by dgershman** [comment]
fixes released in 4.1.0

**Comment by MCANAYAP** [comment]
So sorry for not replying before. Yes. All good now it seems. Thank you

Thanks,
Jen Smith

**Comment by MCANAYAP** [comment]
Hi,
Sure. No calls are showing up under the "reports" tab since 2.23.22, which
is the day we updated to the latest version. We're having to use twilio.
This site is not populating the calls being received.

Thanks,
Jen Smith
