### ISSUE TITLE
How to drop into either meeting search or volunteers using url

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#587]
I know this question was answered before, but I cannot find where I saved the answer. What is the url to use in Twilio to go directly to the meeting search when someone calls? Similarly, what is the url to use to go directly to the volunteer routing?

**Comment by dgershman** [comment]
To go direct to meeting search:

{yap_url}/input-method.php?Digits=2

To go direct to volunteer search:

The same as above except Digits=1.

**Comment by dgershman** [comment]
Is there any reason why you have two separate numbers?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Redguy1959** [comment]
Yes there is. We have a need right now to have a number for meeting info versus a number for volunteers, but that is beside the point. I am asking why the webhooks don’t work the way described below with the input-method.php?Digits=1 versus Digits=2

**Comment by Redguy1959** [comment]
Yeah, I just uploaded the newest version of yap. We were at 4.0.0 and I uploaded 4.0.4. Config.php file is back now.

**Comment by dgershman** [comment]
I could not reproduce the issue.

**Comment by Redguy1959** [comment]
Confirmed working. Weird.
