### ISSUE TITLE
To play some mp3 file over the helpline

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/yap#588]
**Describe the bug**
We can play customize message over the helpline but, after it after mp3 get played, it hangs up itsef.

**What version are you running?**
Yap v3.9.7

**Did this happen on prior versions to the one you are running?**

**To Reproduce**
over the config php script, i add these lines:
static $fr_CA_greeting = "https://naquebec.org/wp-content/uploads/voice/bienvenue-ligne-na.mp3";
static $en_US_greeting = "https://naquebec.org/wp-content/uploads/voice/welcome-help-line.mp3"; 
static $en_US_voicemail_greeting = "https://naquebec.org/wp-content/uploads/voice/message-en.mp3";
static $fr_CA_voicemail_greeting = "https://naquebec.org/wp-content/uploads/voice/message-fr.mp3";
static $en_US_promptset = "https://naquebec.org/wp-content/uploads/voice/help-line-anglais.mp3";
static $fr_CA_promptset = "https://naquebec.org/wp-content/uploads/voice/ligne-daide-francais.mp3";

**Expected behavior**
1. We want the system to read a custom warm welcome messsage after the selection of the language (French or English).
2 We would add another message the time the server search a volunteer to ask the caller to give his/her name to the voicemail.   

**Screenshots**
I let you the Twilio event call in PDF
[Logs _ Calls _ Twilio.pdf](https://github.com/bmlt-enabled/yap/files/8599689/Logs._.Calls._.Twilio.pdf)

**Additional context**
Another option is, can use Alexa to read a message as we use her to read the JPT?

**Comment by dgershman** [comment]
https://naquebec.org/wp-content/uploads/voice/help-line-anglais.mp3 returns a 404 (page not found).

Also, your greeting should indicate which numbers to press for each option, since it's a full replacement for the menu that is automatically spoken out.  

Here is an example of what one area has done:

https://crossroadsarea.org/wp-content/uploads/9/2018/08/crossroads_v4_greeting.mp3.

I'm not sure what you mean when you said.

> We would add another message the time the server search a volunteer to ask the caller to give his/her name to the voicemail.

Also:

> Another option is, can use Alexa to read a message as we use her to read the JPT?

**Comment by Klodd65** [comment]
How can you be sure that the caller who wants to leave a voicemail message leaves at least his name so that the attendants can contact him? (sorry about my English)

Also I test it over the phone myself whatever the message and the link is ok.

**Comment by dgershman** [comment]
Tell them to leave their name in your message.  Otherwise there is no easy way  currently to ensure that the data captured is a name.

**Comment by Klodd65** [comment]
and if i play the message, why the system hang it up? There is no error on the logs on Twilio.

**Comment by dgershman** [comment]
When does it hang up?  During the initial greeting?

**Comment by Klodd65** [comment]
after the greeting message, after 2 seconds

**Comment by dgershman** [comment]
Ok I'll have to take a look.  I've not heard of this happening on any other install.

**Comment by Klodd65** [comment]
would it better to upload a simulate a test record what the system does?

**Comment by dgershman** [comment]
If you'd like to.

**Comment by Klodd65** [comment]
Ok, I need to rebuild the mp3. It left a blank after and you can press 1 , 2 or 3. Can I leave this ticket open? I will test it back on thursday afternoon (only 1 volunteer).
I will try after the voicemaail greeting message next.

**Comment by dgershman** [comment]
Do you have any update on this?

**Comment by Klodd65** [comment]
Not again. I am really want the trustservant to record the welcome and the voicemail message but it seems to work. I will be able to conform it when she record her voice. The thing is i didn't know that the welcome message has to replace the system message, press one to speak to a member, press two to find a meeting, etc.

**Comment by Klodd65** [comment]
Everything is okay!

**Comment by dgershman** [comment]
Great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
