### ISSUE TITLE
add ability to export spreadsheet of volunteers

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#595]

**Comment by dgershman** [comment]
Does it have to be a spreadsheet?  Can it be a CSV?

**Comment by pjaudiomv** [comment]
yea csv would be fine

**Comment by dgershman** [comment]
what level of detail are you looking for?

**Comment by pjaudiomv** [comment]
Mainly just care about name and phone number, whether they are active or not would be a bonus. Don't care about there schedule info

**Comment by dgershman** [comment]
What about when they are on schedule?  What about gender if set?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pjaudiomv** [comment]
Not concerned with that, use case is to just have a list of volunteers to be able to easily see and share and call them. If additional info can be added great but not needed for my use case

**Comment by tempsaint** [comment]
I would think the schedule would be helpful info if you're exporting volunteer info

**Comment by dgershman** [comment]
![Screen Shot 2022-07-26 at 5 11 08 PM](https://user-images.githubusercontent.com/1850811/181112724-b4e541a2-44ea-4b75-876d-15565c4faede.png)

**Comment by dgershman** [comment]
Available in 4.1.0-beta2 if you want to test. 

https://github.com/bmlt-enabled/yap/releases/tag/4.1.0-beta2

**Comment by dgershman** [comment]
completed, released 4.1.0
