### ISSUE TITLE
Call blasting

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#60]
If multiple helpline volunteers are listed as same sequence and same time their available, yap will call "blast" all volunteers and first one to pickup gets the call and all other calls end

**Comment by radius314** [comment]
Yes, this is known as a hunt group in telephony.

**Comment by pjaudiomv** [comment]
Yes I remember that now from doing research on phone systems before I went with grasshopper for mvana.

**Comment by radius314** [comment]
#42 will have to be implemented first, or this will easily be broken by a fast force to VM.

**Comment by radius314** [comment]
https://www.twilio.com/blog/2009/05/dialing-multiple-numbers-simultaneously-with-twilio.html

**Comment by radius314** [comment]
There was another vote for this.

**Comment by pjaudiomv** [comment]
this gos into a loop, after calling and picking up the call blast cycle happens again only this time call appears to come from helpline not callers number
![img_9192](https://user-images.githubusercontent.com/34245618/48009402-ad0b4980-e0e9-11e8-91b6-ea0656f74568.jpg)

**Comment by pjaudiomv** [comment]
![yap_log](https://user-images.githubusercontent.com/34245618/48014848-95d25900-e0f5-11e8-943b-8489e6cdd2c4.jpg)

**Comment by pjaudiomv** [comment]
you can see at 12:10:46 I took the call then it initiated the call blasting all over again

**Comment by radius314** [comment]
patched this in master

**Comment by pjaudiomv** [comment]
this seems to be working as expected now, ideally i could test later with three phones.

**Comment by radius314** [comment]
feel free to add my phone in now to do a test

**Comment by brustar64** [comment]
So we switched one of our areas to Blasting and it turns out that multiple volunteers are able to access the call at the same time.  We expected that the call would be handled by the first volunteer who responded.

**Comment by radius314** [comment]
The version that was put out was not designed in this manner.  The
minimally viable solution was to call everyone and then let the volunteers
sort it out.

**Comment by pjaudiomv** [comment]
Yes so currently this is how the feature works, potentially every volunteer could join in on one big party line. Ideally it would only allow first volunteer.

**Comment by radius314** [comment]
There are a lot of design implications to make this possible.  I would call this an enhancement for a future version, not a bug.

**Comment by pjaudiomv** [comment]
agree as you said it was minimally viable solution
