### ISSUE TITLE
Only the first "Volunteer Dialed" event shows up in the Reports datatable.

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#613]
**Describe the bug**
Regardless of the number of volunteers on-call, only the first volunteer tried shows up as a "Volunteer Dialed" event in the Reports datatable.

**What version are you running?**
4.1.0

**Did this happen on prior versions to the one you are running?**
No, this was broken in 4.1.0.

**To Reproduce**
1. Log into SEZF Yap
2. Go to Reports
3. Select Capital Area or Greensboro Area (it happens for all areas, these are just the two I'm familiar with)
4. Expand any CALL records in the datatable to view the events.
5. Regardless of the number of volunteers that were attempted, only the first shows up as a Volunteer Dialed event.

**Expected behavior**
All volunteers that were dialed should show up as Volunteer Dialed events, in the order they were tried.

**Comment by dgershman** [comment]
will be in yap 4.1.1
