### ISSUE TITLE
Menu option to route to special service body or group

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#622]
I will explain our need:

Our previous Helpline system had a menu option for professionals seeking information about Narcotics Anonymous. They would be connected to a special group of trusted servants who had extensive PR experience to handle these calls. We would appreciate such a feature in Yap.

**Comment by dgershman** [comment]
This is a duplicate of a feature already requested (#584) Closing it in favor of that one. 

There is an option available already to route a call to another phone number for a special purpose.  So if you have another number that you'd like to route to you can.  The ability to specify a list of volunteers within Yap is not yet available but in the works.

**Comment by Redguy1959** [comment]
Thanks Danny.
