### ISSUE TITLE
PHP 8.x support

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#623]
it would be great if yap could support PHP 8.x, just updated craptop and i got 8.1 and my new jammy server is 8.1 too. I think laravel minor version needs to be bumped prob and at least one dev dep is problematic 

`nvanheuverzwijn/monolog-logdna` which doesnt play nice with others

```
  Problem 1
    - Root composer.json requires nvanheuverzwijn/monolog-logdna ^3.0 -> satisfiable by nvanheuverzwijn/monolog-logdna[3.0.0].
    - nvanheuverzwijn/monolog-logdna 3.0.0 requires monolog/monolog >=3.0 -> found monolog/monolog[dev-main, 3.0.0-RC1, ..., 3.x-dev (alias of dev-main)] but the package is fixed to 2.8.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

I have a wip branch here https://github.com/bmlt-enabled/yap/compare/pj/yap-8-wip?expand=1 
could prob bump twilio too maybe

**Comment by dgershman** [comment]
We can probs remove logdnA

**Comment by dgershman** [comment]
@jbraswell you can remove the whole section where the cloud key is used as well.

**Comment by dgershman** [comment]
will be in v4.2.0
