### ISSUE TITLE
Yap Reports does not seem to be recording Meeting Lookups

### ISSUE THREAD

**Issue by IlexOpaca1992** [bmlt-enabled/yap#627]
We are on version 4.1.2. We see meeting lookups in Twilio logs but not in Yap. It remains zero in Yap. Also, Volunteer Lookups seems to be undercounted. We can see in the Twilio logs the last action POST to status.php but nothing appears in Yap logs.

**Comment by dgershman** [comment]
What is your status callback on that number?

**Comment by IlexOpaca1992** [comment]
https://nanj.org/yap/status.php


________________________________

**Comment by dgershman** [comment]
Was there an error in Twilio logs?

**Comment by dgershman** [comment]
Also do you see an errors in the logs on your instance?  They are typically in storage/logs

**Comment by IlexOpaca1992** [comment]
No errors in the Twilio logs. There are, however, a lot of outgoing SMS of the form "You have an incoming phoneline call from +13154916745" and these are being sent to the Helpline volunteers. I think this is unrelated to the Reports issue but am wondering why this occurs.


________________________________

**Comment by IlexOpaca1992** [comment]
I see the web server logs - they are pretty big so I searched on status.php. There are no errors, just http "200" responses associated with status.php. No "500" or "404" errors. Not seeing any errors with anything in the Yap directories.


________________________________

**Comment by dgershman** [comment]
Very strange.  Can you send a screenshot of your Twilio configuration ?  You can block out the number.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IlexOpaca1992** [comment]
TYPE
Local
CAPABILITIES
Voice, Fax, SMS, MMS
LOCALITY
Manasquan, NJ US
NOTES
—
Voice & Fax
ACCEPT INCOMING
Voice Calls
CONFIGURE WITH
Webhook, TwiML Bin, Function, Studio Flow, Proxy Service
A CALL COMES IN
Webhook

HTTP GET
PRIMARY HANDLER FAILS
Webhook

HTTP POST
CALL STATUS CHANGES

HTTP POST
CALLER NAME LOOKUP
Disabled
EMERGENCY CALLING
Emergency Address is not registered.
Add Emergency Address
Messaging
MESSAGING SERVICE
Choose a Messaging Service
CONFIGURE WITH OTHER HANDLERS
Webhook, TwiML Bin, Function, Studio Flow, Proxy Service
A MESSAGE COMES IN
Webhook

HTTP GET
PRIMARY HANDLER FAILS
Webhook

HTTP POST



________________________________

**Comment by dgershman** [comment]
Screenshot?

**Comment by IlexOpaca1992** [comment]
Screenshot of what exactly - I just sent you a copy/paste of the Twilio config for the number? I did this because I would have to send multiple screenshots to send the same amount of stuff.


________________________________

**Comment by dgershman** [comment]
A can’t see the actual configuration of the number.  From what you pasted.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IlexOpaca1992** [comment]
Can you tell me what information you want when you say “configuration of the number” so I know what screen to take a screenshot of? What is some of the stuff on the screen so I can identify it.



________________________________

**Comment by IlexOpaca1992** [comment]
Is this what you need or something else?


________________________________

**Comment by dgershman** [comment]
Under the management of the phone number it should show how you have your webhooks configured .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IlexOpaca1992** [comment]
Sent the screen shots last night as 3 attachments. Did they arrive?


________________________________

**Comment by dgershman** [comment]
They did not.  You may need to attach them in the ticket itself.

**Comment by IlexOpaca1992** [comment]
![Screenshot 2022-08-20 220038](https://user-images.githubusercontent.com/111646335/185792839-0229bba5-3dee-42e5-9df5-84e2f533c991.png)
![Screenshot 2022-08-20 220105](https://user-images.githubusercontent.com/111646335/185792842-49560510-ce00-4fbf-9059-37c88e21baf7.png)
![Screenshot 2022-08-20 215942](https://user-images.githubusercontent.com/111646335/185792844-e8d584c8-b083-465d-a5e6-5ebccc110662.png)

**Comment by dgershman** [comment]
This looks good.  Is there any data in any of the following tables in MySQL?

* records
* records_events
* conference_participants

**Comment by IlexOpaca1992** [comment]
I was wondering what next steps are to diagnose this? Happily the system appears to be working fine except for the Reports. Volunteer call routing and meeting lookups work fine, it's just the reports so if you are busy I get it.


________________________________

**Comment by dgershman** [comment]
Can you email a dump of the database and your config.php to danny<dot>gershman<at>gmail<dot>com?

From: IlexOpaca1992 ***@***.***>
Date: Tuesday, August 23, 2022 at 4:14 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] Yap Reports does not seem to be recording Meeting Lookups (Issue #627)
I was wondering what next steps are to diagnose this? Happily the system appears to be working fine except for the Reports. Volunteer call routing and meeting lookups work fine, it's just the reports so if you are busy I get it.


________________________________

**Comment by IlexOpaca1992** [comment]
The whole database or just specific tables?

Do you need any Twilio logs too?



________________________________

**Comment by IlexOpaca1992** [comment]
Any particular format for the database dump? I have access to phpMyAdmin and the export defaults to "SQL" but there are other choices.


________________________________

**Comment by dgershman** [comment]
Ok figured out what's happening.  The issue occurs because you use a statewide number that is not pointed to a specific service body.  This essentially means data is allocated to a generic service body called `General (0)`.  There are some bugs that need to be fixed, and they will be present in Yap 4.2.0.  However, do not fret, data is being captured, even though you can't see it.

Below is a screenshot showing the current data set from your snapshot:

<img width="987" alt="Screen Shot 2022-08-23 at 7 59 52 PM" src="https://user-images.githubusercontent.com/1850811/186286471-f8485dc3-eca4-4b49-88a1-3b4c7b784c7c.png">
<img width="969" alt="Screen Shot 2022-08-23 at 8 00 28 PM" src="https://user-images.githubusercontent.com/1850811/186286586-a426f6b2-6e5b-4817-8a01-48a9c6104449.png">

**Comment by IlexOpaca1992** [comment]
Awesome! I am glad you could figure this out. Thanks again!


________________________________

**Comment by dgershman** [comment]
proposed fix released in 4.2.0

**Comment by IlexOpaca1992** [comment]
Hi Danny,


on the change notes for Yap 4.2.0 it says "Yap now requires PHP version 8.0 and higher." but there are two files that can be downloaded, one says PHP-8.0 and one says PHP-7.4. Does this mean it still works with 7.4?




________________________________

**Comment by dgershman** [comment]
Yes.  Use the 7.4 named file.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
The release note needs to updated.

**Comment by IlexOpaca1992** [comment]
We tried the yap-4.2.0-php-7.4 and it gave an error that PHP 8 was required for Composer or something.


We tried yap-4.2.0-php-8.0 with PHP 8.1 on our site. Calls seemed to work ok but the Reports on the admin console just give "Error" in a box above where the details would normally show up. This happens no matter what service body is selected.


Reverted to yap-4.1.2 and PHP 7.4.


________________________________

**Comment by dgershman** [comment]
The builds were updated today, if you can give it another try and let us know if it works for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IlexOpaca1992** [comment]
Yes, there is data in all three of these tables, quite a bit actually.

The Reports in Yap are not completely empty, they have just never recorded any Meeting Lookups at all and only record some of the known Volunteer Lookups.


________________________________

**Comment by IlexOpaca1992** [comment]
The 7.4 file throws this error: "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2"."




________________________________

**Comment by IlexOpaca1992** [comment]
Loaded yap-4.2.0-php-7.4 . It no longer gives an error asking for PHP 8. Calling and system works but the Reports do not work at all. Choose any service body and it says "Loading" for a second or two then says "Error".


________________________________
