### ISSUE TITLE
metric buttons showing all 0s for 4.2

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#639]
just testing the latest build for 4.2.0 and all of the metric buttons are showing 0. they work fine in 4.1.2

https://s3.amazonaws.com/archives.bmlt.app/yap/yap-125-4aeb4ca6fbba551fb7b1b5e5f605e1551e1e0a7d.zip

4.1.2

<img width="1273" alt="Screen Shot 2022-08-24 at 9 00 07 PM" src="https://user-images.githubusercontent.com/34245618/186551137-7c7e3a02-2a8b-4544-8daa-4c44b382f917.png">

4.2.0

<img width="1222" alt="Screen Shot 2022-08-24 at 9 02 45 PM" src="https://user-images.githubusercontent.com/34245618/186551161-000c4397-1939-4e0f-8d14-89890fb1ba06.png">

**Comment by dgershman** [comment]
I could not repro.  Are there any JS errors?

**Comment by pjaudiomv** [comment]
No js errors, this is n SEZF server

**Comment by pjaudiomv** [comment]
digging through logs and such, its not working on php8.1 but is on php8.0

**Comment by dgershman** [comment]
Where ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
