### ISSUE TITLE
laravel log errors on sezf server

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#650]
lots of ` [HTTP 400] Unable to create record: AccountSid <REDACTED> is invalid` errors all with same account sid. then other undefined array warnings. it seems like also if no volunteer is on it causes an error maybe idk.

Attached log file here
[laravel.log](https://github.com/bmlt-enabled/yap/files/9531462/laravel.log)

**Comment by dgershman** [comment]
this is related to #648 i believe
