### ISSUE TITLE
Make curl user-agent configurable

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#660]
Yap makes http requests to a root server, and that root server is sometimes in shared hosting. Allowed user agents in shared hosts can be a moving target. It would be nice to have a configuration setting for the user agent, with a sane default if it's not set.

Central Indiana had to change the getUserAgent function to return `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0` to get requests working,.

**Comment by dgershman** [comment]
The fix was changed to support user agent issues with siteground.
