### ISSUE TITLE
Ability to Disable Post Call SMS

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/yap#663]
I am requesting that the ability to disable post call SMS be added.  We have a situation where we're routing meeting search calls from another phoneline, and that telecom provider says new FCC rules prevent them from forwarding anything but our account phone number (which is our phoneline). This has resulted in SMS messages being sent back to our phoneline and not the actual caller. Since it's FCC rules, there's no way for them to get around this. 

The best solution for us, at least short term, is to be able to disable the post call SMS. But I also think there could be other use cases where someone would want to not send SMS messages back to callers. 

 I suppose we could just set `sms_ask` to `false`, but then we're just throwing money away having Twilio send SMS messages back to our phoneline. But I suppose that is an option.

**Comment by dgershman** [comment]
The other thing you could do short term until 4.2.3 is released is set `sms_summary` to `true` which will reduce to one SMS message.  This will save money immediately.  That being said, 4.2.3 should be released shortly.

**Comment by tempsaint** [comment]
Thanks - we already have `sms_summary` set to `true` that's good. I think that's why the cost has been negligible even with the sms messages basically going into a bit bucket. 
What's interesting is that our phoneline provider hasn't mentioned anything about incoming SMS and Twilio hasn't complained with any errors delivering the messages (like it normally does if you try to text a landline).

**Comment by dgershman** [comment]
That is strange.  You could also set `mobile_check` to `true`, which would detect if a landline called (not a perfect science) and then selectively send SMS if it's truly SMS capable.  4.2.3 has been released with this new feature as requested.  Set `sms_disable` to `true`.
