### ISSUE TITLE
gender routing problem

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#703]
**Description**
We set up an area with Call Blasting then Voicemail as the call strategy, and with Gender Routing turned on.  If we call the test number, it never calls a volunteer, even though there is a volunteer with the selected gender available.  It also never goes to voicemail.  If we turn off gender routing for the area the test number works. 

**What version are you running?**
4.2.7

**Did this happen on prior versions to the one you are running?**
Never tried gender routing before

**To Reproduce**
1. Change the configuration to turn on Gender Routing, with Call Blasting then Voicemail call strategy
2. Include a male volunteer.
3. Call the test number, ask to speak to a volunteer, ask to call a male

**Expected behavior**
I expected it to call the volunteer, and if no answer, to go to voicemail.

**Comment by dgershman** [comment]
What's the webhook?  What's the service body ID?

**Comment by alanb2718** [comment]
I don't want to leave things broken, because they're getting ready to port their current helpline.

So here is the same area, on our yap test server, with gender routing enabled:
The webhook is https://test.wszf.org/yap/index.php?override_service_body_id=12 
service body ID 12
The database on this test server is freshly copied from the production one.

**Comment by alanb2718** [comment]
Sorry .... I think it _does_ have gender selection enabled.  I'll set up a test number you can call and hear the prompt.

**Comment by alanb2718** [comment]
I think the gender routing problem was triggered by the siteground / very old user agent issue (fixed in #788). I just tried turning gender routing on and now it's working!
