### ISSUE TITLE
Not receiving text with phone number

### ISSUE THREAD

**Issue by rhondacoren05** [bmlt-enabled/yap#705]
We are receiving calls and usually when we miss the call or sometimes answer, we receive a text with the phone number. Sometimes it comes through sometimes it doesn't. 

Yap v4.2.0

**Did this happen on prior versions to the one you are running?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alanb2718** [comment]
Do you have a toll-free number?  If so check for a Twilio error
`30032 – Toll-Free Number has not been verified`

They have been checking for verified toll-free numbers for a couple of months now.  There is also _another_ requirement to register all numbers by Dec 15 – but hopefully that one hasn’t kicked in yet.

Ugh ….

**Comment by dgershman** [comment]
Please provide additional information.
