### ISSUE TITLE
setting sms_combine to true also causes yap to ask if you want to get an SMS

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#706]
**Description**
If I set `sms_combine` to true and leave `sms_ask` at its default value of false, yap still asks if you want to get an SMS in response to a meeting search.  It's as if `sms_ask` were true, even though it's not.  If `sms_combine` is false this doesn't happen.

**What version are you running?**
4.2.7

**Did this happen on prior versions to the one you are running?**
Don't know.

**To Reproduce**
1. In a configuration, set `sms_combine` to true and leave `sms_ask` at its default value of false.
2. Call, and ask for a meeting lookup.
3. Listen to all 5 meetings.  At the end it will ask if you want to get a text.

**Expected behavior**
If `sms_ask` is false, yap should not ask.

**Screenshots**
NA

**Additional context**
I left our test server set up to demo this behavior.  The webhook is https://test.wszf.org/yap/index.php?override_service_body_id=3
service body ID 3
The database on this test server is freshly copied from the production one.

**Comment by dgershman** [comment]
yup this is a bug

**Comment by dgershman** [comment]
will be in yap 4.3.0
