### ISSUE TITLE
Append a link to an online meetings page if there are no results listed

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#707]
Our online area has requested a feature whereby a link can be sent to our online meetings page if there are no valid search results for a particular area.

**Describe the solution you'd like**
We would like to be able to preconfigure a setting for a webpage if no search results are available.

**Describe alternatives you've considered**
An alternative we've considered is to append every results SMS with a link to our online meetings landing page in addition to the usual search results.

**Comment by dgershman** [comment]
Can you give an example of the area where there are no search results available?

**Comment by brustar64** [comment]
Hi Danny,

the example given was Gladstone QLD where there are only one or two meetings a week.  Depending on the day you message you wont' get any results.
There are many other locations which fall into this bracket.

The alternative we've considered is to add a link to our online meetings page for all search result responses.

EG:

Can't find a local meeting? Meet online at https://www.na.org.au/multi/online-meetings/
Online Meetings - Narcotics Anonymous Australia<https://www.na.org.au/multi/online-meetings/>
Online meetings are available for people who are unable to attend a physical meeting. Non-Location Centric Meetings. These Online or Virtual Meetings are generally not associated with geographical locations.
www.na.org.au

________________________________

**Comment by dgershman** [comment]
You can include virtual meetings in the results if you'd like.  https://yap.bmlt.app/meeting-search/venue-options/#virtual-meetings
