### ISSUE TITLE
Can't make reports from YAP

### ISSUE THREAD

**Issue by fsrnadmin** [bmlt-enabled/yap#711]
All of a sudden, on a siteground hosted site https://freestatena.org/yap/admin ... we go to reports-> then pick our region, to do a report and it says loading... but never populates...

The rest of the yap server works... yap 3.9.9
our phoneline system is working otherwise... unless i upgrade the site to php 8.0

**Comment by dgershman** [comment]
This was an issue first reported in October.  The fix was made available in 4.2.2.

https://github.com/bmlt-enabled/yap/commit/845b146c9545b252fc32ecb5c4f3c47309b51357
