### ISSUE TITLE
Cannot install YAP 4.2.8

### ISSUE THREAD

**Issue by fsrnadmin** [bmlt-enabled/yap#712]
after filling out the https://freestatena.org/yap-4.2.8/admin/installer.php table
i create the config.php file in the root folder and I get a 

Error: SQLSTATE[42S21]: Column already Exists: 1060 Duplicate Column name 'type'

**What version are you running?**
trying to run upgrade yap 4.2.8 on PHP 8.0+

**Comment by dgershman** [comment]
Email a database dump to help@bmlt.app

**Comment by fsrnadmin** [comment]
emailed the dump

**Comment by dgershman** [comment]
A couple of notes here:

1) Do not use the installer, copy the config.php over only.  I know you said you did that originally.  There is no need to use the installer if you are already using Yap.
2) Did you send the right database dump?  I don't see anywhere where the `type` column exists in this database.
