### ISSUE TITLE
Invalid twiml schema from fallback.php

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#754]
**Describe the bug**
Twilio is reporting this error:

Message
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'Say'. One of '{Sms, Message, Redirect}' is expected.
```

Description
```
## Warning - 12200 ### Schema validation warning The provided XML does not conform to the Twilio Markup XML schema. Please refer to the specific error and correct the problem.
```

From URL: https://bmlt.sezf.org/zonal-yap/fallback.php

With Response Body:

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="Polly.Kendra" language="en-US">
        there seems to be a problem... please wait while we connect your call... please stand by.
    </Say>
    <Dial>
        <Number sendDigits="w"></Number>
    </Dial>
</Response>
```

**What version are you running?**
4.2.0

**Did this happen on prior versions to the one you are running?**
Don't know.

**To Reproduce**
I actually don't know under what conditions fallback.php is called.

**Expected behavior**
Seems like fallback.php should return valid twiml.

**Comment by dgershman** [comment]
can you set a fallback number? https://yap.bmlt.app/general/fallback/

**Comment by jbraswell** [comment]
How would that work for a zonal server?

**Comment by dgershman** [comment]
Not sure how you want to use it, but it could be sent within a given service body config.

**Comment by jbraswell** [comment]
Gotcha. That makes sense. Is the twiml not validating schema because there's no fallback number configured for that call?

**Comment by dgershman** [comment]
I believe it's because `<Number sendDigits="w"></Number>` has no number.

**Comment by jbraswell** [comment]
Gotcha, that makes sense then. So fallback.php is what happens when there's some issue talking to the root server, and for this to work the service body would need to configure a fallback number. I am going to close this issue. Thanks!
