### ISSUE TITLE
New PhP causes 500 error for admin login page

### ISSUE THREAD

**Issue by Flooberjibby** [bmlt-enabled/yap#780]
**Describe the bug**
We upgraded to PhP 8.1 to support BMLT 3.0.3 and the Yap admin page no longer works

**What version are you running?**
Tried 4.0.4 and 4.2.8

**Did this happen on prior versions to the one you are running?**

**To Reproduce**
1. Go to yap admin page - server 500 error

**Expected behavior**
We should get the Yap admin login page

**Additional context**
When we switch BACK to 4.0.4 and downgrade PhP to 7.4 we get the login page back.

The attached log is from the NEW, 4.2.8 version.
[laravel.log](https://github.com/bmlt-enabled/yap/files/10867635/laravel.log)

**Comment by dgershman** [comment]
What installation zip did you use?

**Comment by Flooberjibby** [comment]
The yap-4.2.8.zip from the downloads page.

**Comment by dgershman** [comment]
Can you make another folder for the yap install that is isolated from the main one and then send the url?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Flooberjibby** [comment]
We have the new version in the yap folder, the old install is in a folder called yap.old.

So our main (new) admin page is https://www.sjna.org/yap/admin

Our old install is https://www.sjna.org/yap.old/admin

If I have misinterpreted what you mean please let me know.

Thanks for your help!

**Comment by dgershman** [comment]
Ok this exactly what I meant.  I will take a look.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Flooberjibby** [comment]
Ok I may have an issue there. I saw in the upgrade notes from 3x to 4x that we needed a .env file and a generated key (or it would use the default). I didn't see one in our 4.0.4 install so I didn't create one in the new directory since they were both 4+. We had help when we did the initial install and didn't create one then so it wasn't done.

If I need one I'm happy to do it, the link in the doc to create a key with a length of 32 gave me a 404 when I went to go check it out.

Let me know how I should proceed and I'll jump on it.
Thanks!

**Comment by Flooberjibby** [comment]
I just created the .env file in both the new install and the old one. If I confused things further let me know and I'll back out one or both.

I used the same key in each directory and set the debug to true as you asked.

We are still set to use PhP 8.1.

**Comment by dgershman** [comment]
It's actually not required, although the initial upgrade notes did say that.  The key is optional.  The `.env` file won't work pre 4.x as they were not based on Laravel.

**Comment by dgershman** [comment]
So it looks like there is a permissions related issue and the bootstrap/cache folder is not writable.  Most people don't have permissions related issues when the deploy this, however I'm not sure what kind of hosting environment you are operating in.  

Generally speaking, there needs to be some level of write permissions to `./bootstrap/cache` and `./storage` paths.

**Comment by Flooberjibby** [comment]
I unzipped the file and copied it straight over to the site with no modifications, not sure what might have happened. Attached are pictures of the properties for the storage and bootstrap folders; I do not currently see a cache folder under bootstrap (I think I remember seeing one yesterday but I'm not 100% on that).
Should I copy a fresh install in and see what happens? Change the permissions on the folders?

Thanks!

**Comment by dgershman** [comment]
No worries.  Glad we were able to work through it.  Yes you can delete the file, or comment out that line in the `.env` file or set `APP_DEBUG=false`
