### ISSUE TITLE
Callback Feature - Limit to YAP registered Volunteers only

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#805]
**Is your feature request related to a problem? Please describe.**
We don't widely publicise the callback feature for fear of abuse of the service however we would like to enable only YAP enabled volunteers to be able to use this feature. Is there a way we can programatically limit this in Twilio?

**Describe the solution you'd like**
Automatically create a list of allowed callback users in Twilio based on YAP enabled volunteers.
Prevent callback from non-volunteers/other numbers.

**Describe alternatives you've considered**
The only alternative is that we've considered is not to tell people about the callback feature for fear that it will be abused.

**Mention any other of the Github handles that are also interested in this enhancement**
@dgershman @

**Additional context**
Concerns about international calls and limiting Geolocation to those countries we specify.

**Comment by dgershman** [comment]
As of yap 4.2.4 only registered users and those that have a PIN can use dialback. 

https://github.com/bmlt-enabled/yap/releases/tag/4.2.4

**Comment by brustar64** [comment]
Thanks Danny, 
I'll check the doco for enabling - managing the PIN

**Comment by dgershman** [comment]
Here is the [documentation](https://yap.bmlt.app/helpline/dialback/).

**Comment by brustar64** [comment]
Hi Danny,

We've been testing this and I just wanted to clarify what the responder experience/workflow should be.


  1.  Voicemail received
  2.  Responder dials the helpline and press 9 to initiate the callback
  3.  Switch back to text message and click on the "Caller number + PIN" URL

It appears that Android phones are unable to process the URL (seems like their dialler doesn't fully process the tel: standard)

YILS
Bruce
________________________________

**Comment by brustar64** [comment]
Thanks Danny
That puts us in a good position to move forward with a documented process.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
