### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/yap#814]
I installed yap 4.2.10 yesterday and it didn't work. After realizing probably the problem was that I needed up upgrade our php, I upgraded from 7.4 to 8.2 and tried yap again.
It still doesn't work. The error is 500 server error, when I tested: https://natennessee.org/yap4.2.10/upgrade-advisor.php
The old yap still works: https://natennessee.org/yap/upgrade-advisor.php
Been a while since I've upgraded yap as I'm not the region's ITCC any longer, but I've been working on the Twilio campaign to make sure we get our campaign approved, so upgraded to the newest yap. I believe all I needed to do was copy over the config, which I did.

**Comment by californiasteve** [comment]
Did you move the config.php file over to the new yap?

**Comment by dgershman** [comment]
We rebuilt the release, can you try it again with this?  https://github.com/bmlt-enabled/yap/releases/download/4.2.10/yap-4.2.10.zip

**Comment by lucy12187** [comment]
It works with that new version.  Thanks, Danny!
