### ISSUE TITLE
sporadic 500 | Server Error on admin panel

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#820]
**Describe the bug**
We've been sporadically seeing a `500 | Server Error` after trying to log in on the admin panel.  Clearing the host's cache fixes it.

**What version are you running?**
4.2.8

**Did this happen on prior versions to the one you are running?**
no

This is for https://bmlt.wszf.org/yap/admin.  It is still hosted on siteground, which has some pretty aggressive caching.  So perhaps siteground is just caching something it should not; but maybe there is also a yap bug that is interacting badly with the aggressive caching.  Laravel log is attached.

[laravel.log](https://github.com/bmlt-enabled/yap/files/12136812/laravel.log)

**Comment by dgershman** [comment]
What do you mean when you "Clearing the hosts cache fixes it".  What exactly are you doing?

**Comment by alanb2718** [comment]
Here is what siteground says about their dynamic caching mechanism (https://my.siteground.com/support/kb/siteground-dynamic-caching-configuration/):

> Our Dynamic caching is a full-page caching mechanism powered by NGINX that’s enabled and running by default on all SiteGround servers. Applications that send the appropriate headers to allow caching will achieve unbeatable website loading speed. WordPress normally works out-of-the-box with our Dynamic Cache, but other applications may need an additional configuration.

There is a button on their control panel to flush it manually: https://my.siteground.com/support/tutorials/supercacher/dynamic-cache/#How_to_manually_flush_the_Dynamic_Cache.  That is what I meant by "clearing the host's cache".  

There are also controls to exclude some URLs from caching (https://my.siteground.com/support/tutorials/wordpress/sg-optimizer/supercacher/#Exclude_URLs_from_Caching).  So I could just try excluding all of yap; but if the laravel log indicates something more specific is the problem I could exclude that.

Given that there are a fair number of BMLT users still on siteground, it's a bit surprising there haven't been other reports of this, unless there is something peculiar about the WSZF configuration.

**Comment by dgershman** [comment]
Yap has its own built-in caching, and it’s not meant to be cached.  I would disable all caching.

From: Alan B ***@***.***>
Date: Saturday, July 22, 2023 at 11:22 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] sporadic 500 | Server Error on admin panel (Issue #820)

Here is what siteground says about their dynamic caching mechanism (https://my.siteground.com/support/kb/siteground-dynamic-caching-configuration/):

Our Dynamic caching is a full-page caching mechanism powered by NGINX that’s enabled and running by default on all SiteGround servers. Applications that send the appropriate headers to allow caching will achieve unbeatable website loading speed. WordPress normally works out-of-the-box with our Dynamic Cache, but other applications may need an additional configuration.

There is a button on their control panel to flush it manually: https://my.siteground.com/support/tutorials/supercacher/dynamic-cache/#How_to_manually_flush_the_Dynamic_Cache. That is what I meant by "clearing the host's cache".

There are also controls to exclude some URLs from caching (https://my.siteground.com/support/tutorials/wordpress/sg-optimizer/supercacher/#Exclude_URLs_from_Caching). So I could just try excluding all of yap; but if the laravel log indicates something more specific is the problem I could exclude that.

Given that there are a fair number of BMLT users still on siteground, it's a bit surprising there haven't been other reports of this, unless there is something peculiar about the WSZF configuration.
