### ISSUE TITLE
Calls not going through to volunteers or voicemail

### ISSUE THREAD

**Issue by scrti** [bmlt-enabled/yap#823]
Calls not going through to volunteers

Latest version installed

Yes, but intermittently

1. dial 18555446362
2. Select either 1 or 2
3. Hold music loops
4. Call does not get transferred

**Expected behavior**
Call blasting should make all volunteers phone ring at once
Voicemail should come on after 20 secs

**Screenshots**
![Logs-errors-twilio](https://github.com/bmlt-enabled/yap/assets/139581850/d81b734d-af83-433b-a08e-2d6e3c5ccb71)

**Comment by dgershman** [comment]
Reminder, do not post personal or sensitive information here as this is a public website.
