### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by DeathCamel58** [bmlt-enabled/yap#83]
**Is your feature request related to a problem? Please describe.**
We're currently using the Google Maps API for geocoding, but that can be a bit more difficult for less technology savvy people.

**Describe the solution you'd like**
Use [Nominatm](https://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding), which has no API keys, and is based on the open source project [OpenStreetMap](https://openstreetmap.org)

**Describe alternatives you've considered**
Previously answered.

**Additional context**
If I get some time, (possibly tonight), I'll make a PR.

**Comment by DeathCamel58** [comment]
I sent in a PR. It seems to be working, but it'd really help settle me if you tested it a bit more.

**Comment by radius314** [comment]
closing this out due to inactivity
