### ISSUE TITLE
My API is wrong :(

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/yap#837]
**Describe the bug**
1.The API is wrong."I dont remember how to set it."
2. in English, as I explain below, 
3. In French, you can only speak to a volunteer but no meeting location and no Just For Today.

**What version are you running?**
v4.2.10

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
1. Call our region helpline 1 855 544-6362
2. Dial 2 (For English)
3. 
4. An application Error is occured

**Expected behavior**
After the issue
You can dial #1 ask for volunteer ; (works only in french)
You can dial #2 to find a meeting
You can dial #3 to hear the just for today

**Comment by dgershman** [comment]
What is your webhook?

**Comment by Klodd65** [comment]
Voice
Webhook to GET: 
https://yap.membres.naquebec.org/index.php?override_service_body_id=32
Messaging
Webhook to POST: 
https://yap.membres.naquebec.org/sms-gateway.php?override_service_bod

**Comment by dgershman** [comment]
Your server is returning a 500 error on response.  I'm gathering from your subject that you don't know how to set your Twilio Api Key.  If this is your issue, then you need to login into your Twilio account and head to the https://console.twilio.com/us1/account/keys-credentials/api-keys page.  Your api keys will be there and need to be set in your config.php file.  In the future please use Slack for this type of issue, as this is not a bug, and you are looking for support.

**Comment by Klodd65** [comment]
About Twilio, I change the Auth Token string what was wrong. 
Only the Google Account has to be checked. 

What is the Working Team on Slack?

**Comment by dgershman** [comment]
I’m not sure what you are saying.  Is it working now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Klodd65** [comment]
What? Not at all.

**Comment by Klodd65** [comment]
Good it come back when i refresh the page. 
{"status":true,"message":"Ready To Yap!","warnings":"","version":"4.2.10","build":"968207e147cb1c7ffcd654526371b8efbe9dd557"}
I wnat to check everything nowé

**Comment by dgershman** [comment]
Ok is this resolved?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Klodd65** [comment]
Now, none is working :

the system answers right through that "we are sorry, an eror has occured".

Here is the config script
[config.php.docx](https://github.com/bmlt-enabled/yap/files/12909732/config.php.docx)

**Comment by dgershman** [comment]
This is a public site, do not share your config files here.

**Comment by dgershman** [comment]
You were invited to slack https://github.com/bmlt-enabled/yap/issues/837.  In the future, you need to take great care to back up your working configuration before making changes.  It seems like your Yap system is constantly is a state of being broken after it's fixed.
