### ISSUE TITLE
About the new feature could be well in English but a bit wrong in French. We don't use "City" but "Ville".

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/yap#838]
**Describe the bug**
Why does Yap ask for the city "city" instead of our translation php script (en_US, fr_CA, line 43)

**What version are you running?**
v4.2.10

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
Asking 1 (language), choose 1 for French;
Asking 1 ask for a volunteer, 2 to find a meeting, 3 to hear the Just for today, I choose 2 (City)
*New feature: the system ask choose 1 by city, 2 by zip code, 3 listen the Just for Today; I choose 1 by city
 

**Expected behavior**
In French, it is supposed to say "pour quel ville." It doesnt follow the php script  language.
another unexpected argument is we cannot choose Zip Code because we are in  Canada. 

Or is it possible to bypass the feature for us?

**Screenshots**
NA

**Additional context**
we cannot choose Zip Code because we are in  Canada. and in its not the same format ( 6 character alpha-numeric format )

**Comment by dgershman** [comment]
To disable postal code https://yap.bmlt.app/general/disabling-postal-code-gathering/

For the other request reference #843
