### ISSUE TITLE
Reports - No Data after March 3, 2023

### ISSUE THREAD

**Issue by teris222** [bmlt-enabled/yap#839]
**Describe the bug**
No data showing in usage after March 3, 2023.  

**What version are you running?**
v3.9.9

**Did this happen on prior versions to the one you are running?**
Not that I'm aware of.
**To Reproduce**
1. Go to Reports page
2. View Usage visual

**Expected behavior**
Expect data to appear up to the current date.

**Screenshots**
![image](https://github.com/bmlt-enabled/yap/assets/147941719/90dadfab-c374-4881-93ca-9091a40e133f)

**Additional context**

**Comment by dgershman** [comment]
Upgrade to 4.2.11 and let me know if you are still having issues
