### ISSUE TITLE
providing pronunciation hints

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#917]
It would be useful to be able to give yap a hint as to how to pronounce the name of a town when it reads meeting search results.  

For example, if I search for meetings in Yakima, Washington, yap recognizes the town name, but when reading the meetings back, it pronounces it as 'UkEEma'.

**Comment by dgershman** [comment]
I'm pretty sure this would also affect Geocoding responses.  For example if you enter a zip code or say a city or state, it reads back the location.

**Comment by alanb2718** [comment]
Yes, we would want incorrect pronunciations to be fixed for that as well, if possible.

**Comment by dgershman** [comment]
This will be in the next yap 4.3.0 beta

**Comment by dgershman** [comment]
yap 4.3.0 beta 8 was released.

**Comment by alanb2718** [comment]
Alas I'm not having any luck getting pronunciation hints to work. The example in the documentation is for Yakima:
```
static $pronunciations = [[
    "source"=>"Yakima",
    "target"=>"UkEEma"
]];
```

But UkEEma is what Twilio/yap currently says, and isn't correct.  It should be YAKima (/ˈjækɪmɑː/).  I tried various phonetic spellings (YAKima, Yaakima, etc), but none of them changed what was spoken.  Then I tried just "Yak" as the target, to see if it was getting picked up at all, and Twilio/yap is still saying UkEEma.

Should I be doing something different?

**Comment by dgershman** [comment]
Is this still not working?

**Comment by dgershman** [comment]
#943

**Comment by alanb2718** [comment]
Looks like there is a bug in the `pronunciationReplacement` function -- it just works on the first replacement source/target pair.  Need to go through all of the replacements.

**Comment by dgershman** [comment]
Interesting, because `str_replace()` is supposed to replace all occurrences.  Will write another test for this and see what's up.

**Comment by alanb2718** [comment]
The "all occurrences" part is ok.  Here's the function:

```
    private function pronunciationReplacement($subject): string
    {
        foreach ($this->settings->get("pronunciations") as $item) {
            return str_replace($item['source'], $item['target'], $subject);
        }

        return $subject;
    }
}

```
So we iterate through the pronunciations, and return after processing the first item.  So you'd fix all the occurrences of "Sequim", but not "Yakima", for those two pronunciation hints.

**Comment by dgershman** [comment]
gotcha, i understand now what you are saying!
