### ISSUE TITLE
Can't route to volunteers (Sharing the error log)

### ISSUE THREAD

**Issue by sbnawebmaster** [bmlt-enabled/yap#945]
**Describe the bug**
We have been working to set up the YAP for our area but getting "invalid status callback" error (screenshot below). 

![image](https://github.com/bmlt-enabled/yap/assets/162041926/c126746d-a1a4-486f-a738-364348235e22)

We have checked the URL configuration several times and also tried another Twilio account but the same problem occurs. 

**What version are you running?**
v4.2.11

**Did this happen on prior versions to the one you are running?**
This is our first try. 

**Expected behavior**
Everything else is working fine: Reading the meeting directory, and JFT. The problem occurs when we try to route the call to the volunteers. 

**Additional context**
We are SB Area, working Western Zonal Forum.

**Comment by sbnawebmaster** [comment]
Ok. We tried the beta version. This issue is resolved. 
Thank you for letting me be of service.

**Comment by alanb2718** [comment]
We will set up a beta version of yap on the WSZF for Santa Barbara Area to use, since that resolves the issue.  When 3.0.0 is released and we update the regular server they can move back.
