### ISSUE TITLE
settings tab gives an error on 4.3.0-beta10

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#955]
Selecting the Settings tab on yap 4.3.0-beta10 gives a `500 | SERVER ERROR`

The Settings tab is ok on the latest regular release 4.2.11

**To Reproduce**
1. Log in
2. Click on 'Settings'

The laravel.log file is attached.

[laravel.log](https://github.com/bmlt-enabled/yap/files/14563804/laravel.log)

**Comment by dgershman** [comment]
A fix will be available in 4.3.0
