### ISSUE TITLE
Display name_string instead of login_string in admin for page

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#96]
**Is your feature request related to a problem? Please describe.**
login_string sometimes are "Myn@M3" or "$3rVic3" instead of "My Name" and "Service"

**Describe the solution you'd like**
Display name_string instead of login_string

**Comment by radius314** [comment]
Not sure I understand this request.

**Comment by californiasteve** [comment]
Where the "Welcome, californiasteve" it's using the login_string, if we switch it the name_string it would display "California Steve"
![image](https://user-images.githubusercontent.com/31661648/42729375-da25444a-879b-11e8-8598-8a2003c1354c.png)

**Comment by radius314** [comment]
I suppose you are referring to the value coming from the root server.

**Comment by californiasteve** [comment]
I'm sorry, yes this value comes from the root server and displays the login name.

**Comment by radius314** [comment]
Got it.

**Comment by radius314** [comment]
I don't think is possible given the functionality open to us with the BMLT Semantic Administration interface.

**Comment by radius314** [comment]
@litlegreenviper can you validate that it's not possible to get the user information from any semantic interface call?

**Comment by radius314** [comment]
@littlegreenviper can you validate that it's not possible to get the user information from any semantic interface call?

**Comment by pjaudiomv** [comment]
yea I the other day just for the hell of it I scoured through the bmlt docs on the admin api, and came up with same result. didn't think it was possible. but is a cool idea.

**Comment by LittleGreenViper** [comment]
Yes and no.

It is not possible to get admin info from the API (I’ve spent the last couple of months writing a REAL REST API, and can appreciate how pathetic the BMLT one is).

However, any info that you put into meeting records may be accessible if given a visibility of 0 (counterintuitive, but there you have it).

In the default installation, the contact records are visibility 1, which means only logged-in observers can see them. These can be changed on a record-to-record basis, but there’s no GUI to do that.

**Comment by radius314** [comment]
We were looking to get user login specific information.  In this case the “name”.

**Comment by LittleGreenViper** [comment]
In that case, no.

**Comment by radius314** [comment]
That's what I suspected.

**Comment by LittleGreenViper** [comment]
I’m pretty tinfoil, when it comes to security, and I wasn’t confident I could do that securely.

**Comment by radius314** [comment]
I think the way I would do it is to return the details after successful login in the response body.  Rather than return OK return a Json response.

**Comment by LittleGreenViper** [comment]
How do you get californiasteve from the API?

**Comment by radius314** [comment]
I’m not.  It’s just validating the login.  I store the username in session.

**Comment by LittleGreenViper** [comment]
Got it.

Chris Marshall
Geek
Email: cmarshall@mac.com
Web Site: http://cmarshall.com

**Comment by pjaudiomv** [comment]
With the upcoming release of 2.12.5 the root server semantic admin will now have a new parameter `get_user_info` that will enable us to do this feature request. It is in master and destined for v3.

**Comment by radius314** [comment]
@californiasteve can you test this feature to see if it works as you wanted it to?
