### ISSUE TITLE
blast mode not going to voicemail after no volunteers pick up

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#960]
**Describe the bug**
I'm trying to upgrade the WSZF yap server to 4.3.0.  When testing connecting to a volunteer, if someone picks up, all is well.  But if nobody picks up, it just keeps ringing rather than going to voicemail.  (It's in blast then voicemail mode.)

**What version are you running?**
4.3.0

**Did this happen on prior versions to the one you are running?**
No.  I just reverted to 4.2.11, and it's going to voicemail correctly.

**To Reproduce**
1. Set the configuration to blast then voicemail.
2. Call the helpline and ask to speak with a volunteer. 
3. If someone answers, ask them to not answer the next time.
4. Repeat until you end up with yap ringing for several minutes rather than going to voicemail.

**Expected behavior**
Yap should go to voicemail after a minute with nobody answering.

**Screenshots**
There are lots of warnings errors in the Twilio log file - see screenshot.  I can also send laravel.log, but since it contains personally identifying information, I will do that outside of GitHub.

Here are two of the warnings and errors.

```
Error - 16011
Got HTTP 500 response from https://bmlt.wszf.org/yap/helpline-dialer.php?service_body_id=3&Caller=+12067908888&amp;ysk=78157f4d475896e7df8cc05d46bb4b83

Error - 11200
An attempt to retrieve content from https://bmlt.wszf.org/yap/helpline-answer-response.php?conference_name=3_7244582_1710456380&service_body_id=3 returned the HTTP status code 500

```

![twilio-4 3 0-errors](https://github.com/bmlt-enabled/yap/assets/918773/af587294-8f8c-451f-afd3-442ae954706d)

**Comment by dgershman** [comment]
Can you email me the laravel.log?

**Comment by dgershman** [comment]
I see at least one issue that I was able to fix so far.

**Comment by dgershman** [comment]
Can you give this a shot and see if there is any difference?  https://s3.amazonaws.com/archives.bmlt.app/yap/yap-386-f95050ffb21da09f49725c74901d26705cf16327.zip

**Comment by alanb2718** [comment]
Better!  I tried calling a test number with only one volunteer -- yap rang the volunteer and then went to voicemail.  However, I'm still seeing an error in the Twilio error log:

```
Error - 16011
Message
Got HTTP 500 response from https://test.wszf.org/yap/helpline-dialer.php?service_body_id=3&Caller=+12069009004&ysk=f14ff4156125950c6e85ad6a3b3a5e38
```

**Comment by dgershman** [comment]
Ok can you email the log to me?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
I saw the log you emailed last night.  Can you rename your Laravel.log on your test system and then re-run the scenario so it generates clean log data?

From: Danny Gershman ***@***.***>
Date: Friday, March 15, 2024 at 7:54 AM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Your activity ***@***.***>
Subject: Re: [bmlt-enabled/yap] blast mode not going to voicemail after no volunteers pick up (Issue #960)
Ok can you email the log to me?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
Ok try this which fixes those other two errors. https://s3.amazonaws.com/archives.bmlt.app/yap/yap-387-6942479451462b081031f535c9e0852b52421c9c.zip

**Comment by alanb2718** [comment]
It's now usually going to voicemail as desired, and I'm not seeing any Twilio errors.  However, there was one test call that should have gone to voicemail and that instead just kept ringing until I hung up.  I tried to reproduce this but couldn't, so there was some combination of volunteer sending call to voicemail or whatever that tickled it.  I'll email the laravel log.

**Comment by dgershman** [comment]
Ok yes, send it

From: Alan B ***@***.***>
Date: Friday, March 15, 2024 at 11:01 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] blast mode not going to voicemail after no volunteers pick up (Issue #960)

It's now usually going to voicemail as desired, and I'm not seeing any Twilio errors. However, there was one test call that should have gone to voicemail and that instead just kept ringing until I hung up. I tried to reproduce this but couldn't, so there was some combination of volunteer sending call to voicemail or whatever that tickled it. I'll email the laravel log.

**Comment by dgershman** [comment]
Ok fixed another bug , try this one:

https://s3.amazonaws.com/archives.bmlt.app/yap/yap-389-2d0841966c1308f024420944a9a229d62d39b7aa.zip

From: Danny Gershman ***@***.***>
Date: Friday, March 15, 2024 at 11:06 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Your activity ***@***.***>
Subject: Re: [bmlt-enabled/yap] blast mode not going to voicemail after no volunteers pick up (Issue #960)
Ok yes, send it

From: Alan B ***@***.***>
Date: Friday, March 15, 2024 at 11:01 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] blast mode not going to voicemail after no volunteers pick up (Issue #960)

It's now usually going to voicemail as desired, and I'm not seeing any Twilio errors. However, there was one test call that should have gone to voicemail and that instead just kept ringing until I hung up. I tried to reproduce this but couldn't, so there was some combination of volunteer sending call to voicemail or whatever that tickled it. I'll email the laravel log.

**Comment by alanb2718** [comment]
It's working!  (Or to be pessimistically precise, I was unable to cause it to not go to voicemail.)  I tried multiple calls, with various combinations of sending the call to voicemail, hanging up, and just letting it ring; they all worked.  No twilio errors or exceptions in the laravel log.

**Comment by dgershman** [comment]
Ok will close this out.  If you can do additional testing, open a ticket if you find any other issues

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
