### ISSUE TITLE
Can Not Log into Admin, Loops back to Admin page

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#964]
**Describe the bug**
After updating to 4.3.0 I cannot login into the admin panel. After clicking the authenticate button it shows a redirecting message back to the admin page url

**What version are you running?**
4.3.0

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
1. Go to 'https://bmltyap.org/AlSask/admin'
2. Click on 'authenticate'
3. See error

**Expected behavior**
Login into admin area

**Screenshots**

**Additional context**
From Twilio error log, parserMessage

Error on line 27 of document : The processing instruction target matching "[xX][mM][lL]" is not allowed.

ErrorCode

12100

**Comment by dgershman** [comment]
Are you entering credentials or simply clicking the Authenticate button?  Yap user or BMLT user?

**Comment by californiasteve** [comment]
Yap user entering credentials

**Comment by dgershman** [comment]
I believe the issue to be environmental.

**Comment by dgershman** [comment]
found the fix for this duplicate of #973, will be yap 4.3.2
