### ISSUE TITLE
blasting then voicemail doesn't work if there is an invalid or disconnected number among the volunteers

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#971]
**Describe the bug (or maybe it's an enhancement??)**
If one of the volunteers has a disconnected number, blasting then voicemail never goes to voicemail -- it just keeps ringing.

**What version are you running?**
4.3.1-beta1

**Did this happen on prior versions to the one you are running?**
Yes, something like this happened also with 4.2.11.

**To Reproduce**
1. Set up yap for blasting then voicemail.
2. Add a disconnected or otherwise bad number to the volunteers list.  (To reproduce, I used a recently released Twilio number.)
3. Call the helpline and ask to talk with a volunteer.

**Expected behavior**
If one of the numbers is bad, I would expect yap in blast mode to still go to voicemail after the timeout.  Ideally there would be a report also regarding the bad number.

**Additional context**
The Twilio log for the test helpline number says that the released number was busy; there wasn't an error otherwise. I encountered something similar when trying to bring a new area on to yap.  It turns out the helpline coordinator just copied over the numbers from their old installation but didn't test them.  One of those numbers was bad -- not sure how since I didn't try to debug carefully at the time -- but that one gave an error on the Twilio log (which is how we discovered the problem). Same thing happened -- calls just kept ringing and never went to voicemail.

**Comment by dgershman** [comment]
I was able to reproduce this.  This is an old bug and it deserves to be fixed!

**Comment by dgershman** [comment]
The same issue occurs for any call strategy and anytime you use a number that doesn't exist.

**Comment by dgershman** [comment]
fix coming in 4.3.4

**Comment by dgershman** [comment]
![Screenshot 2024-05-04 at 5 11 28 PM](https://github.com/bmlt-enabled/yap/assets/1850811/9a8e3ed7-e2ec-4477-ae82-5877f17111b8)
![Screenshot 2024-05-04 at 5 11 15 PM](https://github.com/bmlt-enabled/yap/assets/1850811/04782dd7-974f-4fd6-a415-2977b457e4be)

**Comment by alanb2718** [comment]
I tried the fix in 4.3.4-beta1, and alas it's still hanging and not sending the call to voicemail when there is a bad number -- at least of a particular kind -- in the volunteer list.  (The number that causes this problem  is a Twilio number that we returned to the pool.)  I'll send you a screenshot similar to the one above, and the laravel log, as a DM.  (It's got my own number in it as well so I won't put it here.)

Then I tried it with the bad number in the screenshot above (212-555-5555) and it **did** send the call to voicemail.

**Comment by dgershman** [comment]
Ok I’ll test this other use case.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
figured out what the difference is.  these released numbers return a busy signal, not a failure.

**Comment by dgershman** [comment]
working on a fix now.

**Comment by dgershman** [comment]
Try with 4.3.4-beta2

**Comment by alanb2718** [comment]
Working for both numbers now (the one that fails and the one that gives a busy signal).  One thing I did not test is having a volunteer who never answers and who does not have voicemail -- I don't have a number handy with that behavior.  Is that already known to work?

**Comment by dgershman** [comment]
If they don't press 1 after answering it will result in a timeout.

**Comment by alanb2718** [comment]
What happens if they never answer?

**Comment by dgershman** [comment]
It times out after whatever the setting is.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
