### ISSUE TITLE
Cannot save some volunteers

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/yap#975]
Affects: Yap 4.3.0 + 4.3.1

Steps to reproduce:

1. Log in to the test server https://test.wszf.org/yap/admin, user WesternStatesZonalForum.
2. Go to Volunteers for Washington / Northern Idaho Region.
3. Make a change (enabling or disabling a volunteer), and try to save.
4. Notice that the change does not get saved.

**Expected behavior**
Should be able to log in, or save the results of the edit.

![314367069-6a674093-8b8d-4a97-801f-771dfdfdbf3b](https://github.com/bmlt-enabled/yap/assets/1850811/598a0aae-af93-4f9f-b352-138dd624fd2c)

**Comment by dgershman** [comment]
@alanb2718 you have a bunch of empty volunteers.  The validation is failing because no number is specified.  If you delete those empty ones, you should be able to save the list.  I will work on better messaging for 4.3.2.

**Comment by dgershman** [comment]
@alanb2718 can you try this patch for this issue? https://s3.amazonaws.com/archives.bmlt.app/yap/yap-395-731bec0d3586b55e4a97e33a9ca943338b39db65.zip

**Comment by alanb2718** [comment]
That fixes the problem with the empty volunteers!  It also catches some badly formed numbers, for example `206 555`.

But for other badly formed numbers (for example `206 555 z 4444`) it still fails silently -- just doesn't save.  For that number the Javascript console says there is an uncaught `NOT_A_NUMBER` exception.

**Comment by dgershman** [comment]
Got another fix coming.

**Comment by dgershman** [comment]
@alanb2718 give this one a shot https://s3.amazonaws.com/archives.bmlt.app/yap/yap-398-4ecb9d968b896eac17c5a4fdf64958d2f6c3e324.zip

**Comment by alanb2718** [comment]
It works!

**Comment by dgershman** [comment]
Will be in 4.3.2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
