### ISSUE TITLE
recurse switch on reports page has no effect

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#980]
**Describe the bug**
When accessing the reports for a region, the recurse switch on the reports page has no effect: you always see the calls for the region as a whole and all its areas, whether or not the switch is on or off.

**What version are you running?**
4.3.2

**Did this happen on prior versions to the one you are running?**
No.  This works ok on 4.2.11

**To Reproduce**
1. Access the reports for a region that has several areas with helplines.  I used the WSZF server, and accessed both Washington / Northern Idaho Region and Northern California Region.
2. Slide the "recurse" switch to off.
3. See calls for the areas under that region, as well as regional calls (if there is a regional helpline).

**Expected behavior**
Flipping the recurse switch to off on a region should show only calls to the regional helpline if there is one, and otherwise no calls.

**Additional context**
Washington / Northern Idaho Region has a regional helpline; Northern California Region does not.

**Comment by dgershman** [comment]
Can you try out yap 4.3.3-beta1?  https://github.com/bmlt-enabled/yap/releases/download/4.3.3-beta1/yap-4.3.3-beta1.zip

**Comment by alanb2718** [comment]
It's working well!
