### ISSUE TITLE
Static overrides not working after upgrade to 4.3.2

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#997]
**Describe the bug**
The following overrides are configured however the system still reads out "State or Province" and "City or County"

static $override_state_or_province = "state or territory";
static $override_city_or_county = "city or suburb";

**What version are you running?**
4.3.2

**Did this happen on prior versions to the one you are running?**
No
**To Reproduce**
Contact the helpline and start a volunteer search.

**Expected behavior**
overrides will be parsed

**Screenshots**
na

**Additional context**
Copied previous config file over to new directory when upgrading.

**Comment by dgershman** [comment]
4.3.3 was released.
